import { db, SUPABASE_URL, connection, vaultRead, patchConnection, storeAsset, parseMp4Basic } from "./runtime.ts";

const GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta";
const FALLBACK_TEXT_MODEL = "gemini-2.5-flash";
const FALLBACK_VEO_MODEL = "veo-3.1-fast-generate-preview";
const FIXTURE_VIDEO_URL = "https://raw.githubusercontent.com/JuanManuelPM/prometeo/work/youtube-creator-runtime-20260910/tests/fixtures/creator/vertical-144x256.mp4";
const timeout=(ms:number)=>AbortSignal.timeout(ms);

async function geminiSecret(owner:string){const c=await connection(owner,"llm","gemini");if(c?.mode!=="VERIFIED_REAL"||!c.vault_secret_id)return null;return {key:await vaultRead(c.vault_secret_id),connection:c}}
function responseText(p:any){return p?.candidates?.[0]?.content?.parts?.map((x:any)=>x.text||"").join("")||""}
async function geminiJSON(owner:string,prompt:string,schema:any,system?:string){
  const g=await geminiSecret(owner);if(!g?.key)return null;
  const model=String(g.connection?.metadata?.text_model||FALLBACK_TEXT_MODEL);
  const body:any={contents:[{role:"user",parts:[{text:prompt}]}],generationConfig:{responseMimeType:"application/json",responseSchema:schema}};
  if(system)body.systemInstruction={parts:[{text:system}]};
  const r=await fetch(`${GEMINI_BASE}/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",signal:timeout(45000),headers:{"x-goog-api-key":String(g.key),"Content-Type":"application/json"},body:JSON.stringify(body)});
  const p:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`GEMINI_${r.status}:${p?.error?.message||"failed"}`);
  const t=responseText(p);if(!t)throw new Error("GEMINI_EMPTY_RESPONSE");return JSON.parse(t);
}

export async function generateIdeas(job:any){
  const {data:ch,error}=await db.from("creator_channels").select("*").eq("id",job.channel_id).eq("owner_id",job.owner_id).single();if(error)throw error;
  const count=Math.max(1,Math.min(30,Number(job.input?.count||12)));
  const schema={type:"array",items:{type:"object",properties:{title:{type:"string"},hook:{type:"string"},premise:{type:"string"},story_angle:{type:"string"},target_duration_seconds:{type:"integer"},novelty_score:{type:"number"},channel_fit_score:{type:"number"}},required:["title","hook","premise","story_angle","target_duration_seconds"]}};
  let ideas:any[]|null=null,source="MOCK";
  try{const p=`Generá ${count} ideas distintas para ${ch.title}. CHANNEL_WORLD=${JSON.stringify(ch.world)} BRIEF=${JSON.stringify(job.input?.brief||null)}`;const x=await geminiJSON(job.owner_id,p,schema,"Devolvé conceptos filmables para Short vertical y evitá repeticiones.");if(Array.isArray(x)){ideas=x.slice(0,count);source="GEMINI"}}catch(e){console.error("gemini ideas fallback",e)}
  if(!ideas){const names=["La llamada que nadie debía atender","El secreto detrás de la puerta","Una promesa hecha demasiado tarde","La carta que cambia todo","El invitado que reconoce la mentira","La decisión que divide a la familia","El objeto que aparece dos veces","La confesión antes de la fiesta","La persona que vuelve sin avisar","El testamento con una segunda página","El mensaje enviado al contacto equivocado","La foto tomada antes de que ocurriera"];ideas=Array.from({length:count},(_,i)=>({title:names[i%names.length]+(i>=names.length?` ${Math.floor(i/names.length)+1}`:""),hook:"Una contradicción aparece en los primeros dos segundos.",premise:`Fixture estructurado ${i+1}`,story_angle:["traición","revelación","malentendido","elección imposible"][i%4],target_duration_seconds:24+(i%4)*4,novelty_score:.7+(i%5)*.04,channel_fit_score:.75+(i%4)*.04}))}
  const rows=ideas.map((x:any,i:number)=>({owner_id:job.owner_id,channel_id:job.channel_id,title:String(x.title||`Idea ${i+1}`).slice(0,180),hook:String(x.hook||"").slice(0,500),state:"IDEA",format:"SHORT_9_16",target_duration_ms:Math.max(8000,Math.min(180000,Number(x.target_duration_seconds||30)*1000)),idempotency_key:`idea:${job.id}:${i}`,creative:{premise:x.premise||"",story_angle:x.story_angle||"",novelty_score:x.novelty_score??null,channel_fit_score:x.channel_fit_score??null,generation_source:source,generation_job_id:job.id},metadata:{provenance:source}}));
  const {data,error:ie}=await db.from("creator_videos").upsert(rows,{onConflict:"owner_id,idempotency_key",ignoreDuplicates:true}).select();if(ie)throw ie;return {source,count:(data||[]).length||rows.length,video_ids:(data||[]).map((x:any)=>x.id)};
}

export async function ensureCreativePackage(job:any){
  const {data:v,error}=await db.from("creator_videos").select("*,creator_channels(*),creator_stories(*)").eq("id",job.video_id).eq("owner_id",job.owner_id).single();if(error)throw error;
  const existing=await db.from("creator_scripts").select("*").eq("video_id",v.id).eq("owner_id",job.owner_id).eq("selected",true).maybeSingle();
  if(existing.data){const scenes=await db.from("creator_scenes").select("*").eq("video_id",v.id).order("scene_no");return {video:v,script:existing.data,scenes:scenes.data||[],source:existing.data.score?.source||"EXISTING"}}
  let pkg:any=null,source="MOCK";
  const schema={type:"object",properties:{title:{type:"string"},hook:{type:"string"},voice_script:{type:"string"},scenes:{type:"array",items:{type:"object",properties:{spoken_text:{type:"string"},visual_goal:{type:"string"},subject:{type:"string"},action:{type:"string"},environment:{type:"string"},camera:{type:"string"},movement:{type:"string"},lighting:{type:"string"},continuity:{type:"string"}},required:["spoken_text","visual_goal","subject","action"]}}},required:["title","hook","voice_script","scenes"]};
  try{const p=`Convertí esta idea en Short. CHANNEL=${JSON.stringify(v.creator_channels?.world||{})} STORY=${JSON.stringify(v.creator_stories||null)} VIDEO=${JSON.stringify({title:v.title,hook:v.hook,creative:v.creative,target_duration_ms:v.target_duration_ms})}`;pkg=await geminiJSON(job.owner_id,p,schema,"Diseñá narración y visual juntos y preservá continuidad.");if(pkg)source="GEMINI"}catch(e){console.error("gemini creative fallback",e)}
  if(!pkg){const chars=v.creator_channels?.world?.characters||["protagonista","rival"],a=chars[0]||"protagonista",b=chars[1]||"rival";pkg={title:v.title,hook:v.hook||`Algo cambia para ${a}.`,voice_script:`${a} cree que todo está resuelto. Entonces ${b} aparece con una prueba.`,scenes:[{spoken_text:`${a} cree que todo está resuelto.`,visual_goal:`Presentar a ${a}.`,subject:a,action:"mira un objeto decisivo",environment:"interior simple",camera:"primer plano",movement:"acercamiento",lighting:"suave",continuity:"identidad estable"},{spoken_text:`Entonces ${b} aparece con una prueba.`,visual_goal:`Introducir a ${b}.`,subject:b,action:"entra y muestra la prueba",environment:"mismo interior",camera:"plano medio",movement:"paneo corto",lighting:"igual",continuity:"mantener posiciones"},{spoken_text:"La historia ya no puede volver atrás.",visual_goal:"Cliffhanger.",subject:a,action:"reacciona",environment:"mismo interior",camera:"close-up",movement:"quieto",lighting:"igual",continuity:"misma identidad"}]}}
  const target=Math.max(8000,Number(v.target_duration_ms||30000)),n=Math.max(1,pkg.scenes.length),seg=Math.floor(target/n);
  const {data:script,error:se}=await db.from("creator_scripts").insert({owner_id:job.owner_id,video_id:v.id,version:1,script:pkg.scenes.map((s:any)=>s.spoken_text).join(" "),voice_script:pkg.voice_script||pkg.scenes.map((s:any)=>s.spoken_text).join(" "),structure:pkg.scenes.map((s:any,i:number)=>({scene_no:i+1,start_ms:i*seg,end_ms:i===n-1?target:(i+1)*seg,visual_goal:s.visual_goal})),score:{source},selected:true}).select().single();if(se)throw se;
  await db.from("creator_videos").update({title:String(pkg.title||v.title).slice(0,180),hook:String(pkg.hook||v.hook||"").slice(0,500),state:"PREPARED",creative:{...(v.creative||{}),creative_package_source:source}}).eq("id",v.id);
  const sceneRows=pkg.scenes.map((s:any,i:number)=>({owner_id:job.owner_id,video_id:v.id,script_id:script.id,scene_no:i+1,start_ms:i*seg,end_ms:i===n-1?target:(i+1)*seg,spoken_text:s.spoken_text||"",visual_goal:s.visual_goal||"",scene_spec:{subject:s.subject||"",action:s.action||"",environment:s.environment||"",camera:s.camera||"",movement:s.movement||"",lighting:s.lighting||"",continuity_from_previous:s.continuity||""},state:"PLANNED"}));
  const {data:scenes,error:sce}=await db.from("creator_scenes").upsert(sceneRows,{onConflict:"video_id,scene_no"}).select();if(sce)throw sce;
  for(const s of scenes||[]){const q=s.scene_spec||{};await db.from("creator_prompts").insert({owner_id:job.owner_id,video_id:v.id,scene_id:s.id,kind:"VIDEO_SCENE",provider:"conceptual",conceptual:{...q,visual_goal:s.visual_goal,spoken_text:s.spoken_text},compiled_text:`Vertical 9:16. Subject: ${q.subject}. Action: ${q.action}. Environment: ${q.environment}. Camera: ${q.camera}. Movement: ${q.movement}. Lighting: ${q.lighting}. Continuity: ${q.continuity_from_previous}. Goal: ${s.visual_goal}. Avoid unreadable text, identity changes and duplicated objects.`,compiler_version:"creator-prompt-v3"})}
  return {video:{...v,title:pkg.title||v.title,hook:pkg.hook||v.hook,state:"PREPARED"},script,scenes:scenes||[],source};
}

export async function maybeGenerateVoice(owner:string,channelId:string,videoId:string,text:string,voice="es-AR-TomasNeural"){
  const existing=await db.from("creator_assets").select("*").eq("owner_id",owner).eq("video_id",videoId).eq("kind","VOICE").maybeSingle();if(existing.data)return existing.data;
  try{const r=await fetch(`${SUPABASE_URL}/functions/v1/casa-tts`,{method:"POST",signal:timeout(12000),headers:{"Content-Type":"application/json"},body:JSON.stringify({text:text.slice(0,300),voice})});if(!r.ok)throw new Error(`EDGE_TTS_${r.status}`);const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.byteLength<100)throw new Error("EDGE_TTS_EMPTY");const asset=await storeAsset({owner,channelId,videoId,kind:"VOICE",bytes,mime:r.headers.get("content-type")||"audio/mpeg",provider:"edge-neural",pathSuffix:"voice.mp3",metadata:{voice}});await patchConnection(owner,"voice","edge-neural",{mode:"VERIFIED_REAL",verified_at:new Date().toISOString(),last_probe:{ok:true,bytes:bytes.byteLength},last_error:null,metadata:{function:"casa-tts",credential_required:false}}).catch(()=>{});return asset}catch(e){await patchConnection(owner,"voice","edge-neural",{mode:"BLOCKED",last_probe:{ok:false},last_error:{message:String((e as any)?.message||e)}}).catch(()=>{});return null}
}

export async function fetchFixtureVideo(){const r=await fetch(FIXTURE_VIDEO_URL,{signal:timeout(12000),redirect:"follow"});if(!r.ok)throw new Error(`FIXTURE_HTTP_${r.status}`);const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.byteLength<1000)throw new Error("FIXTURE_TOO_SMALL");const probe=parseMp4Basic(bytes);if(!probe.ok||probe.vertical_9_16!==true)throw new Error(`FIXTURE_INVALID:${JSON.stringify(probe)}`);return {bytes,url:FIXTURE_VIDEO_URL,probe}}
export async function getVideoStrategy(owner:string,maxCostCents:number){const veo=await connection(owner,"video","veo");const allowed=veo&&["CONFIGURED","VERIFIED_REAL"].includes(veo.mode)&&veo.vault_secret_id&&veo.metadata?.spend_allowed===true;const model=String(veo?.metadata?.video_model||veo?.metadata?.default_model||FALLBACK_VEO_MODEL);const estimated=Number(veo?.metadata?.estimated_cost_cents_8s||80);if(allowed&&estimated<=maxCostCents)return {kind:"VEO" as const,connection:veo,model,estimated_cost_cents:estimated};return {kind:"FIXTURE" as const,reason:!veo?"NO_VIDEO_PROVIDER":veo.metadata?.spend_allowed!==true?"PAID_SPEND_NOT_AUTHORIZED":estimated>maxCostCents?"COST_BUDGET":"PROVIDER_NOT_READY",estimated_cost_cents:0}}
export async function submitVeo(owner:string,prompt:string,model:string){const c=await connection(owner,"video","veo");if(!c?.vault_secret_id)throw new Error("VEO_SECRET_MISSING");const key=await vaultRead(c.vault_secret_id);if(!key)throw new Error("VEO_SECRET_EMPTY");const r=await fetch(`${GEMINI_BASE}/models/${encodeURIComponent(model)}:predictLongRunning`,{method:"POST",signal:timeout(30000),headers:{"x-goog-api-key":String(key),"Content-Type":"application/json"},body:JSON.stringify({instances:[{prompt}],parameters:{aspectRatio:"9:16",durationSeconds:"8",resolution:"720p"}})});const p:any=await r.json().catch(()=>({}));if(!r.ok||!p.name)throw new Error(`VEO_SUBMIT_${r.status}:${p?.error?.message||"missing operation"}`);return {operation:String(p.name)}}
export async function pollVeo(owner:string,operation:string){const c=await connection(owner,"video","veo");if(!c?.vault_secret_id)throw new Error("VEO_SECRET_MISSING");const key=await vaultRead(c.vault_secret_id);if(!key)throw new Error("VEO_SECRET_EMPTY");const r=await fetch(`${GEMINI_BASE}/${operation}`,{signal:timeout(30000),headers:{"x-goog-api-key":String(key)}});const p:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`VEO_POLL_${r.status}:${p?.error?.message||"poll failed"}`);if(!p.done)return {done:false as const};if(p.error)throw new Error(`VEO_OPERATION:${p.error.message||JSON.stringify(p.error)}`);const uri=p?.response?.generateVideoResponse?.generatedSamples?.[0]?.video?.uri||p?.response?.generatedVideos?.[0]?.video?.uri||p?.response?.generated_videos?.[0]?.video?.uri;if(!uri)throw new Error("VEO_DONE_WITHOUT_VIDEO_URI");const vr=await fetch(uri,{signal:timeout(60000),headers:{"x-goog-api-key":String(key)},redirect:"follow"});if(!vr.ok)throw new Error(`VEO_DOWNLOAD_${vr.status}`);const bytes=new Uint8Array(await vr.arrayBuffer());return {done:true as const,bytes,probe:parseMp4Basic(bytes),uri}}
