(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const DATA=[
{t:'Noción de sujeto',s:'La unidad de análisis se amplía: del individuo aislado al sujeto-en-relación y en contexto.',k:'sujeto monádico · sujeto relacional · contexto',d:['La perspectiva sistémica deja de explicar una conducta sólo por propiedades internas. Pregunta qué relaciones, secuencias y contextos la mantienen o le dan sentido.','La causalidad deja de pensarse como una flecha única A→B y pasa a una lógica circular: A influye en B y B modifica a A dentro de una secuencia.'],q:[['¿Qué cambia en la noción de sujeto?','Pasa de un sujeto aislado e intrapsíquico a un sujeto relacional y contextual; la unidad de análisis incluye vínculos y patrones de interacción.'],['¿Qué significa causalidad circular?','Que los efectos vuelven sobre las condiciones que los produjeron: no hay una causa única, sino influencias recíprocas dentro de un circuito.']],visual:['sujeto relacional psicología sistémica','causalidad circular sistema','contexto relaciones psicología']},
{t:'Teoría General de los Sistemas',s:'Un sistema es una totalidad organizada: importan los elementos, pero sobre todo sus relaciones y patrones de organización.',k:'totalidad · sistema abierto · homeostasis · equifinalidad',d:['Un sistema no se entiende sumando partes aisladas. Sus propiedades emergen de la organización y de las relaciones entre sus componentes.','Los sistemas abiertos intercambian materia, energía o información con el entorno. Pueden conservar organización mediante homeostasis o cambiar mediante procesos morfogenéticos.'],q:[['¿Qué significa totalidad?','Que el sistema posee propiedades que dependen de la organización del conjunto y no pueden reducirse a una sola parte.'],['¿Qué es equifinalidad?','Que condiciones iniciales diferentes pueden conducir a estados finales semejantes.']],visual:['general systems theory diagram','open system homeostasis','equifinality system']},
{t:'Cibernética',s:'La cibernética estudia regulación y control mediante circuitos de retroalimentación.',k:'feedback · regulación · cambio · observador',d:['La retroalimentación negativa reduce desviaciones y favorece estabilidad. La positiva amplifica desviaciones y puede impulsar cambio. Ninguna es buena o mala por sí misma.','La segunda cibernética incluye al observador dentro del sistema observado: observar también modifica la descripción de aquello que se observa.'],q:[['¿Feedback negativo significa algo malo?','No. Significa reducción de desviación respecto de un patrón; suele estabilizar el sistema.'],['¿Primera vs segunda cibernética?','En la primera el observador se piensa fuera del sistema; en la segunda se reconoce que el observador participa en la construcción de lo observado.']],visual:['cybernetics feedback loop','negative positive feedback diagram','second order cybernetics observer']},
{t:'Teoría de la información',s:'La información reduce incertidumbre; en Bateson, es una diferencia que produce una diferencia para algún sistema.',k:'información · diferencia · ruido · redundancia',d:['En Shannon-Weaver aparecen fuente, mensaje, canal, receptor y ruido. La información puede pensarse como reducción de posibilidades o incertidumbre.','Bateson desplaza el foco del mensaje como objeto a la diferencia relevante para un sistema: no toda diferencia informa, sólo la que produce alguna modificación.'],q:[['¿Qué es información para Bateson?','Una diferencia que produce una diferencia en algún sistema capaz de responder a ella.'],['¿Qué función cumple el ruido?','Introduce perturbaciones en la transmisión y puede aumentar la incertidumbre o dificultar la reconstrucción del mensaje.']],visual:['information theory Shannon Weaver diagram','difference that makes a difference Bateson','noise redundancy information']},
{t:'Teoría de la Comunicación Humana',s:'Toda conducta en una interacción puede adquirir valor comunicacional y organizar una relación.',k:'axiomas · metacomunicación · puntuación · digital/analógico',d:['Los cinco axiomas: es imposible no comunicar; toda comunicación tiene contenido y relación; cada participante puntúa la secuencia; usamos modalidades digital y analógica; las relaciones pueden organizarse simétrica o complementariamente.','Los problemas aparecen cuando se confunden niveles, se puntúan de modo incompatible las secuencias, se traducen mal mensajes analógicos/digitales o se rigidizan patrones simétricos o complementarios.'],q:[['¿Qué significa contenido y relación?','Todo mensaje dice algo sobre un contenido y, al mismo tiempo, define cómo debe entenderse la relación entre los participantes.'],['¿Qué es puntuación de la secuencia?','La manera en que cada participante organiza dónde empieza y por qué continúa una interacción; puntuaciones distintas pueden sostener conflictos.']],visual:['communication axioms Watzlawick','communication content relationship diagram','symmetric complementary communication']},
{t:'Constructivismo y construccionismo',s:'El conocimiento y los significados no son copias neutras: se construyen desde marcos, relaciones, lenguaje y prácticas.',k:'observador · realidad · lenguaje · construcción social',d:['El constructivismo subraya que el observador participa activamente en la construcción del conocimiento. Watzlawick diferencia realidad de primer orden y realidad de segundo orden.','El construccionismo social desplaza el foco hacia cómo lenguaje, discursos, prácticas y relaciones producen significados y realidades compartidas.'],q:[['¿Constructivismo vs construccionismo?','El constructivismo enfatiza la construcción del conocimiento por el observador; el construccionismo enfatiza la producción social y lingüística de significados.'],['¿Realidad de primer y segundo orden?','La primera refiere a propiedades y regularidades empíricas; la segunda a significados, valores e interpretaciones atribuidas.']],visual:['constructivism reality Watzlawick','social constructionism language','Flatland perception constructivism']},
{t:'Modelo de mente de Bateson',s:'La mente puede entenderse como un sistema distribuido de diferencias, transformaciones y circuitos autocorrectivos.',k:'patrón que conecta · diferencia · circuito · tipos lógicos',d:['Para Bateson la mente no se reduce necesariamente al interior del cráneo. Puede describirse a escala de un circuito organizado que incluye organismo, ambiente y flujos de información.','Entre sus criterios aparecen partes interactuantes, diferencias que desencadenan procesos, energía colateral, cadenas circulares, transformaciones de diferencias y jerarquías de tipos lógicos.'],q:[['¿Por qué la mente puede extenderse más allá de la piel?','Porque la unidad relevante puede ser el circuito completo de diferencias y retroalimentaciones del que participa el organismo.'],['¿Qué significa mapa ≠ territorio?','Que una representación o descripción nunca es idéntica a aquello que representa; selecciona diferencias según un marco.']],visual:['Gregory Bateson mind ecology','Bateson pattern that connects','mind system feedback Bateson']}
];
const PHASES=['Resumen','Profundidad','Reforzar'];
let old={};try{old=JSON.parse(localStorage.getItem('m3cleanV5')||'{}')}catch{}
let S={};try{S=JSON.parse(localStorage.getItem('m3cleanV6')||'{}')}catch{}
if(!S.states)S.states=old.states||DATA.map(()=>['','','']);
if(!S.boards)S.boards={};
if(old.boards&&Object.keys(S.boards).length===0)S.boards=old.boards;
let unit=0,phase=0,view='home';
function save(){localStorage.setItem('m3cleanV6',JSON.stringify(S))}
function statusClass(v){return v==='good'?'good':v==='review'?'review':''}
function renderHome(){view='home';$('#home').style.display='block';$('#topic').classList.remove('active');$('#bottom').classList.remove('show');$('#home').innerHTML=`<div class="homeIntro">7 unidades</div>${DATA.map((x,i)=>`<button class="topicCard" data-u="${i}"><span class="num">${String(i+1).padStart(2,'0')}</span><h2>${x.t}</h2><p>${x.s}</p><span class="topicStatus">${S.states[i].map(v=>`<i class="${statusClass(v)}"></i>`).join('')}</span></button>`).join('')}`;$$('.topicCard').forEach(b=>b.onclick=()=>openUnit(+b.dataset.u,phase));scrollTo(0,0)}
function openUnit(i,p=phase){unit=Math.max(0,Math.min(DATA.length-1,i));phase=Math.max(0,Math.min(2,p));view='topic';$('#home').style.display='none';$('#topic').classList.add('active');$('#bottom').classList.add('show');renderTopic();scrollTo(0,0)}
function renderTopic(){const x=DATA[unit];let body='';if(phase===0)body=`<div class="copy"><p>${x.s}</p></div><div class="keys">${x.k}</div>`;if(phase===1)body=`<div class="depth">${x.d.map((p,i)=>`<h3>${String(i+1).padStart(2,'0')}</h3><p>${p}</p>`).join('')}</div>`;if(phase===2)body=`<div class="reinforce">${x.q.map(([q,a])=>`<div class="qa"><strong>${q}</strong><button type="button">Ver respuesta</button><div class="answer">${a}</div></div>`).join('')}</div>`;$('#topic').innerHTML=`<div class="topicNav"><button class="backBtn" id="backHome" aria-label="Volver">‹</button><div class="topicMeta">U${unit+1} / ${DATA.length} · ${PHASES[phase]}</div></div><div class="topicHead"><h1>${x.t}</h1></div>${body}<div class="phaseTail"><span>${PHASES[phase]} · ${phase+1}/3</span><span class="phaseDots">${[0,1,2].map(i=>`<i class="${i<phase?'done':i===phase?'current':''}"></i>`).join('')}</span></div><div class="swipehint">deslizá horizontalmente para cambiar de unidad</div>`;$('#backHome').onclick=renderHome;$$('.qa button').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'));syncBottom()}
function syncBottom(){const st=S.states[unit][phase];$('#reviewBtn').classList.toggle('on',st==='review');$('#goodBtn').classList.toggle('on',st==='good');$('#reviewBtn').setAttribute('aria-pressed',st==='review');$('#goodBtn').setAttribute('aria-pressed',st==='good')}
function toggleState(v){S.states[unit][phase]=S.states[unit][phase]===v?'':v;save();syncBottom()}
$('#reviewBtn').onclick=()=>toggleState('review');$('#goodBtn').onclick=()=>toggleState('good');
function showPhaseToast(){const t=$('#phaseToast');t.textContent=`${PHASES[phase]} · ${phase+1}/3`;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),720)}
function reinforceQueue(){const q=DATA.map((_,i)=>i).filter(i=>S.states[i][0]!=='good'||S.states[i][1]!=='good'||S.states[i][2]==='review'||!S.states[i][2]);return q.length?q:DATA.map((_,i)=>i)}
function goNext(){if(phase<2){if(unit<DATA.length-1){openUnit(unit+1,phase);return}phase++;unit=0;showPhaseToast();setTimeout(()=>openUnit(0,phase),100);return}const q=reinforceQueue(),idx=q.indexOf(unit);if(idx>=0&&idx<q.length-1){openUnit(q[idx+1],2);return}renderHome();showPhaseToast()}
function goPrev(){if(phase===2){const q=reinforceQueue(),idx=q.indexOf(unit);if(idx>0){openUnit(q[idx-1],2);return}}if(unit>0){openUnit(unit-1,phase);return}if(phase>0){phase--;openUnit(DATA.length-1,phase)}}
$('#nextBtn').onclick=goNext;$('#homeBtn').onclick=renderHome;$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');S.dark=document.body.classList.contains('dark');save()};if(S.dark)document.body.classList.add('dark');
let sx=0,sy=0,swiping=false;$('#topic').addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'||e.target.closest('button,input,canvas'))return;sx=e.clientX;sy=e.clientY;swiping=true},{passive:true});$('#topic').addEventListener('pointerup',e=>{if(!swiping)return;swiping=false;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)>58&&Math.abs(dx)>Math.abs(dy)*1.25){if(dx<0){if(unit<DATA.length-1)openUnit(unit+1,phase);else goNext()}else goPrev()}},{passive:true});window.addEventListener('keydown',e=>{if(view!=='topic'||$('#board').classList.contains('open'))return;if(e.key==='ArrowRight')goNext();if(e.key==='ArrowLeft')goPrev()});

/* ---------- WHITEBOARD ---------- */
const B=$('#board'),C=$('#boardCanvas'),ctx=C.getContext('2d'),wrap=$('#canvasWrap');
let boardTool='select',lineStyle='arrow',boardColor='#111111',boardWidth=3,selected=[],drawing=null,gesture=null,lasso=null,penSeen=false,currentEmoji='💡';
const history=new Map(),redoHistory=new Map(),imageCache=new Map();
function migrateBoard(b){if(!b.objects)b.objects=[];if(b.strokes){b.strokes.forEach(s=>b.objects.push({id:uid(),type:s.type==='arrow'?'line':'stroke',points:s.points||[],color:s.color||'#111',width:s.w||3,style:s.type==='arrow'?'arrow':s.type==='high'?'high':'pen'}));delete b.strokes}if(b.emojis){b.emojis.forEach(e=>b.objects.push({id:uid(),type:'emoji',x:e.x||.5,y:e.y||.5,size:44,char:e.c||'💡'}));delete b.emojis}return b}
function boardState(){const b=S.boards[unit]||(S.boards[unit]={objects:[]});return migrateBoard(b)}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function snap(){return JSON.stringify(boardState().objects)}
function beginHistory(){const h=history.get(unit)||[];const s=snap();if(h[h.length-1]!==s)h.push(s);if(h.length>60)h.shift();history.set(unit,h);redoHistory.set(unit,[])}
function restore(str){boardState().objects=JSON.parse(str);selected=[];save();renderBoard();syncSelectionBar()}
function undo(){const h=history.get(unit)||[];if(!h.length)return;const r=redoHistory.get(unit)||[];r.push(snap());redoHistory.set(unit,r);restore(h.pop());history.set(unit,h)}
function redo(){const r=redoHistory.get(unit)||[];if(!r.length)return;const h=history.get(unit)||[];h.push(snap());history.set(unit,h);restore(r.pop());redoHistory.set(unit,r)}
function size(){const r=C.getBoundingClientRect();return{w:r.width,h:r.height,left:r.left,top:r.top}}
function pnorm(e){const r=size();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.w)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.h))}}
function resizeCanvas(){const r=size();if(r.w<2||r.h<2)return;const d=Math.min(devicePixelRatio||1,2);C.width=Math.round(r.w*d);C.height=Math.round(r.h*d);ctx.setTransform(d,0,0,d,0,0);renderBoard()}
new ResizeObserver(resizeCanvas).observe(wrap);
function loadImg(src){if(imageCache.has(src))return imageCache.get(src);const im=new Image();imageCache.set(src,im);im.onload=renderBoard;im.onerror=()=>{if(im.crossOrigin){const im2=new Image();imageCache.set(src,im2);im2.onload=renderBoard;im2.src=src}};if(!src.startsWith('data:'))im.crossOrigin='anonymous';im.src=src;return im}
function pxPoint(p){const r=size();return{x:p.x*r.w,y:p.y*r.h}}
function objBBox(o){const r=size();if(o.type==='emoji'){const w=o.size||44;return{x:o.x*r.w-w/2,y:o.y*r.h-w/2,w,h:w}}if(o.type==='image')return{x:o.x*r.w,y:o.y*r.h,w:o.w*r.w,h:o.h*r.h};if(o.type==='line')return{x:Math.min(o.x1,o.x2)*r.w,y:Math.min(o.y1,o.y2)*r.h,w:Math.max(8,Math.abs(o.x2-o.x1)*r.w),h:Math.max(8,Math.abs(o.y2-o.y1)*r.h)};const pts=o.points||[];if(!pts.length)return{x:0,y:0,w:0,h:0};const xs=pts.map(p=>p.x*r.w),ys=pts.map(p=>p.y*r.h),pad=(o.width||3)+5;return{x:Math.min(...xs)-pad,y:Math.min(...ys)-pad,w:Math.max(...xs)-Math.min(...xs)+pad*2,h:Math.max(...ys)-Math.min(...ys)+pad*2}}
function unionBBox(ids=selected){const boxes=ids.map(id=>boardState().objects.find(o=>o.id===id)).filter(Boolean).map(objBBox);if(!boxes.length)return null;const x=Math.min(...boxes.map(b=>b.x)),y=Math.min(...boxes.map(b=>b.y)),x2=Math.max(...boxes.map(b=>b.x+b.w)),y2=Math.max(...boxes.map(b=>b.y+b.h));return{x,y,w:x2-x,h:y2-y}}
function lineSegDist(px,py,x1,y1,x2,y2){const A=px-x1,B=py-y1,C=x2-x1,D=y2-y1,d=C*C+D*D;let t=d?Math.max(0,Math.min(1,(A*C+B*D)/d)):0;const x=x1+t*C,y=y1+t*D;return Math.hypot(px-x,py-y)}
function hitObject(p,radius=15){const s=size(),px=p.x*s.w,py=p.y*s.h,obs=[...boardState().objects].reverse();for(const o of obs){if(o.type==='stroke'){const pts=o.points||[];for(let i=1;i<pts.length;i++){const a=pxPoint(pts[i-1]),b=pxPoint(pts[i]);if(lineSegDist(px,py,a.x,a.y,b.x,b.y)<radius+(o.width||3)/2)return o}}else if(o.type==='line'){const a={x:o.x1*s.w,y:o.y1*s.h},b={x:o.x2*s.w,y:o.y2*s.h};if(lineSegDist(px,py,a.x,a.y,b.x,b.y)<radius)return o}else{const b=objBBox(o);if(px>=b.x-radius&&px<=b.x+b.w+radius&&py>=b.y-radius&&py<=b.y+b.h+radius)return o}}return null}
function drawArrowHead(x1,y1,x2,y2,double=false){const ang=Math.atan2(y2-y1,x2-x1),L=14;ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-L*Math.cos(ang-.55),y2-L*Math.sin(ang-.55));ctx.moveTo(x2,y2);ctx.lineTo(x2-L*Math.cos(ang+.55),y2-L*Math.sin(ang+.55));ctx.stroke();if(double){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x1+L*Math.cos(ang-.55),y1+L*Math.sin(ang-.55));ctx.moveTo(x1,y1);ctx.lineTo(x1+L*Math.cos(ang+.55),y1+L*Math.sin(ang+.55));ctx.stroke()}}
function drawObj(o){const s=size();ctx.save();ctx.lineCap='round';ctx.lineJoin='round';if(o.type==='stroke'){ctx.strokeStyle=o.color||'#111';ctx.lineWidth=o.width||3;if(o.style==='high'){ctx.globalAlpha=.33;ctx.globalCompositeOperation='multiply'}const pts=o.points||[];if(pts.length){ctx.beginPath();ctx.moveTo(pts[0].x*s.w,pts[0].y*s.h);for(let i=1;i<pts.length;i++)ctx.lineTo(pts[i].x*s.w,pts[i].y*s.h);ctx.stroke()}}else if(o.type==='line'){const x1=o.x1*s.w,y1=o.y1*s.h,x2=o.x2*s.w,y2=o.y2*s.h;ctx.strokeStyle=o.color||'#111';ctx.lineWidth=o.width||3;if(o.style==='dashed')ctx.setLineDash([10,8]);ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();if(o.style==='arrow'||o.style==='double')drawArrowHead(x1,y1,x2,y2,o.style==='double');if(o.style==='ticks'){const n=5,dx=(x2-x1)/n,dy=(y2-y1)/n,ang=Math.atan2(y2-y1,x2-x1)+Math.PI/2;for(let i=1;i<n;i++){const x=x1+dx*i,y=y1+dy*i;ctx.beginPath();ctx.moveTo(x-5*Math.cos(ang),y-5*Math.sin(ang));ctx.lineTo(x+5*Math.cos(ang),y+5*Math.sin(ang));ctx.stroke()}}}else if(o.type==='emoji'){ctx.font=`${o.size||44}px system-ui,Apple Color Emoji,Segoe UI Emoji`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.char,o.x*s.w,o.y*s.h)}else if(o.type==='image'){const im=loadImg(o.src);if(im.complete&&im.naturalWidth)try{ctx.drawImage(im,o.x*s.w,o.y*s.h,o.w*s.w,o.h*s.h)}catch{}}ctx.restore()}
function renderBoard(){const s=size();ctx.clearRect(0,0,s.w,s.h);boardState().objects.forEach(drawObj);if(drawing)drawObj(drawing);if(lasso){ctx.save();ctx.strokeStyle='#777';ctx.setLineDash([5,5]);ctx.strokeRect(lasso.x,lasso.y,lasso.w,lasso.h);ctx.restore()}if(selected.length){const b=unionBBox();if(b){ctx.save();ctx.strokeStyle='#2563eb';ctx.lineWidth=1.5;ctx.setLineDash([5,4]);ctx.strokeRect(b.x-4,b.y-4,b.w+8,b.h+8);ctx.setLineDash([]);ctx.fillStyle='#fff';ctx.strokeStyle='#2563eb';for(const [x,y] of [[b.x-4,b.y-4],[b.x+b.w+4,b.y+b.h+4]]){ctx.beginPath();ctx.rect(x-5,y-5,10,10);ctx.fill();ctx.stroke()}ctx.restore()}}}
function syncSelectionBar(){$('#selectionBar').classList.toggle('show',selected.length>0)}
function translateObj(o,dx,dy){if(o.type==='stroke'){o.points.forEach(p=>{p.x+=dx;p.y+=dy})}else if(o.type==='line'){o.x1+=dx;o.x2+=dx;o.y1+=dy;o.y2+=dy}else{o.x+=dx;o.y+=dy}}
function scaleObj(o,cx,cy,k){const s=size();if(o.type==='stroke'){o.points.forEach(p=>{const x=p.x*s.w,y=p.y*s.h;p.x=(cx+(x-cx)*k)/s.w;p.y=(cy+(y-cy)*k)/s.h})}else if(o.type==='line'){for(const key of ['x1','x2'])o[key]=(cx+(o[key]*s.w-cx)*k)/s.w;for(const key of ['y1','y2'])o[key]=(cy+(o[key]*s.h-cy)*k)/s.h}else if(o.type==='emoji'){const x=o.x*s.w,y=o.y*s.h;o.x=(cx+(x-cx)*k)/s.w;o.y=(cy+(y-cy)*k)/s.h;o.size=Math.max(16,(o.size||44)*k)}else{const x=o.x*s.w,y=o.y*s.h;o.x=(cx+(x-cx)*k)/s.w;o.y=(cy+(y-cy)*k)/s.h;o.w*=k;o.h*=k}}
function eraseAt(p,seen){const hit=hitObject(p,24);if(!hit||seen.has(hit.id))return;seen.add(hit.id);const a=boardState().objects,i=a.findIndex(o=>o.id===hit.id);if(i>=0)a.splice(i,1);selected=selected.filter(id=>id!==hit.id);renderBoard();syncSelectionBar()}
function pointerAllowed(e){if(e.pointerType==='pen'){penSeen=true;return true}if(e.pointerType==='touch'&&penSeen&&['pen','high','line'].includes(boardTool))return false;return true}
C.addEventListener('pointerdown',e=>{if(!pointerAllowed(e))return;e.preventDefault();try{C.setPointerCapture(e.pointerId)}catch{}const p=pnorm(e),s=size(),pp={x:p.x*s.w,y:p.y*s.h};if(boardTool==='emojiPlace'){beginHistory();const o={id:uid(),type:'emoji',x:p.x,y:p.y,size:46,char:currentEmoji};boardState().objects.push(o);selected=[o.id];boardTool='select';setActiveTool('select');save();renderBoard();syncSelectionBar();return}if(boardTool==='eraser'){beginHistory();gesture={mode:'erase',id:e.pointerId,seen:new Set()};eraseAt(p,gesture.seen);return}if(boardTool==='select'){const b=unionBBox();if(b&&selected.length&&Math.hypot(pp.x-(b.x+b.w+4),pp.y-(b.y+b.h+4))<18){gesture={mode:'resize',id:e.pointerId,anchor:{x:b.x-4,y:b.y-4},start:pp,base:JSON.parse(snap()),hist:false};return}const hit=hitObject(p,12);if(hit){if(!selected.includes(hit.id))selected=[hit.id];gesture={mode:'move',id:e.pointerId,last:p,hist:false};syncSelectionBar();renderBoard();return}selected=[];syncSelectionBar();gesture={mode:'lasso',id:e.pointerId,start:pp};lasso={x:pp.x,y:pp.y,w:0,h:0};renderBoard();return}beginHistory();if(boardTool==='line'){if(lineStyle==='curve')drawing={id:uid(),type:'stroke',style:'pen',color:boardColor,width:boardWidth,points:[p]};else drawing={id:uid(),type:'line',style:lineStyle,color:boardColor,width:boardWidth,x1:p.x,y1:p.y,x2:p.x,y2:p.y}}else drawing={id:uid(),type:'stroke',style:boardTool==='high'?'high':'pen',color:boardTool==='high'?'#f0ca32':boardColor,width:boardTool==='high'?Math.max(12,boardWidth*5):boardWidth,points:[p]};renderBoard()},{passive:false});
C.addEventListener('pointermove',e=>{if(!gesture&&!drawing)return;if(!pointerAllowed(e))return;e.preventDefault();const p=pnorm(e),s=size(),pp={x:p.x*s.w,y:p.y*s.h};if(gesture?.mode==='erase'){eraseAt(p,gesture.seen);return}if(gesture?.mode==='move'){if(!gesture.hist){beginHistory();gesture.hist=true}const dx=p.x-gesture.last.x,dy=p.y-gesture.last.y;boardState().objects.filter(o=>selected.includes(o.id)).forEach(o=>translateObj(o,dx,dy));gesture.last=p;renderBoard();return}if(gesture?.mode==='resize'){const a=gesture.anchor,sd=Math.max(20,Math.hypot(gesture.start.x-a.x,gesture.start.y-a.y)),nd=Math.max(20,Math.hypot(pp.x-a.x,pp.y-a.y)),k=nd/sd;if(!gesture.hist){beginHistory();gesture.hist=true}boardState().objects=JSON.parse(JSON.stringify(gesture.base));boardState().objects.filter(o=>selected.includes(o.id)).forEach(o=>scaleObj(o,a.x,a.y,k));renderBoard();return}if(gesture?.mode==='lasso'){const a=gesture.start;lasso={x:Math.min(a.x,pp.x),y:Math.min(a.y,pp.y),w:Math.abs(pp.x-a.x),h:Math.abs(pp.y-a.y)};renderBoard();return}if(drawing){if(drawing.type==='line'){drawing.x2=p.x;drawing.y2=p.y}else{const evs=e.getCoalescedEvents?e.getCoalescedEvents():[e];evs.forEach(x=>drawing.points.push(pnorm(x)))}renderBoard()}},{passive:false});
function finishPointer(e){if(gesture){if(gesture.mode==='lasso'&&lasso){selected=boardState().objects.filter(o=>{const b=objBBox(o),cx=b.x+b.w/2,cy=b.y+b.h/2;return cx>=lasso.x&&cx<=lasso.x+lasso.w&&cy>=lasso.y&&cy<=lasso.y+lasso.h}).map(o=>o.id);lasso=null;syncSelectionBar();renderBoard()}if(['move','resize','erase'].includes(gesture.mode)){save();syncSelectionBar();renderBoard()}gesture=null}if(drawing){boardState().objects.push(drawing);drawing=null;save();renderBoard()}}
C.addEventListener('pointerup',finishPointer,{passive:false});C.addEventListener('pointercancel',finishPointer,{passive:false});
function setActiveTool(t){boardTool=t;$$('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));$('#lineBtn').classList.toggle('active',t==='line')}
$$('.tool').forEach(b=>b.onclick=()=>{closePopovers();setActiveTool(b.dataset.tool)});
function closePopovers(except){$$('.popover').forEach(p=>{if(p!==except)p.classList.remove('open')})}
function togglePopover(p){const was=p.classList.contains('open');closePopovers();p.classList.toggle('open',!was)}
const COLORS=['#111111','#5f6360','#c93434','#e67e22','#e4b51e','#3f9b5f','#4aa7c0','#2757d8','#7a4ad8','#d34d92','#ffffff'];
$('#colorPopover').innerHTML=COLORS.map(c=>`<button class="swatch ${c===boardColor?'active':''}" data-c="${c}" style="background:${c}" aria-label="${c}"></button>`).join('');$('#colorBtn').onclick=()=>togglePopover($('#colorPopover'));$$('.swatch').forEach(b=>b.onclick=()=>{boardColor=b.dataset.c;$('#colorWell').style.background=boardColor;$$('.swatch').forEach(x=>x.classList.toggle('active',x===b));closePopovers()});
const WIDTHS=[1.5,3,6,12];$('#widthPopover').innerHTML=WIDTHS.map(w=>`<button class="widthChoice" data-w="${w}"><i style="--w:${w}px"></i></button>`).join('');$('#widthBtn').onclick=()=>togglePopover($('#widthPopover'));$$('.widthChoice').forEach(b=>b.onclick=()=>{boardWidth=+b.dataset.w;$('.widthSample').style.borderTopWidth=Math.max(1,Math.min(7,boardWidth))+'px';closePopovers()});
const lineOptions=[['line','<svg viewBox="0 0 24 24"><path d="M4 20L20 4"/></svg>'],['arrow','<svg viewBox="0 0 24 24"><path d="M4 20L19 5M12 5h7v7"/></svg>'],['double','<svg viewBox="0 0 24 24"><path d="M5 19L19 5M5 12v7h7M12 5h7v7"/></svg>'],['dashed','<svg viewBox="0 0 24 24"><path stroke-dasharray="4 3" d="M4 20L20 4"/></svg>'],['ticks','<svg viewBox="0 0 24 24"><path d="M4 20L20 4M8 18l-2-2M12 14l-2-2M16 10l-2-2"/></svg>'],['curve','<svg viewBox="0 0 24 24"><path d="M4 18c4-12 12 4 16-10"/></svg>']];$('#linePopover').innerHTML=lineOptions.map(([v,svg])=>`<button class="lineChoice" data-line="${v}">${svg}</button>`).join('');$('#lineBtn').onclick=()=>togglePopover($('#linePopover'));$$('.lineChoice').forEach(b=>b.onclick=()=>{lineStyle=b.dataset.line;setActiveTool('line');closePopovers()});
const ECATS={Recientes:['💡','🧠','⚠️','✅','❌','❓','🔁','🔗','➡️','⬅️','↔️','⭐','📌','💬'],Símbolos:['✅','❌','⚠️','❓','❗','⭕','🔴','🟢','🟡','🔵','⬛','⬜','➕','➖','✖️','➗','♾️','💯','🔗','🔒','🔓','✔️','☑️'],Flechas:['➡️','⬅️','⬆️','⬇️','↔️','↕️','↗️','↘️','↙️','↖️','🔁','🔄','⤴️','⤵️','🔀','🔃'],Ideas:['🧠','💡','👁️','💬','🗣️','👂','📌','🎯','🧩','🔍','📚','📝','🧪','⚙️','🌐','🕸️'],Personas:['👤','👥','🧑','👩','👨','🧒','👵','👴','🤝','🙋','🤔','🫂','👉','👈','☝️','👇','👍','👎'],Objetos:['📱','💻','🖥️','⌨️','📷','🖼️','📖','📕','📒','📎','✂️','🔑','🔔','⏱️','📍','🧭','🪜','🪞'],Naturaleza:['🌱','🌿','🌳','🌎','🌍','🌞','🌙','☁️','🔥','💧','🌊','🧬','🐕','🐈','🐦','🐝']};
function renderEmojiPicker(cat='Recientes',filter=''){const pop=$('#emojiPopover');pop.innerHTML=`<input class="emojiSearch" id="emojiSearch" placeholder="Buscar o escribir un emoji"/><div class="emojiCats">${Object.keys(ECATS).map(c=>`<button data-cat="${c}">${c}</button>`).join('')}</div><div class="emojiGrid" id="emojiGrid"></div>`;const all=filter?[...new Set(Object.values(ECATS).flat())]:ECATS[cat];$('#emojiGrid').innerHTML=all.map(e=>`<button data-e="${e}">${e}</button>`).join('');$$('.emojiCats button').forEach(b=>b.onclick=()=>renderEmojiPicker(b.dataset.cat));$$('#emojiGrid button').forEach(b=>b.onclick=()=>{currentEmoji=b.dataset.e;boardTool='emojiPlace';closePopovers()});$('#emojiSearch').oninput=e=>{const v=e.target.value.trim();if(v&&/[\p{Extended_Pictographic}\p{Emoji_Presentation}]/u.test(v)){currentEmoji=[...v][0];boardTool='emojiPlace'}else renderEmojiPicker(cat,v)};}
renderEmojiPicker();$('#emojiBtn').onclick=()=>togglePopover($('#emojiPopover'));
function addImage(src){beginHistory();const o={id:uid(),type:'image',src,x:.22,y:.22,w:.42,h:.3};boardState().objects.push(o);selected=[o.id];save();renderBoard();syncSelectionBar();setActiveTool('select');closePopovers()}
function fileToImage(file){if(!file||!file.type.startsWith('image/'))return;const rd=new FileReader();rd.onload=()=>addImage(rd.result);rd.readAsDataURL(file)}$('#imageBtn').onclick=()=>$('#imageInput').click();$('#imageInput').onchange=e=>{fileToImage(e.target.files[0]);e.target.value=''};wrap.addEventListener('dragover',e=>{e.preventDefault()});wrap.addEventListener('drop',e=>{e.preventDefault();fileToImage([...e.dataTransfer.files].find(f=>f.type.startsWith('image/')))});window.addEventListener('paste',e=>{if(!B.classList.contains('open'))return;const f=[...e.clipboardData.files].find(x=>x.type.startsWith('image/'));if(f)fileToImage(f)});
async function pinterestResults(keyword){const data={options:{query:keyword,scope:'pins',rs:'typed'},context:{}};const source='/search/pins/?q='+encodeURIComponent(keyword);const url='https://www.pinterest.com/resource/BaseSearchResource/get/?source_url='+encodeURIComponent(source)+'&data='+encodeURIComponent(JSON.stringify(data))+'&_='+Date.now();const r=await fetch(url,{headers:{'x-pinterest-pws-handler':'www/search/[scope].js'}});if(!r.ok)throw Error('Pinterest '+r.status);const j=await r.json();const arr=j?.resource_response?.data?.results||[];return arr.map(x=>({thumb:x?.images?.['236x']?.url||x?.images?.orig?.url,src:x?.images?.orig?.url||x?.images?.['736x']?.url})).filter(x=>x.thumb&&x.src).slice(0,3)}
function pinFallback(row,key){row.innerHTML=`<div class="pinImages">${[1,2,3].map(()=>`<button class="pinCard pinSearch"><span class="pinFallback">Pinterest ↗</span></button>`).join('')}</div><div class="pinStatus">No pude traer miniaturas aquí. Tocá para abrir esa búsqueda.</div>`;$$('.pinSearch',row).forEach(b=>b.onclick=()=>window.open('https://www.pinterest.com/search/pins/?q='+encodeURIComponent(key),'_blank','noopener'))}
async function loadPinRow(row,key){row.innerHTML='<div class="pinStatus">cargando…</div>';try{const imgs=await pinterestResults(key);if(!imgs.length)throw Error('vacío');row.innerHTML=`<div class="pinImages">${imgs.map((x,i)=>`<button class="pinCard" data-i="${i}"><img src="${x.thumb}" alt=""/></button>`).join('')}</div>`;$$('.pinCard',row).forEach(b=>b.onclick=()=>addImage(imgs[+b.dataset.i].src))}catch{pinFallback(row,key)}}
function openPinterest(){const pop=$('#pinPopover'),keys=DATA[unit].visual;pop.innerHTML=`<div class="pinTitle"><strong>Pinterest · U${unit+1}</strong><span>3 por búsqueda</span></div>${keys.map((k,i)=>`<div class="pinRow"><div class="pinRowLabel">${k}</div><div class="pinRowBody" data-row="${i}"></div></div>`).join('')}`;togglePopover(pop);keys.forEach((k,i)=>loadPinRow($(`[data-row="${i}"]`,pop),k))}$('#pinBtn').onclick=openPinterest;
$('#smallerSel').onclick=()=>scaleSelection(.9);$('#biggerSel').onclick=()=>scaleSelection(1.12);function scaleSelection(k){if(!selected.length)return;const b=unionBBox();beginHistory();boardState().objects.filter(o=>selected.includes(o.id)).forEach(o=>scaleObj(o,b.x+b.w/2,b.y+b.h/2,k));save();renderBoard()}
$('#deleteSel').onclick=()=>{if(!selected.length)return;beginHistory();boardState().objects=boardState().objects.filter(o=>!selected.includes(o.id));selected=[];save();renderBoard();syncSelectionBar()};$('#duplicateSel').onclick=()=>{if(!selected.length)return;beginHistory();const clones=boardState().objects.filter(o=>selected.includes(o.id)).map(o=>{const c=JSON.parse(JSON.stringify(o));c.id=uid();translateObj(c,.03,.03);return c});boardState().objects.push(...clones);selected=clones.map(o=>o.id);save();renderBoard();syncSelectionBar()};
$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;
$('#boardBtn').onclick=()=>{B.classList.add('open');B.setAttribute('aria-hidden','false');B.classList.toggle('hideTheory',innerWidth<700);const x=DATA[unit];$('#boardTheory').innerHTML=`<h2>${x.t}</h2><p>${x.s}</p><p>${x.d.join('</p><p>')}</p>`;selected=[];setActiveTool('select');closePopovers();setTimeout(resizeCanvas,30)};$('#closeBoard').onclick=()=>{B.classList.remove('open');B.setAttribute('aria-hidden','true');save()};$('#theoryBtn').onclick=()=>B.classList.toggle('hideTheory');
renderHome();
})();