/* Prometeo Calendar v1 — shared runtime + independent configuration. */
(function(global){
  'use strict';
  const VERSION=1;
  const DEFAULTS=Object.freeze({weekStart:1,locale:'es-AR',mode:'WEEK',showWeekNumbers:false,compact:false});
  const MODES=['WEEK','MONTH','DAY'];
  const pad=n=>String(n).padStart(2,'0');
  const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  const cloneDate=d=>new Date(d.getFullYear(),d.getMonth(),d.getDate());
  const addDays=(d,n)=>{const x=cloneDate(d);x.setDate(x.getDate()+n);return x};
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const startOfWeek=(d,weekStart)=>{const x=cloneDate(d),delta=(x.getDay()-weekStart+7)%7;x.setDate(x.getDate()-delta);return x};
  const icon={left:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 5l-7 7 7 7"/></svg>`,right:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 5l7 7-7 7"/></svg>`,plus:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>`};
  const dayNames=(locale,weekStart)=>{const base=new Date(2026,7,23);return Array.from({length:7},(_,i)=>new Intl.DateTimeFormat(locale,{weekday:'short'}).format(addDays(base,(weekStart+i)%7))).map(x=>x.replace('.',''))};
  function normalizeEvents(events=[]){return events.map((e,i)=>({id:e.id||`event-${i}`,date:e.date,time:e.time||'',title:e.title||'Sin título',meta:e.meta||'',tone:e.tone||'default'})).filter(e=>/^\d{4}-\d{2}-\d{2}$/.test(e.date))}
  function resolveConfig(opts={}){const c={...DEFAULTS};Object.keys(DEFAULTS).forEach(k=>{if(Object.prototype.hasOwnProperty.call(opts,k))c[k]=opts[k]});c.weekStart=Number(c.weekStart)===0?0:1;c.mode=MODES.includes(c.mode)?c.mode:'WEEK';return c}
  function mount(host,options={}){
    if(!host)throw new Error('PrometeoCalendar.mount host required');
    let config=resolveConfig(options),cursor=options.cursor?new Date(options.cursor+'T12:00:00'):new Date(),events=normalizeEvents(options.events),selected=options.selectedDate||iso(cursor);
    const provenance={};Object.keys(DEFAULTS).forEach(k=>provenance[k]=Object.prototype.hasOwnProperty.call(options,k)?'override':'default');
    host.classList.add('pc-root');host.dataset.calendarVersion=String(VERSION);
    const eventMap=()=>{const m=new Map();events.forEach(e=>{if(!m.has(e.date))m.set(e.date,[]);m.get(e.date).push(e)});return m};
    function headerLabel(){if(config.mode==='DAY')return new Intl.DateTimeFormat(config.locale,{weekday:'long',day:'numeric',month:'long'}).format(cursor);if(config.mode==='MONTH')return new Intl.DateTimeFormat(config.locale,{month:'long',year:'numeric'}).format(cursor);const start=startOfWeek(cursor,config.weekStart),end=addDays(start,6),f=new Intl.DateTimeFormat(config.locale,{day:'numeric',month:'short'});return `${f.format(start)} — ${f.format(end)}`}
    function renderWeek(){const start=startOfWeek(cursor,config.weekStart),names=dayNames(config.locale,config.weekStart),map=eventMap();let html=`<div class="pc-week pc-week-${config.compact?'compact':'normal'}"><div class="pc-week-head"><span></span>`;for(let i=0;i<7;i++){const d=addDays(start,i),key=iso(d),isToday=key===iso(new Date()),isSel=key===selected;html+=`<button class="pc-day-head${isToday?' is-today':''}${isSel?' is-selected':''}" data-date="${key}" type="button"><span>${esc(names[i])}</span><b>${d.getDate()}</b></button>`}html+='</div><div class="pc-week-body"><div class="pc-time-rail"><span>08</span><span>12</span><span>16</span><span>20</span></div>';for(let i=0;i<7;i++){const d=addDays(start,i),key=iso(d),dayEvents=map.get(key)||[];html+=`<div class="pc-day-column" data-date="${key}">`;dayEvents.forEach((e,idx)=>{const top=Math.min(82,10+idx*23);html+=`<button class="pc-event tone-${esc(e.tone)}" style="--event-top:${top}%" data-event-id="${esc(e.id)}" type="button"><span>${esc(e.time)}</span><b>${esc(e.title)}</b></button>`});html+='</div>'}return html+'</div></div>'}
    function renderMonth(){const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),map=eventMap(),gridStart=startOfWeek(first,config.weekStart),names=dayNames(config.locale,config.weekStart);let html=`<div class="pc-month"><div class="pc-month-head">${names.map(n=>`<span>${esc(n)}</span>`).join('')}</div><div class="pc-month-grid">`;for(let i=0;i<42;i++){const d=addDays(gridStart,i),key=iso(d),outside=d.getMonth()!==cursor.getMonth(),ev=map.get(key)||[];html+=`<button class="pc-month-day${outside?' is-outside':''}${key===selected?' is-selected':''}${key===iso(new Date())?' is-today':''}" data-date="${key}" type="button"><b>${d.getDate()}</b>${ev.length?`<span class="pc-dots">${ev.slice(0,3).map(()=>'<i></i>').join('')}</span>`:''}</button>`}return html+'</div></div>'}
    function renderDay(){const key=iso(cursor),ev=(eventMap().get(key)||[]);return `<div class="pc-day-view"><div class="pc-day-date">${new Intl.DateTimeFormat(config.locale,{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(cursor)}</div><div class="pc-day-events">${ev.length?ev.map(e=>`<button class="pc-day-event tone-${esc(e.tone)}" data-event-id="${esc(e.id)}" type="button"><span>${esc(e.time||'—')}</span><div><b>${esc(e.title)}</b>${e.meta?`<small>${esc(e.meta)}</small>`:''}</div></button>`).join(''):'<p class="pc-empty">No hay eventos. Seleccioná “Nuevo” para crear uno.</p>'}</div></div>`}
    function render(){host.innerHTML=`<div class="pc-shell"><header class="pc-head"><div><span class="pc-kicker">agenda</span><h3>${esc(headerLabel())}</h3></div><div class="pc-head-actions"><button class="pc-icon-btn" data-action="prev" type="button" aria-label="Anterior">${icon.left}</button><button class="pc-today-btn" data-action="today" type="button">Hoy</button><button class="pc-icon-btn" data-action="next" type="button" aria-label="Siguiente">${icon.right}</button><button class="pc-new-btn" data-action="new" type="button">${icon.plus}<span>Nuevo</span></button></div></header><nav class="pc-modes" aria-label="Vista de calendario">${MODES.map(m=>`<button type="button" data-mode="${m}" class="${config.mode===m?'is-active':''}">${m==='WEEK'?'Semana':m==='MONTH'?'Mes':'Día'}</button>`).join('')}</nav><div class="pc-stage">${config.mode==='WEEK'?renderWeek():config.mode==='MONTH'?renderMonth():renderDay()}</div></div>`;host.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;if(a==='prev')cursor=config.mode==='MONTH'?new Date(cursor.getFullYear(),cursor.getMonth()-1,1):addDays(cursor,config.mode==='WEEK'?-7:-1);if(a==='next')cursor=config.mode==='MONTH'?new Date(cursor.getFullYear(),cursor.getMonth()+1,1):addDays(cursor,config.mode==='WEEK'?7:1);if(a==='today'){cursor=new Date();selected=iso(cursor)}if(a==='new')options.onCreate?.({date:selected||iso(cursor),mode:config.mode});render();options.onChange?.(getState())}));host.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{config.mode=b.dataset.mode;render();options.onChange?.(getState())}));host.querySelectorAll('[data-date]').forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.date;cursor=new Date(selected+'T12:00:00');options.onDayOpen?.({date:selected});if(config.mode==='MONTH'&&options.monthClickOpensDay!==false)config.mode='DAY';render();options.onChange?.(getState())}));host.querySelectorAll('[data-event-id]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const event=events.find(x=>x.id===b.dataset.eventId);options.onEventOpen?.(event)}))}
    function getState(){return {version:VERSION,mode:config.mode,cursor:iso(cursor),selectedDate:selected,config:{...config},provenance:{...provenance},events:[...events]}}
    function setConfig(next={}){Object.keys(next).forEach(k=>{if(Object.prototype.hasOwnProperty.call(DEFAULTS,k)){config[k]=next[k];provenance[k]='override'}});config=resolveConfig(config);render();return getState()}
    function setEvents(next=[]){events=normalizeEvents(next);render();return getState()}
    function setMode(mode){if(MODES.includes(mode)){config.mode=mode;render()}return getState()}
    function destroy(){host.innerHTML='';host.classList.remove('pc-root')}
    render();return Object.freeze({version:VERSION,getState,setConfig,setEvents,setMode,destroy});
  }
  global.PrometeoCalendar=Object.freeze({version:VERSION,defaults:DEFAULTS,modes:MODES,mount});
})(window);