(function(g){
'use strict';
const TAU=Math.PI*2;
const P={void:'#050605',ink:'#d8c7a9',outline:'#090a09',outlineHi:'#3a352d',glass:'#92aaa4',glassEdge:'#d3ddd6',ember:'#c95f2d',emberHi:'#ffc36e',cyan:'#5caaa3',cyanHi:'#b8fff1',acid:'#87984b',sand:'#91775a'};
const SOURCES={
 mildew:{id:'wall_green_mildew',url:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Mold_spores.jpg?width=900',page:'https://commons.wikimedia.org/wiki/File:Mold_spores.jpg',license:'CC0',fallback:'#36463b'},
 rust:{id:'metal_rust_photo',url:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rust_on_metal.jpg?width=960',page:'https://commons.wikimedia.org/wiki/File:Rust_on_metal.jpg',license:'Public domain',fallback:'#61412f'},
 steel:{id:'metal_scratched_cc0',url:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Dark_white_moderately_scratched_rusty_worn_seamless_metal_surface_texture.jpg?width=960',page:'https://commons.wikimedia.org/wiki/File:Dark_white_moderately_scratched_rusty_worn_seamless_metal_surface_texture.jpg',license:'CC0',fallback:'#666c67'},
 wood:{id:'wood_old_public_domain',url:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Old_wood_texture.jpg?width=960',page:'https://commons.wikimedia.org/wiki/File:Old_wood_texture.jpg',license:'Public domain',fallback:'#5c402d'}
};
const MATERIALS={
 wall_green_mildew:{asset:'mildew',base:'#314039',shade:'#101813',edge:'#647266',tint:'rgba(43,72,56,.18)'},
 stone:{asset:'mildew',base:'#3d4039',shade:'#161813',edge:'#717267',tint:'rgba(93,86,66,.18)'},
 metal:{asset:'steel',base:'#666c67',shade:'#202421',edge:'#b8c0b8',tint:'rgba(85,105,98,.12)'},
 rust:{asset:'rust',base:'#704730',shade:'#22130d',edge:'#b67548',tint:'rgba(123,55,24,.13)'},
 wood:{asset:'wood',base:'#5d412f',shade:'#24150f',edge:'#a17a58',tint:'rgba(83,43,24,.11)'},
 dark:{asset:'steel',base:'#1b1d1a',shade:'#080908',edge:'#4d504a',tint:'rgba(0,0,0,.48)'},
 glass:{base:P.glass,shade:'#263a35',edge:P.glassEdge}
};
const images={}; let loaded=0,failed=0;
const ready=Promise.all(Object.entries(SOURCES).map(([k,s])=>new Promise(resolve=>{
  const im=new Image(); im.crossOrigin='anonymous';
  im.onload=()=>{images[k]=im;loaded++;resolve(true)};
  im.onerror=()=>{failed++;resolve(false)};
  im.src=s.url;
}))).then(()=>({loaded,failed}));
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function col(v){return P[v]||v||P.ink}
function rgba(hex,a){if(!hex||hex[0]!=='#')return hex;let h=hex.slice(1);if(h.length===3)h=h.split('').map(x=>x+x).join('');const n=parseInt(h,16);return 'rgba('+(n>>16)+','+((n>>8)&255)+','+(n&255)+','+a+')'}
function poly(c,pts,close=true){c.beginPath();c.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)c.lineTo(pts[i].x,pts[i].y);if(close)c.closePath()}
function ellipse(c,x,y,rx,ry){c.beginPath();c.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,TAU)}
function mat(id){return MATERIALS[id]||MATERIALS.dark}
function shadow(c,x,y,rx,ry,a=.34){c.save();c.globalAlpha=a;c.fillStyle='#000';ellipse(c,x,y,rx,ry);c.fill();c.restore()}
function drawCover(c,img,x,y,w,h,zoom=1){const ar=w/h,iar=img.width/img.height;let sx=0,sy=0,sw=img.width,sh=img.height;if(iar>ar){sw=img.height*ar; sx=(img.width-sw)/2}else{sh=img.width/ar;sy=(img.height-sh)/2}if(zoom>1){const nw=sw/zoom,nh=sh/zoom;sx+=(sw-nw)/2;sy+=(sh-nh)/2;sw=nw;sh=nh}c.drawImage(img,sx,sy,sw,sh,x,y,w,h)}
function surface(c,id,x,y,w,h,opt={}){const m=mat(id),src=SOURCES[m.asset],img=images[m.asset];c.save();c.beginPath();c.rect(x,y,w,h);c.clip();c.fillStyle=m.base;c.fillRect(x,y,w,h);if(img){c.globalAlpha=opt.alpha==null?.93:opt.alpha;drawCover(c,img,x,y,w,h,opt.zoom||1.15);c.globalAlpha=1;c.fillStyle=opt.tint||m.tint||'rgba(0,0,0,0)';c.fillRect(x,y,w,h);if(opt.dark)c.fillStyle='rgba(0,0,0,'+opt.dark+')',c.fillRect(x,y,w,h)}else if(src){c.fillStyle='rgba(0,0,0,.16)';c.fillRect(x,y,w,h)}if(opt.vignette!==false){const g=c.createRadialGradient(x+w*.5,y+h*.45,1,x+w*.5,y+h*.45,Math.max(w,h)*.7);g.addColorStop(.35,'rgba(255,255,255,0)');g.addColorStop(1,'rgba(0,0,0,.32)');c.fillStyle=g;c.fillRect(x,y,w,h)}c.restore();c.strokeStyle=opt.edge||m.edge||P.outlineHi;c.lineWidth=opt.lineWidth||1.4;c.strokeRect(x+.5,y+.5,w-1,h-1)}
function decal(c,x,y,w,h,text='07'){c.save();c.fillStyle='rgba(220,204,170,.82)';c.fillRect(x,y,w,h);c.fillStyle='#16130f';c.font='900 '+Math.max(7,h*.52)+'px ui-monospace,monospace';c.textAlign='center';c.textBaseline='middle';c.fillText(text,x+w/2,y+h/2);c.globalAlpha=.25;c.fillStyle='#000';for(let i=0;i<5;i++)c.fillRect(x+(i*17)%w,y+(i*11)%h,3,1);c.restore()}
function block(c,p){const x=p.x||0,y=p.y||0,w=p.w||70,h=p.h||42,d=p.depth||12,id=p.material||'stone',m=mat(id);if(p.shadow!==false)shadow(c,x+w*.54,y+h+d+7,w*.62,7,.3);c.save();poly(c,[{x,y},{x:x+d,y:y-d},{x:x+w+d,y:y-d},{x:x+w,y}]);c.fillStyle=m.edge;c.fill();poly(c,[{x:x+w,y},{x:x+w+d,y:y-d},{x:x+w+d,y:y+h-d},{x:x+w,y:y+h}]);c.fillStyle=m.shade;c.fill();surface(c,id,x,y,w,h,{zoom:p.zoom||1.2,dark:p.dark||0});c.strokeStyle=P.outline;c.lineWidth=1.2;poly(c,[{x,y},{x:x+d,y:y-d},{x:x+w+d,y:y-d},{x:x+w,y}]);c.stroke();poly(c,[{x:x+w,y},{x:x+w+d,y:y-d},{x:x+w+d,y:y+h-d},{x:x+w,y:y+h}]);c.stroke();if(p.decal)decal(c,x+w*.08,y+h*.12,w*.22,h*.22,p.decal);c.restore()}
function wall(c,p){block(c,{...p,depth:p.depth==null?8:p.depth,material:p.material||'wall_green_mildew'});const x=p.x||0,y=p.y||0,w=p.w||100,h=p.h||60;c.save();c.strokeStyle='rgba(222,205,169,.18)';c.lineWidth=1;c.beginPath();c.moveTo(x+w*.07,y+h*.72);c.lineTo(x+w*.93,y+h*.72);c.stroke();if(p.panel){c.fillStyle='rgba(21,17,13,.78)';c.fillRect(x+w*.08,y+h*.72,w*.84,h*.18);for(let i=0;i<6;i++){c.fillStyle=i%2?'rgba(109,84,57,.26)':'rgba(36,28,22,.62)';c.fillRect(x+w*(.09+i*.14),y+h*.735,w*.11,h*.13)}}c.restore()}
function glassBox(c,p){const x=p.x||0,y=p.y||0,w=p.w||70,h=p.h||60,d=p.depth||9,edge=col(p.edge||'glassEdge');if(p.shadow!==false)shadow(c,x+w*.5,y+h+7,w*.55,7,.22);c.save();if(p.internals!==false){surface(c,p.innerMaterial||'rust',x+7,y+9,w-14,h-18,{zoom:1.4,dark:.28,vignette:false});for(let i=0;i<3;i++){c.strokeStyle=i===1?'rgba(255,176,87,.78)':'rgba(91,190,172,.58)';c.lineWidth=2;c.beginPath();c.moveTo(x+10,y+h*(.28+i*.2));c.bezierCurveTo(x+w*.33,y+h*(.1+i*.25),x+w*.63,y+h*(.5-i*.08),x+w-8,y+h*(.24+i*.21));c.stroke()}decal(c,x+w*.58,y+h*.14,w*.22,h*.16,'IN')}
  c.fillStyle=rgba(col(p.tint||'glass'),p.alpha==null?.12:p.alpha);c.fillRect(x,y,w,h);poly(c,[{x,y},{x:x+d,y:y-d},{x:x+w+d,y:y-d},{x:x+w,y}]);c.fillStyle=rgba(col(p.tint||'glass'),.18);c.fill();poly(c,[{x:x+w,y},{x:x+w+d,y:y-d},{x:x+w+d,y:y+h-d},{x:x+w,y:y+h}]);c.fillStyle=rgba(col(p.tint||'glass'),.08);c.fill();c.strokeStyle=edge;c.lineWidth=1.6;c.strokeRect(x+.5,y+.5,w-1,h-1);c.globalAlpha=.46;c.strokeStyle='#fff';c.beginPath();c.moveTo(x+w*.12,y+5);c.lineTo(x+w*.58,y+5);c.stroke();c.restore()}
function cylinder(c,p){const x=p.x||0,y=p.y||0,w=p.w||44,h=p.h||110,rx=w*.5,ry=p.ellipse||Math.max(4,w*.15),fill=clamp(p.fill==null?0:p.fill,0,1),fillCol=col(p.fillColor||'ember');if(p.shadow!==false)shadow(c,x,y+h+ry*.9,w*.72,ry*.8,.3);c.save();c.beginPath();c.rect(x-rx+3,y,w-6,h);c.clip();surface(c,p.material||'steel',x-rx+3,y,w-6,h,{zoom:2,dark:.46,vignette:false});if(fill>0){const fy=y+h*(1-fill),bh=h*fill;c.fillStyle=rgba(fillCol,.58);c.fillRect(x-rx+5,fy,w-10,bh);const g=c.createLinearGradient(x-rx,fy,x+rx,fy);g.addColorStop(0,'rgba(255,255,255,.08)');g.addColorStop(.45,rgba(fillCol,.72));g.addColorStop(1,'rgba(0,0,0,.16)');c.fillStyle=g;c.fillRect(x-rx+5,fy,w-10,bh);ellipse(c,x,fy,rx-5,Math.max(2,ry-2));c.fillStyle=rgba(fillCol,.82);c.fill()}c.restore();c.save();c.strokeStyle='rgba(211,221,214,.78)';c.lineWidth=1.6;c.beginPath();c.moveTo(x-rx,y);c.lineTo(x-rx,y+h);c.moveTo(x+rx,y);c.lineTo(x+rx,y+h);c.stroke();ellipse(c,x,y,rx,ry);c.stroke();ellipse(c,x,y+h,rx,ry);c.stroke();for(let i=1;i<8;i++){c.globalAlpha=.42;c.beginPath();c.moveTo(x-rx-1,y+h*i/8);c.lineTo(x+rx+1,y+h*i/8);c.stroke()}c.globalAlpha=1;decal(c,x-rx+5,y+12,w-10,13,String(Math.round(fill*100)).padStart(2,'0'));if(p.emissive){c.shadowColor=fillCol;c.shadowBlur=13;ellipse(c,x,y+h*(1-fill),rx-7,Math.max(1,ry-3));c.strokeStyle=rgba(col(p.fillHi||'emberHi'),.95);c.stroke();c.shadowBlur=0}c.restore()}
function platform(c,p){const x=p.x||0,y=p.y||0,rx=p.rx||42,ry=p.ry||13,h=p.h||8;if(p.shadow!==false)shadow(c,x,y+h+ry*.8,rx*1.15,ry*.72,.3);c.save();ellipse(c,x,y+h,rx,ry);c.fillStyle=mat(p.material||'metal').shade;c.fill();ellipse(c,x,y,rx,ry);c.clip();surface(c,p.material||'metal',x-rx,y-ry,rx*2,ry*2,{zoom:1.7,dark:.18,vignette:false});c.restore();c.save();ellipse(c,x,y,rx,ry);c.strokeStyle=P.outline;c.lineWidth=1.6;c.stroke();if(p.ring){ellipse(c,x,y,rx*.6,ry*.54);c.strokeStyle=rgba(col(p.ring),.9);c.lineWidth=2;c.stroke()}c.restore()}
function station(c,p){const x=p.x||0,y=p.y||0,w=p.w||110,h=p.h||55;platform(c,{x:x+w*.5,y:y+h+9,rx:w*.58,ry:13,h:7,material:p.material||'rust',ring:p.ring||'ember'});block(c,{x,y,w,h,depth:9,material:p.bodyMaterial||'rust',shadow:false,decal:p.decal||'S7'});glassBox(c,{x:x+w*.17,y:y+10,w:w*.66,h:h*.46,depth:4,innerMaterial:p.innerMaterial||'metal',shadow:false})}
function glow(c,p){const x=p.x||0,y=p.y||0,r=p.r||18,color=col(p.color||'cyan');const gr=c.createRadialGradient(x,y,0,x,y,r);gr.addColorStop(0,rgba(color,p.alpha==null?.55:p.alpha));gr.addColorStop(.35,rgba(color,.18));gr.addColorStop(1,rgba(color,0));c.fillStyle=gr;ellipse(c,x,y,r,r);c.fill()}
function token(c,p){const x=p.x||0,y=p.y||0,r=p.r||6,color=col(p.color||'emberHi'),pts=[];for(let i=0;i<6;i++){const a=-Math.PI/2+i*TAU/6;pts.push({x:x+Math.cos(a)*r,y:y+Math.sin(a)*r})}c.save();if(p.emissive){c.shadowColor=color;c.shadowBlur=8}poly(c,pts);c.fillStyle=color;c.fill();c.shadowBlur=0;c.strokeStyle=P.outline;c.stroke();c.restore()}
function particles(c,p,e){const n=Math.min(p.count||12,36),x=p.x||0,y=p.y||0,t=(e.now||0)*.001;for(let i=0;i<n;i++){const q=(t*.55+i/n)%1;c.globalAlpha=(1-q)*.75;c.fillStyle=col(p.color||'emberHi');c.fillRect(x+Math.sin(i*12.7)*p.spread*q,y-q*(p.rise||36),1+(i%2),1+(i%3===0))}c.globalAlpha=1}
function path(c,p){const pts=p.points||[];if(pts.length<2)return;c.save();c.lineCap='round';c.lineJoin='round';poly(c,pts,false);c.strokeStyle='rgba(0,0,0,.55)';c.lineWidth=(p.width||8)+5;c.stroke();poly(c,pts,false);c.strokeStyle=col(p.color||'sand');c.lineWidth=p.width||8;c.stroke();c.restore()}
function arrow(c,p){const a=p.from,b=p.to;if(!a||!b)return;path(c,{points:[a,b],width:p.width||3,color:p.color||'emberHi'});const ang=Math.atan2(b.y-a.y,b.x-a.x),r=p.head||9;poly(c,[{x:b.x,y:b.y},{x:b.x-Math.cos(ang-.55)*r,y:b.y-Math.sin(ang-.55)*r},{x:b.x-Math.cos(ang+.55)*r,y:b.y-Math.sin(ang+.55)*r}]);c.fillStyle=col(p.color||'emberHi');c.fill()}
function hologram(c,p,e){const x=p.x||0,y=p.y||0,w=p.w||60,h=p.h||70,color=col(p.color||'cyanHi');c.save();c.globalAlpha=p.alpha||.48;c.strokeStyle=color;c.setLineDash([3,5]);c.strokeRect(x,y,w,h);c.setLineDash([]);for(let i=0;i<4;i++){c.globalAlpha=.12;c.fillStyle=color;c.fillRect(x+3,y+((i/4+(e.now||0)*.0002)%1)*h,w-6,1)}c.restore()}
function drawPrimitive(c,p={},env={}){if(!c)return false;const e={now:env.now==null?performance.now():env.now};switch(String(p.type||'block').toLowerCase()){case'block':case'solid':block(c,p);break;case'wall':wall(c,p);break;case'glass-box':case'glassbox':glassBox(c,p);break;case'cylinder':case'progress-cylinder':cylinder(c,p);break;case'platform':case'node-platform':platform(c,p);break;case'station':station(c,p);break;case'glow':glow(c,p);break;case'token':case'output-token':token(c,p);break;case'particles':particles(c,p,e);break;case'path':path(c,p);break;case'arrow':arrow(c,p);break;case'hologram':hologram(c,p,e);break;case'shadow':shadow(c,p.x||0,p.y||0,p.rx||24,p.ry||8,p.alpha||.34);break;default:return false}return true}
g.COLISEO_LAB_MODULE={id:'materials',version:'2.0.0',tokens:{palette:P},sources:SOURCES,materials:MATERIALS,images,ready,get assetStatus(){return{loaded,failed,total:Object.keys(SOURCES).length}},drawPrimitive};
})(window);
