import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../',import.meta.url);
const read=p=>fs.readFileSync(new URL(p,root),'utf8');
const shell=read('shared/shell/v53-adapter/v1/v53-shell-adapter.js');
const bridge=read('lab/prometeo-v53-integrated-part1/bridge.js');
const wrapper=read('lab/prometeo-v53-integrated-part1/index.html');
const pk=read('shared/pagekit/host/v2/pagekit-host.js');
const persistence=read('shared/runtime/persistence/v1/persistence.js');
assert.match(shell,/PROMETEO_V53_COMPLETE_EXAMPLE_ATLAS_20260901/);
assert.match(shell,/usesExistingTerminal:true/);assert.match(shell,/usesExistingGrip:true/);assert.match(shell,/createsVisibleShell:false/);
assert.doesNotMatch(shell,/createElement\(['"](?:section|button|iframe)['"]\).*return-tooth/);
assert.match(shell,/prometeo\.v53-semantic-return\/v1/);assert.match(shell,/semanticFingerprint/);assert.match(shell,/history:/);
assert.doesNotMatch(shell,/scrollX|scrollY|clientX.*restore|clientY.*restore/);
assert.match(shell,/childList:true/);assert.doesNotMatch(shell,/attributeFilter:\s*\[['"]class/);
assert.match(wrapper,/\.\.\/\.\.\/navigator\//);assert.match(wrapper,/allow="fullscreen; clipboard-read; clipboard-write"/);assert.match(wrapper,/allowfullscreen/);
assert.match(bridge,/same origin/i);assert.doesNotMatch(bridge,/shared\/shell\/v1\/shell\.js/);
assert.match(pk,/v26/);assert.match(pk,/v37/);assert.match(pk,/persistent/i);assert.match(pk,/attach\(container\)/);assert.match(pk,/ensureTerminalLease/);assert.match(pk,/compact/);assert.match(pk,/presentation/);assert.match(pk,/fullscreen/);
assert.match(persistence,/PROMETEO_STALE_STATE_COMMIT/);assert.match(persistence,/readRecord/);assert.match(persistence,/SESSION_DIAGNOSTIC_ONLY_PART2_LEDGER_PENDING/);
console.log(JSON.stringify({ok:true,tests:['v53-shell-no-duplicate-ui','semantic-return-not-pixels','no-animation-attribute-observer','same-origin-v53-composition-harness','wrapper-delegates-pagekit-capabilities','pagekit-v26-v37-persistent-reparentable','commit-time-cas-present','generic-shell-not-imported']},null,2));