import assert from 'node:assert/strict';
import {json,jsonl,context,load} from './part2-test-helpers.mjs';
const c=context();load('shared/reincarnation/v1/reincarnate.js',c);load('shared/operator/v1/operator-view.js',c);
// Unit-test the reincarnation contract with a coherent snapshot derived from whatever durable frontier is current. End-to-end P3 later verifies the actual HEAD/DOT/PARENT files after final synchronization.
const currentGraph=json('state/CURRENT_GRAPH.json'),candidate=currentGraph.pointers.candidate_current,artifact=currentGraph.artifacts[candidate.artifact_id];
const head={schema:'prometeo.head/v1',namespace:'prometeo',artifact_id:candidate.artifact_id,source:artifact.source,receipt_id:candidate.receipt_id};
const dotState={schema:'prometeo.dot-state/v1',phase:currentGraph.active_workstream?.phase||'TEST',state:'READY',active_branch:currentGraph.active_workstream?.branch||'candidate',next_gate:'CURRENT_FRONTIER',last_receipt:currentGraph.last_durable_receipt};
const parent={schema:'prometeo.parent/v1',child:candidate.artifact_id,parent:currentGraph.pointers.runtime_base?.artifact_id||candidate.artifact_id,parent_source:currentGraph.artifacts[currentGraph.pointers.runtime_base?.artifact_id]?.source||artifact.source};
const args={bootstrap:json('reincarnation/BOOTSTRAP.json'),currentGraph,head,dotState,parent,pending:json('state/PENDING.json'),carry:json('state/CARRY.json'),watermarks:json('state/WATERMARKS.json'),catalog:json('catalog/CATALOG_MANIFEST.json'),lineage:json('lineage/LINEAGE_GRAPH.json'),capabilities:json('lineage/CAPABILITY_REGISTRY.json'),hotBook:json('context/books/HOT.json'),operatorContract:json('reincarnation/OPERATOR_CONTRACT.json'),ledgerReceipts:jsonl('receipts/ledger.jsonl')};
const wake=c.PrometeoReincarnate.wake(args);assert.equal(wake.ACTIVE_FRONTEND,'navigator-v53-visible');assert.equal(wake.PAGES.count,31);assert.ok(wake.RULES.some(x=>x.includes('EXISTS')));assert.equal(Object.isFrozen(wake.CURRENT),true);assert.equal(wake.CURRENT.candidate,candidate.artifact_id);assert.equal(wake.HOW_TO_CHANGE,args.operatorContract.HOW_TO_CHANGE);assert.equal(wake.HOW_TO_TEST,args.operatorContract.HOW_TO_TEST);assert.equal(wake.HOW_TO_RELEASE,args.operatorContract.HOW_TO_RELEASE);
assert.throws(()=>c.PrometeoReincarnate.wake({...args,carry:undefined}),e=>e.code==='PROMETEO_WAKE_CARRY');assert.throws(()=>c.PrometeoReincarnate.wake({...args,operatorContract:undefined}),e=>e.code==='PROMETEO_WAKE_OPERATOR');const badHead=structuredClone(args.head);badHead.artifact_id='forged';assert.throws(()=>c.PrometeoReincarnate.wake({...args,head:badHead}),e=>e.code==='PROMETEO_WAKE_HEAD_DRIFT');
const op=c.PrometeoOperatorView.project({currentGraph,pending:json('state/PENDING.json'),catalog:json('catalog/CATALOG_MANIFEST.json')});assert.deepEqual(Array.from(op.actions),['OPEN_PAGE','SEARCH','USE','REQUEST_CHANGE','CREATE','BACK']);assert.equal('lease_id' in op,false);assert.equal('receipt_hash' in op,false);console.log(JSON.stringify({ok:true,phases:['2.17','2.18'],frontend:wake.ACTIVE_FRONTEND}));
