import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../',import.meta.url);
const read=p=>fs.readFileSync(new URL(p,root),'utf8');
const shell=read('shared/shell/v53-adapter/v1/v53-shell-adapter.js');
const bridge=read('lab/prometeo-v53-integrated-part1/bridge.js');
const wrapper=read('lab/prometeo-v53-integrated-part1/index.html');
const pk=read('shared/pagekit/host/v2/pagekit-host.js');
assert.match(shell,/PROMETEO_V53_COMPLETE_EXAMPLE_ATLAS_20260901/);
assert.match(shell,/usesExistingTerminal:true/);
assert.match(shell,/usesExistingGrip:true/);
assert.match(shell,/createsVisibleShell:false/);
assert.doesNotMatch(shell,/createElement\(['"](?:section|button|iframe)['"]\).*return-tooth/);
assert.match(shell,/prometeo\.v53-semantic-return\/v1/);
assert.match(shell,/history:/);
assert.doesNotMatch(shell,/scrollX|scrollY|clientX.*restore|clientY.*restore/);
assert.match(wrapper,/\.\.\/\.\.\/navigator\//);
assert.match(bridge,/same origin/i);
assert.match(pk,/v26/);assert.match(pk,/v37/);assert.match(pk,/Persistent/i);
assert.match(pk,/compact/);assert.match(pk,/presentation/);assert.match(pk,/fullscreen/);
console.log(JSON.stringify({ok:true,tests:['v53-shell-no-duplicate-ui','semantic-return-not-pixels','same-origin-v53-wrapper','pagekit-v26-v37-persistent']},null,2));
