import assert from 'node:assert/strict';
import fs from 'node:fs';
import {spawnSync} from 'node:child_process';

const read=p=>JSON.parse(fs.readFileSync(new URL('../'+p,import.meta.url),'utf8'));
const current=read('state/CURRENT_GRAPH.json');
const dot=read('state/DOT_STATE.json');
const pending=read('state/PENDING.json');
const matrix=read('coordination/PART3_GATE_MATRIX.json');
const report=read('coordination/P3_01_BROWSER_CLOSURE.json');
const receipts=fs.readFileSync(new URL('../receipts/ledger.jsonl',import.meta.url),'utf8').trim().split(/\n+/).map(JSON.parse);
const receipt=receipts.at(-1);
assert.equal(receipt.id,'R-P3-01-BROWSER-0006');
assert.equal(current.revision,5);
assert.equal(current.last_durable_receipt,receipt.id);
assert.equal(dot.last_receipt,receipt.id);
assert.equal(current.active_workstream.phase,'PART3_P3_01_COMPLETE');
assert.equal(dot.phase,'PART3_P3_01_COMPLETE');
assert.equal(dot.next_gate,'P3-02_FRESH_AGENT_REINCARNATION');
assert.equal(current.pointers.candidate_current.receipt_id,'R-P2-AUDIT-0004');
assert.equal(current.pointers.served_current.receipt_id,'R-P2-BOOT-0001');
assert.equal(current.pointers.served_current.evidence_state,'INHERITED_PREEXISTING_NOT_PART2_BROWSER_REVERIFIED');
assert.equal(current.pointers.human_accepted_physics.receipt_id,'R-P2-BOOT-0001');
const p301=matrix.gates.find(g=>g.id==='P3-01');
const p302=matrix.gates.find(g=>g.id==='P3-02');
assert.equal(p301.status,'PASS');
assert.equal(p301.receipt_id,receipt.id);
assert.equal(p301.ci_run,33882820789);
assert.equal(p301.artifact_id,9940580289);
assert.equal(p302.status,'READY');
assert.deepEqual(matrix.gates.filter(g=>g.status==='READY').map(g=>g.id),['P3-02']);
assert.deepEqual(pending.items[0].dependencies,[receipt.id]);
assert.match(pending.items[0].next_action,/execute only P3-02/);
assert.equal(pending.items[0].source_frontier.p3_01_receipt_hash,receipt.hash);
assert.equal(report.status,'PASS');
assert.equal(report.receipt_hash,receipt.hash);
assert.equal(report.empirical.failed_local_resources,0);
assert.equal(report.empirical.page_errors,0);
assert.equal(report.empirical.console_errors,0);
assert.equal(report.truth_ceiling.human_accepted,false);
assert.equal(report.truth_ceiling.new_served_verification,false);
assert.equal(report.truth_ceiling.fresh_agent_reincarnation,false);
const run=spawnSync(process.execPath,['scripts/p3-00-rehydrate.mjs'],{encoding:'utf8'});
if(run.status!==0){process.stderr.write(run.stderr||'');process.exit(run.status||1)}
const wake=JSON.parse(run.stdout);
assert.equal(wake.ledger.ok,true);
assert.equal(wake.ledger.count,6);
assert.equal(wake.ledger.last_receipt_id,receipt.id);
assert.equal(wake.state_crosscheck.current_last_receipt,receipt.id);
assert.equal(wake.state_crosscheck.dot_last_receipt,receipt.id);
assert.equal(wake.wake.CURRENT.phase,'PART3_P3_01_COMPLETE');
console.log(JSON.stringify({ok:true,gate:'P3-01',receipt:receipt.id,revision:current.revision,next_gate:p302.id}));
