const docs=[
{id:'1VhggV-9Ivmiijqoex-xpIrUlQItoPPzz',file:'Mieles barrera Aportes de la ciencia cognitiva a la comprension de la cognicion 2024.pdf',title:'Aportes de la ciencia cognitiva a la comprensión de la cognición',author:'María Dilia Mieles Barrera',size:'251 KB',status:'texto extraíble',lead:'El surgimiento de la denominada Ciencia Cognitiva ocurrió en los años 50 del siglo XX en los Estados Unidos, a raíz de la crisis del conductismo que restaba importancia al funcionamiento de la mente en la explicación de la conducta de los seres humanos.',body:'Esta nueva perspectiva se traza el propósito de investigar los principios del procesamiento cognitivo, el pensamiento, el comportamiento inteligente y la representación del conocimiento desde la psicología experimental y con una perspectiva interdisciplinar.'},
{id:'1WL_vbL3hjwBDYsevXALX0H5gGCDAX6Qq',file:'Rojas paradigma simbolico computacional 2022.pdf',title:'Paradigma simbólico computacional, modularidad de la mente y lenguaje',author:'Carlos Rodrigo Rojas Zepeda',size:'168 KB',status:'texto extraíble',lead:'El paradigma simbólico computacional propone que la mente es un sistema de procesamiento compuesto por un conjunto de estructuras organizadas que operan siguiendo reglas precisas para tratar y transformar la información.',body:'Al respecto, Jerry Fodor (1983) nos presenta un modelo que supone una organización modular de la mente. Dichos módulos son específicos e innatos y serían responsables de nuestro comportamiento.'},
{id:'1hugwcx3p_IWWEVEJrCNiuqYAqDdog0o8',file:'Miller La_revolucion_cognitiva_una_perspectiva 2006.pdf',title:'La revolución cognitiva: una perspectiva histórica',author:'George A. Miller',size:'65 KB',status:'texto extraíble',lead:'La Ciencia Cognitiva es una criatura de los años cincuenta, producto de una época cuando la psicología, la antropología y la lingüística se redefinían a sí mismas y la ciencia de la computación y la neurociencia surgían como disciplinas.',body:'La psicología no podía participar en la revolución cognitiva hasta tanto no se librara del conductismo, restableciéndole así a la cognición respetabilidad científica.'},
{id:'1i3LxEQMF2LgH1AHGBsxQaadhO8ji6rGG',file:'Recorrido de los cientificos Cognitivos_evolucion_pensamiento_Bruner Apunte de catedra.pdf',title:'Recorrido de los Científicos Cognitivos',author:'Dra. Gabriela Ramos Mejía',size:'241 KB',status:'texto extraíble',lead:'Jerome Bruner, constituye quizás uno de los exponentes más importantes de los modelos psicológicos contemporáneos, ha sido junto con muchos otros, especialmente George Miller, el fundador de lo que hoy conocemos como Psicología Cognitiva.',body:'El presente trabajo consiste en un recorrido por la evolución su pensamiento. En primer lugar realizaremos un breve recorrido biográfico para luego tomar tres momentos de su vida a través de diferentes textos.'},
{id:'1i3LVQbkeAEWxJdd73M21w9EFDtBcTy71',file:'Teoria_computacional Apunte de Catedra.pdf',title:'La teoría computacional',author:'Dra. Gabriela Ramos Mejía',size:'376 KB',status:'texto extraíble',lead:'La mente es un sistema simbólico, se maneja con símbolos. Nos movemos en un universo de información.',body:'Los procesos mentales procesan un número enorme de percepciones. Sensaciones, ideas, creencias, etc. Representaciones mentales o símbolos.'},
{id:'1E1iSOM1Iz4xAjdLRdnvNJ5WFVY1X9JFQ',file:'Diaz García, Ruiz Fernández y Villalobos Crespo (2017). Manual de técnicas y terapias cognitivo conductuales.pdf',title:'Manual de técnicas y terapias cognitivo conductuales',author:'Díaz García · Ruiz Fernández · Villalobos Crespo',size:'3.36 MB',status:'sin texto extraíble en esta prueba',scan:true},
{id:'1CpEezUw_xc5xEA2tXltXucxXhA-E8WXP',file:'Mahoney M. y Freeman A. (1988). Cognición y Psicoterapia. Cap. 3.pdf',title:'Cognición y psicoterapia',author:'Michael J. Mahoney · Arthur Freeman',size:'979 KB',status:'texto extraíble',lead:'Se han propuesto muchas teorías a lo largo de los años para explicar la conducta humana.',body:'Las conceptualizaciones básicas sobre la naturaleza humana que dichas teorías adoptan y los procesos causales que postulan requieren un examen cuidadoso por distintos motivos.'},
{id:'1Co6S2eUSajqHjaPa-UmwFL9KgQSh3WPN',file:'Fernández Álvarez H. (1988). Fundamentos de un modelo integrativo en psicoterapia. Cap 3..pdf',title:'La psicología cognitiva y la psicoterapia',author:'Héctor Fernández Álvarez',size:'1.16 MB',status:'texto extraíble',lead:'Los desarrollos de la moderna psicología cognitiva han realizado valiosas aportaciones en distintos campos, muchas de las cuales son el punto de apoyo sobre el que se basa la elaboración de un modelo integrativo de psicoterapia como el que aquí presentamos.',body:'Hablar de una psicología cognitiva moderna hace referencia al impresionante movimiento que se ha expandido a lo largo y a lo ancho del conocimiento psicológico en las últimas tres décadas.'},
{id:'1Ciy04OdM_V38HOyNZ5xQyDplAHD91GEL',file:'Gardner H. (1988). La nueva ciencia de la mente. Cap. 2.pdf',title:'Los cimientos de la ciencia cognitiva',author:'Howard Gardner',size:'9.61 MB',status:'texto extraíble',lead:'En setiembre de 1948, un grupo de eminentes científicos, representantes de diversas disciplinas, se reunieron en el predio del Instituto de Tecnología de California para celebrar un simposio sobre “Los mecanismos cerebrales en la conducta”.',body:'Este congreso se había proyectado a fin de facilitar el intercambio de ideas acerca de un tema clásico: la forma en que el sistema nervioso controla la conducta.'},
{id:'1Cd46xQm9hE4ImrqnzOJwYHNVV79TFYIb',file:'Gardner H. (1988). La nueva ciencia de la mente. Cap. 3.pdf',title:'Las primeras décadas de la ciencia cognitiva',author:'Howard Gardner',size:'7.73 MB',status:'texto extraíble',lead:'Rara vez los aficionados a la historia alcanzaron un grado tal de consenso: hay coincidencia casi unánime entre los principales sobrevivientes de aquella época, en cuanto a que la ciencia cognitiva fue admitida oficialmente alrededor de 1956.',body:'El psicólogo George A. Miller (1979) dio incluso una fecha más precisa: el 11 de setiembre de 1956.'},
{id:'1Ccia3HsS-8dunO_K4I-WvK30hUsy_8x1',file:'Holyoak, K.J. (2002). Psicología. Pp. 29-40.pdf',title:'Psicología',author:'Keith J. Holyoak',size:'8.10 MB',status:'texto extraíble',lead:'La psicología es la ciencia que investiga la representación y procesamiento de la información de los organismos complejos.',body:'Muchas especies animales son capaces de tomar información sobre su entorno, formar representaciones internas del mismo y manipular esas representaciones para seleccionar y ejecutar acciones.'}
];
const $=id=>document.getElementById(id);
const E={list:$('fileList'),type:$('fileType'),title:$('fileTitle'),meta:$('fileMeta'),paper:$('paperContent'),drive:$('driveId')};
let active=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderList(){
 E.list.innerHTML=docs.map((d,i)=>`<button class="file-row" type="button" data-i="${i}" data-active="${i===active?'1':'0'}"><span class="file-icon">PDF</span><span><span class="file-name">${esc(d.file)}</span><span class="file-sub">${esc(d.size)} · ${esc(d.status)}</span></span><span class="file-arrow">→</span></button>`).join('');
 E.list.querySelectorAll('.file-row').forEach(b=>b.addEventListener('click',()=>{active=Number(b.dataset.i);render();}));
}
function renderPreview(){
 const d=docs[active];
 E.type.textContent='GOOGLE DRIVE / PDF';
 E.title.textContent=d.title;
 E.meta.textContent=`${d.author} · ${d.size} · vista interna de la primera página`;
 E.drive.textContent=`drive:${d.id}`;
 if(d.scan){
   E.paper.innerHTML=`<div class="scan-state"><div><strong>PDF detectado</strong><span>Este archivo no devolvió texto extraíble en esta prueba. Prometeo puede listar el archivo, pero todavía no tiene una página textual que mostrar sin añadir OCR o render binario.</span></div></div>`;
 } else {
   E.paper.innerHTML=`<p class="kicker">Vista previa · fragmento extraído de página 1</p><h3>${esc(d.title)}</h3><p class="author">${esc(d.author)}</p><p>${esc(d.lead)}</p><p>${esc(d.body)}</p>`;
 }
}
function render(){renderList();renderPreview()}
render();