const docs=[
{id:'1VhggV-9Ivmiijqoex-xpIrUlQItoPPzz',file:'Mieles barrera Aportes de la ciencia cognitiva a la comprension de la cognicion 2024.pdf',title:'Aportes de la ciencia cognitiva a la comprensión de la cognición',author:'María Dilia Mieles Barrera',size:'251 KB',status:'texto extraíble',lead:'El surgimiento de la denominada Ciencia Cognitiva ocurrió en los años 50 del siglo XX en los Estados Unidos, a raíz de la crisis del conductismo.',body:'Esta nueva perspectiva se traza el propósito de investigar los principios del procesamiento cognitivo, el pensamiento, el comportamiento inteligente y la representación del conocimiento desde una perspectiva interdisciplinar.'},
{id:'1WL_vbL3hjwBDYsevXALX0H5gGCDAX6Qq',file:'Rojas paradigma simbolico computacional 2022.pdf',title:'Paradigma simbólico computacional, modularidad de la mente y lenguaje',author:'Carlos Rodrigo Rojas Zepeda',size:'168 KB',status:'texto extraíble',lead:'El paradigma simbólico computacional propone que la mente es un sistema de procesamiento compuesto por estructuras organizadas que operan siguiendo reglas precisas.',body:'En esta perspectiva, la modularidad de la mente y el lenguaje se discuten a partir de los aportes de Fodor y Chomsky, junto con críticas provenientes de otros enfoques cognitivos.'},
{id:'1hugwcx3p_IWWEVEJrCNiuqYAqDdog0o8',file:'Miller La_revolucion_cognitiva_una_perspectiva 2006.pdf',title:'La revolución cognitiva: una perspectiva histórica',author:'George A. Miller',size:'65 KB',status:'texto extraíble',lead:'La Ciencia Cognitiva es una criatura de los años cincuenta, producto de una época en que varias disciplinas se redefinían y nuevas áreas comenzaban a surgir.',body:'Miller presenta un relato histórico y personal sobre la transformación de la psicología, el cuestionamiento del conductismo y la aparición de un campo cognitivo interdisciplinario.'},
{id:'1i3LxEQMF2LgH1AHGBsxQaadhO8ji6rGG',file:'Recorrido de los cientificos Cognitivos_evolucion_pensamiento_Bruner Apunte de catedra.pdf',title:'Recorrido de los Científicos Cognitivos',author:'Dra. Gabriela Ramos Mejía',size:'241 KB',status:'texto extraíble',lead:'Jerome Bruner constituye uno de los exponentes más importantes de los modelos psicológicos contemporáneos y participó en la fundación de la Psicología Cognitiva.',body:'El apunte recorre la evolución de su pensamiento y distintos momentos de su trayectoria, desde sus investigaciones sobre percepción hasta sus desarrollos sobre cultura y mente.'},
{id:'1i3LVQbkeAEWxJdd73M21w9EFDtBcTy71',file:'Teoria_computacional Apunte de Catedra.pdf',title:'La teoría computacional',author:'Dra. Gabriela Ramos Mejía',size:'376 KB',status:'texto extraíble',lead:'La mente es un sistema simbólico y se maneja con símbolos. Los procesos mentales procesan percepciones, sensaciones, ideas, creencias y representaciones.',body:'El texto introduce los sistemas simbólicos, la computación y los niveles de análisis propuestos por David Marr para pensar la mente como sistema de procesamiento.'},
{id:'1E1iSOM1Iz4xAjdLRdnvNJ5WFVY1X9JFQ',file:'Diaz García, Ruiz Fernández y Villalobos Crespo (2017). Manual de técnicas y terapias cognitivo conductuales.pdf',title:'Manual de técnicas y terapias cognitivo conductuales',author:'Díaz García · Ruiz Fernández · Villalobos Crespo',size:'3.36 MB',status:'sin texto extraíble en esta prueba',scan:true},
{id:'1CpEezUw_xc5xEA2tXltXucxXhA-E8WXP',file:'Mahoney M. y Freeman A. (1988). Cognición y Psicoterapia. Cap. 3.pdf',title:'Cognición y psicoterapia',author:'Michael J. Mahoney · Arthur Freeman',size:'979 KB',status:'texto extraíble',lead:'Se han propuesto muchas teorías para explicar la conducta humana. Las conceptualizaciones sobre la naturaleza humana y los procesos causales requieren un examen cuidadoso.',body:'El capítulo presentado en el archivo desarrolla un modelo de causalidad en la teoría del aprendizaje social y discute cómo las concepciones teóricas orientan la investigación psicológica.'},
{id:'1Co6S2eUSajqHjaPa-UmwFL9KgQSh3WPN',file:'Fernández Álvarez H. (1988). Fundamentos de un modelo integrativo en psicoterapia. Cap 3..pdf',title:'Fundamentos de un modelo integrativo en psicoterapia',author:'Héctor Fernández Álvarez',size:'1.16 MB',status:'texto extraíble',lead:'Los desarrollos de la moderna psicología cognitiva han realizado aportaciones en distintos campos y sirven de apoyo para la elaboración de un modelo integrativo de psicoterapia.',body:'El capítulo analiza la expansión de la psicología cognitiva y su influencia sobre el campo de la clínica y la psicoterapia.'},
{id:'1Ciy04OdM_V38HOyNZ5xQyDplAHD91GEL',file:'Gardner H. (1988). La nueva ciencia de la mente. Cap. 2.pdf',title:'Los cimientos de la ciencia cognitiva',author:'Howard Gardner',size:'9.61 MB',status:'texto extraíble',lead:'En septiembre de 1948, un grupo de científicos de diversas disciplinas se reunió en el Instituto de Tecnología de California para un simposio sobre mecanismos cerebrales en la conducta.',body:'Gardner reconstruye los antecedentes de la ciencia cognitiva y el desafío al conductismo a partir de figuras como von Neumann, McCulloch y Lashley.'},
{id:'1Cd46xQm9hE4ImrqnzOJwYHNVV79TFYIb',file:'Gardner H. (1988). La nueva ciencia de la mente. Cap. 3.pdf',title:'Las primeras décadas de la ciencia cognitiva',author:'Howard Gardner',size:'7.73 MB',status:'texto extraíble',lead:'Existe amplio consenso en situar alrededor de 1956 la admisión oficial de la ciencia cognitiva como nuevo campo interdisciplinario.',body:'El capítulo recupera el simposio de teoría de la información del MIT y el encuentro entre psicología experimental, lingüística teórica y simulación computacional.'},
{id:'1Ccia3HsS-8dunO_K4I-WvK30hUsy_8x1',file:'Holyoak, K.J. (2002). Psicología. Pp. 29-40.pdf',title:'Psicología',author:'Keith J. Holyoak',size:'8.10 MB',status:'texto extraíble',lead:'La psicología investiga la representación y el procesamiento de la información en organismos complejos.',body:'El texto describe cómo los organismos adquieren información del entorno, forman representaciones internas y utilizan esos procesos para seleccionar y ejecutar acciones.'}
];
const $=id=>document.getElementById(id);
const E={list:$('fileList'),type:$('fileType'),title:$('fileTitle'),meta:$('fileMeta'),paper:$('paperContent'),drive:$('driveId')};
let active=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderList(){
 E.list.innerHTML=docs.map((d,i)=>`<button class="file-row" type="button" data-i="${i}" data-active="${i===active?'1':'0'}"><span class="file-icon">PDF</span><span><span class="file-name">${esc(d.file)}</span><span class="file-sub">${esc(d.size)} · ${esc(d.status)}</span></span><span class="file-arrow">→</span></button>`).join('');
 E.list.querySelectorAll('.file-row').forEach(b=>b.addEventListener('click',()=>{active=Number(b.dataset.i);render();}));
}
function renderPreview(){
 const d=docs[active];
 E.type.textContent='GOOGLE DRIVE / PDF';
 E.title.textContent=d.title;
 E.meta.textContent=`${d.author} · ${d.size} · vista interna de la primera página`;
 E.drive.textContent=`drive:${d.id}`;
 if(d.scan){
   E.paper.innerHTML=`<div class="scan-state"><div><strong>PDF detectado</strong><span>Este archivo no devolvió texto extraíble en esta prueba. Prometeo puede listar el archivo, pero todavía no tiene una página textual que mostrar sin añadir OCR o render binario.</span></div></div>`;
 } else {
   E.paper.innerHTML=`<p class="kicker">Vista previa · fragmento de página 1</p><h3>${esc(d.title)}</h3><p class="author">${esc(d.author)}</p><p>${esc(d.lead)}</p><p>${esc(d.body)}</p>`;
 }
}
function render(){renderList();renderPreview()}
render();