(function(){
const {TOPICS,esc,currentSourceText,getUnit,S,save,$,$$}=window.__M3V7_WHITEBOARD_BOOT__;
let unit=getUnit();
/* ---------- WHITEBOARD ---------- */
const B=$('#board'),C=$('#boardCanvas'),ctx=C.getContext('2d'),wrap=$('#canvasWrap');
let boardTool='select',lineStyle='arrow',boardColor='#111111',boardWidth=3,selected=[],drawing=null,gesture=null,lasso=null,penSeen=false,currentEmoji='💡';
const history=new Map(),redoHistory=new Map(),imageCache=new Map();
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function migrateBoard(b){if(!b.objects)b.objects=[];if(b.strokes){b.strokes.forEach(s=>b.objects.push({id:uid(),type:s.type==='arrow'?'line':'stroke',points:s.points||[],color:s.color||'#111',width:s.w||3,style:s.type==='arrow'?'arrow':s.type==='high'?'high':'pen'}));delete b.strokes}if(b.emojis){b.emojis.forEach(e=>b.objects.push({id:uid(),type:'emoji',x:e.x||.5,y:e.y||.5,size:44,char:e.c||'💡'}));delete b.emojis}return b}
function boardState(){const b=S.boards[unit]||(S.boards[unit]={objects:[]});return migrateBoard(b)}
function snap(){return JSON.stringify(boardState().objects)}
function beginHistory(){const h=history.get(unit)||[],s=snap();if(h[h.length-1]!==s)h.push(s);if(h.length>60)h.shift();history.set(unit,h);redoHistory.set(unit,[])}
function restore(str){boardState().objects=JSON.parse(str);selected=[];save();renderBoard();syncSelectionBar()}
function undo(){const h=history.get(unit)||[];if(!h.length)return;const r=redoHistory.get(unit)||[];r.push(snap());redoHistory.set(unit,r);restore(h.pop());history.set(unit,h)}
function redo(){const r=redoHistory.get(unit)||[];if(!r.length)return;const h=history.get(unit)||[];h.push(snap());history.set(unit,h);restore(r.pop());redoHistory.set(unit,r)}
function size(){const r=C.getBoundingClientRect();return{w:r.width,h:r.height,left:r.left,top:r.top}}
function pnorm(e){const r=size();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.w)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.h))}}
function resizeCanvas(){const r=size();if(r.w<2||r.h<2)return;const d=Math.min(devicePixelRatio||1,2);C.width=Math.round(r.w*d);C.height=Math.round(r.h*d);ctx.setTransform(d,0,0,d,0,0);renderBoard()}
new ResizeObserver(resizeCanvas).observe(wrap);
function loadImg(src){if(imageCache.has(src))return imageCache.get(src);const im=new Image();imageCache.set(src,im);im.onload=renderBoard;im.onerror=()=>{if(im.crossOrigin){const im2=new Image();imageCache.set(src,im2);im2.onload=renderBoard;im2.src=src}};if(!src.startsWith('data:'))im.crossOrigin='anonymous';im.src=src;return im}
function pxPoint(p){const r=size();return{x:p.x*r.w,y:p.y*r.h}}
function objBBox(o){const r=size();if(o.type==='emoji'){const w=o.size||44;return{x:o.x*r.w-w/2,y:o.y*r.h-w/2,w,h:w}}if(o.type==='image')return{x:o.x*r.w,y:o.y*r.h,w:o.w*r.w,h:o.h*r.h};if(o.type==='line')return{x:Math.min(o.x1,o.x2)*r.w,y:Math.min(o.y1,o.y2)*r.h,w:Math.max(8,Math.abs(o.x2-o.x1)*r.w),h:Math.max(8,Math.abs(o.y2-o.y1)*r.h)};const pts=o.points||[];if(!pts.length)return{x:0,y:0,w:0,h:0};const xs=pts.map(p=>p.x*r.w),ys=pts.map(p=>p.y*r.h),pad=(o.width||3)+5;return{x:Math.min(...xs)-pad,y:Math.min(...ys)-pad,w:Math.max(...xs)-Math.min(...xs)+pad*2,h:Math.max(...ys)-Math.min(...ys)+pad*2}}
function unionBBox(ids=selected){const boxes=ids.map(id=>boardState().objects.find(o=>o.id===id)).filter(Boolean).map(objBBox);if(!boxes.length)return null;const x=Math.min(...boxes.map(b=>b.x)),y=Math.min(...boxes.map(b=>b.y)),x2=Math.max(...boxes.map(b=>b.x+b.w)),y2=Math.max(...boxes.map(b=>b.y+b.h));return{x,y,w:x2-x,h:y2-y}}
function lineSegDist(px,py,x1,y1,x2,y2){const A=px-x1,B=py-y1,Cc=x2-x1,D=y2-y1,d=Cc*Cc+D*D,t=d?Math.max(0,Math.min(1,(A*Cc+B*D)/d)):0,x=x1+t*Cc,y=y1+t*D;return Math.hypot(px-x,py-y)}
function hitObject(p,radius=15){const s=size(),px=p.x*s.w,py=p.y*s.h;for(const o of [...boardState().objects].reverse()){if(o.type==='stroke'){const pts=o.points||[];for(let i=1;i<pts.length;i++){const a=pxPoint(pts[i-1]),b=pxPoint(pts[i]);if(lineSegDist(px,py,a.x,a.y,b.x,b.y)<radius+(o.width||3)/2)return o}}else if(o.type==='line'){if(lineSegDist(px,py,o.x1*s.w,o.y1*s.h,o.x2*s.w,o.y2*s.h)<radius)return o}else{const b=objBBox(o);if(px>=b.x-radius&&px<=b.x+b.w+radius&&py>=b.y-radius&&py<=b.y+b.h+radius)return o}}return null}
function drawArrowHead(x1,y1,x2,y2,double=false){const ang=Math.atan2(y2-y1,x2-x1),L=14;ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-L*Math.cos(ang-.55),y2-L*Math.sin(ang-.55));ctx.moveTo(x2,y2);ctx.lineTo(x2-L*Math.cos(ang+.55),y2-L*Math.sin(ang+.55));ctx.stroke();if(double){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x1+L*Math.cos(ang-.55),y1+L*Math.sin(ang-.55));ctx.moveTo(x1,y1);ctx.lineTo(x1+L*Math.cos(ang+.55),y1+L*Math.sin(ang+.55));ctx.stroke()}}
function drawObj(o){const s=size();ctx.save();ctx.lineCap='round';ctx.lineJoin='round';if(o.type==='stroke'){ctx.strokeStyle=o.color||'#111';ctx.lineWidth=o.width||3;if(o.style==='high'){ctx.globalAlpha=.33;ctx.globalCompositeOperation='multiply'}const pts=o.points||[];if(pts.length){ctx.beginPath();ctx.moveTo(pts[0].x*s.w,pts[0].y*s.h);for(let i=1;i<pts.length;i++)ctx.lineTo(pts[i].x*s.w,pts[i].y*s.h);ctx.stroke()}}else if(o.type==='line'){const x1=o.x1*s.w,y1=o.y1*s.h,x2=o.x2*s.w,y2=o.y2*s.h;ctx.strokeStyle=o.color||'#111';ctx.lineWidth=o.width||3;if(o.style==='dashed')ctx.setLineDash([10,8]);ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();if(o.style==='arrow'||o.style==='double')drawArrowHead(x1,y1,x2,y2,o.style==='double');if(o.style==='ticks'){const n=5,dx=(x2-x1)/n,dy=(y2-y1)/n,ang=Math.atan2(y2-y1,x2-x1)+Math.PI/2;for(let i=1;i<n;i++){const x=x1+dx*i,y=y1+dy*i;ctx.beginPath();ctx.moveTo(x-5*Math.cos(ang),y-5*Math.sin(ang));ctx.lineTo(x+5*Math.cos(ang),y+5*Math.sin(ang));ctx.stroke()}}}else if(o.type==='emoji'){ctx.font=`${o.size||44}px system-ui,Apple Color Emoji,Segoe UI Emoji`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.char,o.x*s.w,o.y*s.h)}else if(o.type==='image'){const im=loadImg(o.src);if(im.complete&&im.naturalWidth)try{ctx.drawImage(im,o.x*s.w,o.y*s.h,o.w*s.w,o.h*s.h)}catch{}}ctx.restore()}
function renderBoard(){const s=size();ctx.clearRect(0,0,s.w,s.h);boardState().objects.forEach(drawObj);if(drawing)drawObj(drawing);if(lasso){ctx.save();ctx.strokeStyle='#777';ctx.setLineDash([5,5]);ctx.strokeRect(lasso.x,lasso.y,lasso.w,lasso.h);ctx.restore()}if(selected.length){const b=unionBBox();if(b){ctx.save();ctx.strokeStyle='#2563eb';ctx.lineWidth=1.5;ctx.setLineDash([5,4]);ctx.strokeRect(b.x-4,b.y-4,b.w+8,b.h+8);ctx.setLineDash([]);ctx.fillStyle='#fff';ctx.strokeStyle='#2563eb';for(const [x,y] of [[b.x-4,b.y-4],[b.x+b.w+4,b.y+b.h+4]]){ctx.beginPath();ctx.rect(x-5,y-5,10,10);ctx.fill();ctx.stroke()}ctx.restore()}}}
function syncSelectionBar(){$('#selectionBar').classList.toggle('show',selected.length>0)}
function translateObj(o,dx,dy){if(o.type==='stroke')o.points.forEach(p=>{p.x+=dx;p.y+=dy});else if(o.type==='line'){o.x1+=dx;o.x2+=dx;o.y1+=dy;o.y2+=dy}else{o.x+=dx;o.y+=dy}}
function scaleObj(o,cx,cy,k){const s=size();if(o.type==='stroke')o.points.forEach(p=>{const x=p.x*s.w,y=p.y*s.h;p.x=(cx+(x-cx)*k)/s.w;p.y=(cy+(y-cy)*k)/s.h});else if(o.type==='line'){for(const key of ['x1','x2'])o[key]=(cx+(o[key]*s.w-cx)*k)/s.w;for(const key of ['y1','y2'])o[key]=(cy+(o[key]*s.h-cy)*k)/s.h}else if(o.type==='emoji'){const x=o.x*s.w,y=o.y*s.h;o.x=(cx+(x-cx)*k)/s.w;o.y=(cy+(y-cy)*k)/s.h;o.size=Math.max(16,(o.size||44)*k)}else{const x=o.x*s.w,y=o.y*s.h;o.x=(cx+(x-cx)*k)/s.w;o.y=(cy+(y-cy)*k)/s.h;o.w*=k;o.h*=k}}
function eraseAt(p,seen){const hit=hitObject(p,25);if(!hit||seen.has(hit.id))return;seen.add(hit.id);const a=boardState().objects,i=a.findIndex(o=>o.id===hit.id);if(i>=0)a.splice(i,1);selected=selected.filter(id=>id!==hit.id);renderBoard();syncSelectionBar()}
function pointerAllowed(e){if(e.pointerType==='pen'){penSeen=true;return true}if(e.pointerType==='touch'&&penSeen&&['pen','high','line'].includes(boardTool))return false;return true}
C.addEventListener('pointerdown',e=>{if(!pointerAllowed(e))return;e.preventDefault();try{C.setPointerCapture(e.pointerId)}catch{}const p=pnorm(e),s=size(),pp={x:p.x*s.w,y:p.y*s.h};if(boardTool==='emojiPlace'){beginHistory();const o={id:uid(),type:'emoji',x:p.x,y:p.y,size:46,char:currentEmoji};boardState().objects.push(o);selected=[o.id];setActiveTool('select');save();renderBoard();syncSelectionBar();return}if(boardTool==='eraser'){beginHistory();gesture={mode:'erase',id:e.pointerId,seen:new Set()};eraseAt(p,gesture.seen);return}if(boardTool==='select'){const b=unionBBox();if(b&&selected.length&&Math.hypot(pp.x-(b.x+b.w+4),pp.y-(b.y+b.h+4))<20){gesture={mode:'resize',id:e.pointerId,anchor:{x:b.x-4,y:b.y-4},start:pp,base:JSON.parse(snap()),hist:false};return}const hit=hitObject(p,12);if(hit){if(e.shiftKey||e.metaKey){selected=selected.includes(hit.id)?selected.filter(id=>id!==hit.id):[...selected,hit.id]}else if(!selected.includes(hit.id))selected=[hit.id];gesture={mode:'move',id:e.pointerId,last:p,hist:false};syncSelectionBar();renderBoard();return}selected=[];syncSelectionBar();gesture={mode:'lasso',id:e.pointerId,start:pp};lasso={x:pp.x,y:pp.y,w:0,h:0};renderBoard();return}beginHistory();if(boardTool==='line'){if(lineStyle==='curve')drawing={id:uid(),type:'stroke',style:'pen',color:boardColor,width:boardWidth,points:[p]};else drawing={id:uid(),type:'line',style:lineStyle,color:boardColor,width:boardWidth,x1:p.x,y1:p.y,x2:p.x,y2:p.y}}else drawing={id:uid(),type:'stroke',style:boardTool==='high'?'high':'pen',color:boardTool==='high'?'#f0ca32':boardColor,width:boardTool==='high'?Math.max(12,boardWidth*5):boardWidth,points:[p]};renderBoard()},{passive:false});
C.addEventListener('pointermove',e=>{if(!gesture&&!drawing)return;if(!pointerAllowed(e))return;e.preventDefault();const p=pnorm(e),s=size(),pp={x:p.x*s.w,y:p.y*s.h};if(gesture?.mode==='erase'){eraseAt(p,gesture.seen);return}if(gesture?.mode==='move'){if(!gesture.hist){beginHistory();gesture.hist=true}const dx=p.x-gesture.last.x,dy=p.y-gesture.last.y;boardState().objects.filter(o=>selected.includes(o.id)).forEach(o=>translateObj(o,dx,dy));gesture.last=p;renderBoard();return}if(gesture?.mode==='resize'){const a=gesture.anchor,sd=Math.max(20,Math.hypot(gesture.start.x-a.x,gesture.start.y-a.y)),nd=Math.max(20,Math.hypot(pp.x-a.x,pp.y-a.y)),k=nd/sd;if(!gesture.hist){beginHistory();gesture.hist=true}boardState().objects=JSON.parse(JSON.stringify(gesture.base));boardState().objects.filter(o=>selected.includes(o.id)).forEach(o=>scaleObj(o,a.x,a.y,k));renderBoard();return}if(gesture?.mode==='lasso'){const a=gesture.start;lasso={x:Math.min(a.x,pp.x),y:Math.min(a.y,pp.y),w:Math.abs(pp.x-a.x),h:Math.abs(pp.y-a.y)};renderBoard();return}if(drawing){if(drawing.type==='line'){drawing.x2=p.x;drawing.y2=p.y}else{const evs=e.getCoalescedEvents?e.getCoalescedEvents():[e];evs.forEach(x=>drawing.points.push(pnorm(x)))}renderBoard()}},{passive:false});
function finishPointer(e){if(gesture){if(gesture.mode==='lasso'&&lasso){selected=boardState().objects.filter(o=>{const b=objBBox(o),cx=b.x+b.w/2,cy=b.y+b.h/2;return cx>=lasso.x&&cx<=lasso.x+lasso.w&&cy>=lasso.y&&cy<=lasso.y+lasso.h}).map(o=>o.id);lasso=null;syncSelectionBar();renderBoard()}if(['move','resize','erase'].includes(gesture.mode)){save();syncSelectionBar();renderBoard()}gesture=null}if(drawing){boardState().objects.push(drawing);drawing=null;save();renderBoard()}}
C.addEventListener('pointerup',finishPointer,{passive:false});C.addEventListener('pointercancel',finishPointer,{passive:false});
function setActiveTool(t){boardTool=t;$$('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));$('#lineBtn').classList.toggle('active',t==='line')}
$$('.tool').forEach(b=>b.onclick=()=>{closePopovers();setActiveTool(b.dataset.tool)});function closePopovers(except){$$('.popover').forEach(p=>{if(p!==except)p.classList.remove('open')})}function togglePopover(p){const was=p.classList.contains('open');closePopovers();p.classList.toggle('open',!was)}
const COLORS=['#111111','#5f6360','#c93434','#e67e22','#e4b51e','#3f9b5f','#4aa7c0','#2757d8','#7a4ad8','#d34d92','#ffffff'];$('#colorPopover').innerHTML=COLORS.map(c=>`<button class="swatch ${c===boardColor?'active':''}" data-c="${c}" style="background:${c}" aria-label="${c}"></button>`).join('');$('#colorBtn').onclick=()=>togglePopover($('#colorPopover'));$$('.swatch').forEach(b=>b.onclick=()=>{boardColor=b.dataset.c;$('#colorWell').style.background=boardColor;$$('.swatch').forEach(x=>x.classList.toggle('active',x===b));closePopovers()});
const WIDTHS=[1.5,3,6,12];$('#widthPopover').innerHTML=WIDTHS.map(w=>`<button class="widthChoice" data-w="${w}"><i style="--w:${w}px"></i></button>`).join('');$('#widthBtn').onclick=()=>togglePopover($('#widthPopover'));$$('.widthChoice').forEach(b=>b.onclick=()=>{boardWidth=+b.dataset.w;$('.widthSample').style.borderTopWidth=Math.max(1,Math.min(7,boardWidth))+'px';closePopovers()});
const lineOptions=[['line','<svg viewBox="0 0 24 24"><path d="M4 20L20 4"/></svg>'],['arrow','<svg viewBox="0 0 24 24"><path d="M4 20L19 5M12 5h7v7"/></svg>'],['double','<svg viewBox="0 0 24 24"><path d="M5 19L19 5M5 12v7h7M12 5h7v7"/></svg>'],['dashed','<svg viewBox="0 0 24 24"><path stroke-dasharray="4 3" d="M4 20L20 4"/></svg>'],['ticks','<svg viewBox="0 0 24 24"><path d="M4 20L20 4M8 18l-2-2M12 14l-2-2M16 10l-2-2"/></svg>'],['curve','<svg viewBox="0 0 24 24"><path d="M4 18c4-12 12 4 16-10"/></svg>']];$('#linePopover').innerHTML=lineOptions.map(([v,svg])=>`<button class="lineChoice" data-line="${v}">${svg}</button>`).join('');$('#lineBtn').onclick=()=>togglePopover($('#linePopover'));$$('.lineChoice').forEach(b=>b.onclick=()=>{lineStyle=b.dataset.line;setActiveTool('line');closePopovers()});
const ECATS={Recientes:['💡','🧠','⚠️','✅','❌','❓','🔁','🔗','➡️','⬅️','↔️','⭐','📌','💬','👁️','🎯'],Símbolos:['✅','❌','⚠️','❓','❗','⭕','🔴','🟢','🟡','🔵','⬛','⬜','➕','➖','✖️','➗','♾️','💯','🔗','🔒','🔓','✔️','☑️','🔘','🔺','🔻','◼️','◻️'],Flechas:['➡️','⬅️','⬆️','⬇️','↔️','↕️','↗️','↘️','↙️','↖️','🔁','🔄','⤴️','⤵️','🔀','🔃','▶️','◀️','⏩','⏪'],Ideas:['🧠','💡','👁️','💬','🗣️','👂','📌','🎯','🧩','🔍','📚','📝','🧪','⚙️','🌐','🕸️','🗺️','🧭','📊','📈'],Personas:['👤','👥','🧑','👩','👨','🧒','👵','👴','🤝','🙋','🤔','🫂','👉','👈','☝️','👇','👍','👎','🫵','✋','👌','👏'],Objetos:['📱','💻','🖥️','⌨️','📷','🖼️','📖','📕','📒','📎','✂️','🔑','🔔','⏱️','📍','🧭','🪜','🪞','🧰','🧲','🔬','🧪','📡'],Naturaleza:['🌱','🌿','🌳','🌎','🌍','🌞','🌙','☁️','🔥','💧','🌊','🧬','🐕','🐈','🐦','🐝','🦋','🌸','🍃']};
function renderEmojiPicker(cat='Recientes'){const pop=$('#emojiPopover');pop.innerHTML=`<input class="emojiSearch" id="emojiSearch" placeholder="Buscá o pegá cualquier emoji"/><div class="emojiCats">${Object.keys(ECATS).map(c=>`<button data-cat="${c}">${c}</button>`).join('')}</div><div class="emojiGrid" id="emojiGrid"></div>`;$('#emojiGrid').innerHTML=ECATS[cat].map(e=>`<button data-e="${e}">${e}</button>`).join('');$$('.emojiCats button').forEach(b=>b.onclick=()=>renderEmojiPicker(b.dataset.cat));$$('#emojiGrid button').forEach(b=>b.onclick=()=>{currentEmoji=b.dataset.e;setActiveTool('emojiPlace');closePopovers()});$('#emojiSearch').oninput=e=>{const v=e.target.value.trim();if(v){currentEmoji=v;setActiveTool('emojiPlace')}}}
renderEmojiPicker();$('#emojiBtn').onclick=()=>togglePopover($('#emojiPopover'));
function addImage(src){beginHistory();const o={id:uid(),type:'image',src,x:.22,y:.22,w:.42,h:.3};boardState().objects.push(o);selected=[o.id];save();renderBoard();syncSelectionBar();setActiveTool('select');closePopovers()}
function fileToImage(file){if(!file||!file.type.startsWith('image/'))return;const rd=new FileReader();rd.onload=()=>addImage(rd.result);rd.readAsDataURL(file)}$('#imageBtn').onclick=()=>$('#imageInput').click();$('#imageInput').onchange=e=>{fileToImage(e.target.files[0]);e.target.value=''};wrap.addEventListener('dragover',e=>e.preventDefault());wrap.addEventListener('drop',e=>{e.preventDefault();fileToImage([...e.dataTransfer.files].find(f=>f.type.startsWith('image/')))});window.addEventListener('paste',e=>{if(!B.classList.contains('open'))return;const f=[...e.clipboardData.files].find(x=>x.type.startsWith('image/'));if(f)fileToImage(f)});
async function pinterestResults(keyword){const data={options:{query:keyword,scope:'pins',rs:'typed'},context:{}};const source='/search/pins/?q='+encodeURIComponent(keyword);const url='https://www.pinterest.com/resource/BaseSearchResource/get/?source_url='+encodeURIComponent(source)+'&data='+encodeURIComponent(JSON.stringify(data))+'&_='+Date.now();const r=await fetch(url,{headers:{'x-pinterest-pws-handler':'www/search/[scope].js'}});if(!r.ok)throw Error('Pinterest '+r.status);const j=await r.json(),arr=j?.resource_response?.data?.results||[];return arr.map(x=>({thumb:x?.images?.['236x']?.url||x?.images?.orig?.url,src:x?.images?.orig?.url||x?.images?.['736x']?.url})).filter(x=>x.thumb&&x.src).slice(0,3)}
function pinFallback(row,key){row.innerHTML=`<div class="pinImages">${[1,2,3].map(()=>`<button class="pinCard pinSearch"><span class="pinFallback">Pinterest ↗</span></button>`).join('')}</div><div class="pinStatus">Si Pinterest bloquea las miniaturas, tocá para abrir esa búsqueda.</div>`;$$('.pinSearch',row).forEach(b=>b.onclick=()=>window.open('https://www.pinterest.com/search/pins/?q='+encodeURIComponent(key),'_blank','noopener'))}
async function loadPinRow(row,key){row.innerHTML='<div class="pinStatus">cargando…</div>';try{const imgs=await pinterestResults(key);if(!imgs.length)throw Error('vacío');row.innerHTML=`<div class="pinImages">${imgs.map((x,i)=>`<button class="pinCard" data-i="${i}"><img src="${x.thumb}" alt=""/></button>`).join('')}</div>`;$$('.pinCard',row).forEach(b=>b.onclick=()=>addImage(imgs[+b.dataset.i].src))}catch{pinFallback(row,key)}}
function openPinterest(){const pop=$('#pinPopover'),keys=TOPICS[unit].visual;pop.innerHTML=`<div class="pinTitle"><strong>Pinterest · U${unit+1}</strong><span>3 por búsqueda</span></div>${keys.map((k,i)=>`<div class="pinRow"><div class="pinRowLabel">${esc(k)}</div><div class="pinRowBody" data-row="${i}"></div></div>`).join('')}`;togglePopover(pop);keys.forEach((k,i)=>loadPinRow($(`[data-row="${i}"]`,pop),k))}$('#pinBtn').onclick=openPinterest;
function scaleSelection(k){if(!selected.length)return;const b=unionBBox();beginHistory();boardState().objects.filter(o=>selected.includes(o.id)).forEach(o=>scaleObj(o,b.x+b.w/2,b.y+b.h/2,k));save();renderBoard()}$('#smallerSel').onclick=()=>scaleSelection(.9);$('#biggerSel').onclick=()=>scaleSelection(1.12);$('#deleteSel').onclick=()=>{if(!selected.length)return;beginHistory();boardState().objects=boardState().objects.filter(o=>!selected.includes(o.id));selected=[];save();renderBoard();syncSelectionBar()};$('#duplicateSel').onclick=()=>{if(!selected.length)return;beginHistory();const clones=boardState().objects.filter(o=>selected.includes(o.id)).map(o=>{const c=JSON.parse(JSON.stringify(o));c.id=uid();translateObj(c,.03,.03);return c});boardState().objects.push(...clones);selected=clones.map(o=>o.id);save();renderBoard();syncSelectionBar()};$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;
$('#boardBtn').onclick=()=>{unit=getUnit();B.classList.add('open');B.setAttribute('aria-hidden','false');B.classList.toggle('hideTheory',innerWidth<700);const text=currentSourceText().split(/\n\n+/).filter(Boolean).slice(0,18);$('#boardTheory').innerHTML=`<h2>${esc(TOPICS[unit].t)}</h2>${text.map(p=>`<p>${esc(p)}</p>`).join('')}`;selected=[];setActiveTool('select');closePopovers();document.documentElement.style.overflow='hidden';setTimeout(resizeCanvas,30)};$('#closeBoard').onclick=()=>{B.classList.remove('open');B.setAttribute('aria-hidden','true');document.documentElement.style.overflow='';save()};$('#theoryBtn').onclick=()=>B.classList.toggle('hideTheory');


})();
