function render(){
  E.voices.innerHTML=voices.map(v=>{const c=C(v.id);return`<button class="voice ${selected===v.id?'active':''} ${playing===v.id?'playing':''}" data-id="${v.id}"><div class="vn">${v.name}</div><div class="vk">${v.kind}</div><div class="vs"><i class="dot ${c.status}"></i><span>${statusText(c.status)}${c.status==='ready'&&c.bytes?` · ${Math.round(c.bytes/1024)} KB`:''}</span></div></button>`}).join('');
  document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>select(b.dataset.id));
  const v=V(selected),c=C(selected);E.pname.textContent=v.name;E.prompt.value=v.prompt;
  let extra='';if(c.status==='generating'&&c.started)extra=` · ${Math.round((performance.now()-c.started)/1000)} s`;if(c.status==='ready')extra=` · ${c.cache||''}${c.ms?` · ${(c.ms/1000).toFixed(1)} s`:''}`;if(c.error)extra=` · ${c.error}`;
  E.pstate.textContent=statusText(c.status)+extra;
  E.play.textContent=audio&&playing===selected&&!audio.paused?'❚❚':'▶';
  E.fill.style.width=audio&&playing===selected&&Number.isFinite(audio.duration)&&audio.duration>0?`${Math.min(100,audio.currentTime/audio.duration*100)}%`:'0%';
}
function select(id){if(!C(id)||id===selected)return;stop();selected=id;localStorage.setItem(LS+'selected',id);render()}
function enqueue(id,front=false){const c=C(id);if(!c||['ready','generating','checking'].includes(c.status))return;c.status='queued';if(!queue.includes(id))front?queue.unshift(id):queue.push(id);render();run()}
async function check(id,front=false){const c=C(id);if(!c||['ready','generating'].includes(c.status))return;c.status='checking';c.error=null;render();const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),5000),t=performance.now();try{const r=await fetch(`${API}?id=${encodeURIComponent(clipId(id))}`,{cache:'no-store',signal:ctrl.signal});if(r.ok){return setReady(id,await r.blob(),r,t,'HIT')}}catch(e){}finally{clearTimeout(timer)}c.status='queued';render();enqueue(id,front)}
function setReady(id,blob,r,t,cache){const c=C(id);if(c.url)URL.revokeObjectURL(c.url);c.status='ready';c.blob=blob;c.url=URL.createObjectURL(blob);c.bytes=blob.size;c.ms=performance.now()-t;c.cache=r.headers.get('x-audio-lab-cache')||cache;c.error=null;c.attempts=0;log(`${V(id).name} lista · ${c.cache} · ${Math.round(c.bytes/1024)} KB`);render()}
async function generate(id){const c=C(id),v=V(id);if(c.status==='ready')return;c.status='generating';c.started=performance.now();c.error=null;c.attempts++;render();const gap=Math.max(0,5000-(Date.now()-lastPost));if(gap)await new Promise(r=>setTimeout(r,gap));lastPost=Date.now();const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),240000),t=performance.now();try{log(`generando página · ${v.name} · intento ${c.attempts}`);const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},signal:ctrl.signal,body:JSON.stringify({voicePrompt:v.prompt,text:PAGE_TEXT,messageId:clipId(id)})});if(!r.ok){let d='';try{d=await r.text()}catch{}const e=new Error(`HTTP ${r.status}${d?` · ${d.slice(0,140)}`:''}`);e.status=r.status;throw e}setReady(id,await r.blob(),r,t,'MISS')}catch(e){c.error=e.name==='AbortError'?'timeout de generación':e.message;if((e.status===429||e.name==='AbortError')&&c.attempts<3){c.status='queued';if(!queue.includes(id))queue.push(id);log(`reintento pendiente · ${v.name}`);await new Promise(r=>setTimeout(r,e.status===429?15000:5000))}else{c.status='error';log(`ERROR · ${v.name} · ${c.error}`)}render()}finally{clearTimeout(timer)}}
