(()=>{'use strict';
const qs=new URLSearchParams(location.search);
if(qs.get('legacy')==='1') return;
if(window.__STUDY_V18) return;
window.__STUDY_V18=true;
const CURRICULUM='./psychology-curriculum-v1.json?v=180';
const ENRICHMENT='./course-enrichment-v16.json?v=180';
const LOGO='https://upload.wikimedia.org/wikipedia/commons/b/b4/Logo-up.jpg';
const THEMES=['mono','violet','forest','clay'];
const THEME_LABEL={mono:'UP Mono',violet:'Noche violeta',forest:'Bosque',clay:'Arcilla'};
const YEARS={1:['1','RO'],2:['2','DO'],3:['3','RO'],4:['4','TO']};
let curriculum=[],enrich=[],byId=new Map(),openYear=1,activeCourse=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const microlink=url=>'https://api.microlink.io/?'+new URLSearchParams({url,embed:'image.url'}).toString();
const currentTheme=()=>document.documentElement.dataset.studyTheme||'mono';
function setTheme(name){const t=THEMES.includes(name)?name:'mono';document.documentElement.dataset.studyTheme=t;try{localStorage.setItem('study:v18:theme',t)}catch{}const live=document.querySelector('[data-theme-live]');if(live){live.textContent=THEME_LABEL[t];live.classList.add('show');setTimeout(()=>live.classList.remove('show'),850)}}
function cycleTheme(){const i=THEMES.indexOf(currentTheme());setTheme(THEMES[(i+1+THEMES.length)%THEMES.length])}
function courseRow(id){return curriculum.find(x=>x.course_id===id)||null}
function enrichRow(id){return byId.get(id)||null}
function legacyURL(id){const u=new URL(location.href);u.search='';u.searchParams.set('legacy','1');if(id)u.searchParams.set('course',id);return u.toString()}
function coverURL(row){const e=enrichRow(row.course_id);return e?.cover?.pin_url?microlink(e.cover.pin_url):''}
function metaText(row){return `${row.year_no}º año · ${row.semester_no}º cuatrimestre`}
function logoBlock(){return `<div class="v18Brand"><img src="${LOGO}" alt="Universidad de Palermo"><strong>Psicología</strong></div>`}
function themeButton(){return `<button class="v18Theme" type="button" data-v18-theme aria-label="Cambiar tema" title="Cambiar tema"><i></i></button>`}
function yearTile(y){const [n,s]=YEARS[y];return `<button class="v18Year ${openYear===y?'on':''}" data-v18-year="${y}" type="button" aria-label="${y}º año"><span class="v18YearNum">${n}</span><span class="v18YearSuffix">${s}</span></button>`}
function coverCard(row){const img=coverURL(row);return `<button class="v18Course" type="button" data-v18-course="${esc(row.course_id)}"><span class="v18CourseCover">${img?`<img src="${esc(img)}" alt="" loading="lazy" decoding="async" onerror="this.remove()">`:''}<i></i><b>${esc(row.canonical_title)}</b></span></button>`}
function semesterShelf(year,sem){const rows=curriculum.filter(x=>x.year_no===year&&x.semester_no===sem).sort((a,b)=>(a.order_no||99)-(b.order_no||99));return `<section class="v18Semester"><aside class="v18SemesterRail"><span>${sem===1?'PRIMER':'SEGUNDO'}</span><b>CUATRIMESTRE</b></aside><div class="v18ShelfViewport"><div class="v18Shelf">${rows.map(coverCard).join('')}</div><div class="v18ShelfLine"></div></div></section>`}
function homeHTML(){return `<main class="v18Shell v18Home"><header class="v18Header">${logoBlock()}${themeButton()}</header><section class="v18Years">${[1,2,3,4].map(yearTile).join('')}</section><section class="v18YearContent">${semesterShelf(openYear,1)}${semesterShelf(openYear,2)}</section><footer class="v18Foot"><a href="${esc(legacyURL())}">Ver versión anterior</a></footer></main>`}
function moduleCard(key,title,desc){return `<button class="v18Module" type="button" data-v18-module="${key}"><span>${title}</span><small>${desc}</small></button>`}
function materialsPanel(row){const e=enrichRow(row.course_id),c=e?.current_external,h=e?.historical_archive;if(!c&&!h)return `<div class="v18PanelText">Todavía no hay una fuente externa asociada a esta materia en V18.</div>`;return `<div class="v18MaterialLinks">${c?`<a href="${esc(c.url)}" target="_blank" rel="noopener"><b>Material actual</b><span>${esc(c.label||'Abrir carpeta')}</span></a>`:''}${h?`<a href="${esc(h.url)}" target="_blank" rel="noopener"><b>Archivo histórico</b><span>${esc(h.label||'Abrir archivo')}</span></a>`:''}</div>`}
function migrationPanel(row,label){return `<div class="v18PanelText">${label} conserva por ahora su funcionalidad completa en la interfaz anterior mientras se migra a este diseño.</div><a class="v18LegacyAction" href="${esc(legacyURL(row.course_id))}">Abrir ${label.toLowerCase()} anterior</a>`}
function courseHTML(row){const img=coverURL(row),e=enrichRow(row.course_id);return `<main class="v18Shell v18CourseView"><header class="v18CourseTop"><button class="v18Back" type="button" data-v18-back aria-label="Volver">←</button>${themeButton()}</header><section class="v18CourseHero"><div class="v18HeroCover">${img?`<img src="${esc(img)}" alt="" decoding="async" onerror="this.remove()">`:''}<i></i></div><div class="v18HeroCopy"><span>${esc(metaText(row))}</span><h1>${esc(row.canonical_title)}</h1>${row.metadata?.focus?`<p>${esc(row.metadata.focus)}</p>`:''}</div></section><nav class="v18Modules">${moduleCard('classes','Clases','Sesiones y contenidos')}${moduleCard('chat','Chat','Conversación de la materia')}${moduleCard('boards','Pizarrones','Pizarrones compartidos')}${moduleCard('materials','Materiales','Fuentes y archivos')}</nav><section class="v18ModulePanel" data-v18-panel><div class="v18PanelText">Elegí una sección.</div></section><footer class="v18Foot"><a href="${esc(legacyURL(row.course_id))}">Ver esta materia en la versión anterior</a>${e?.cover?.pin_url?`<a href="${esc(e.cover.pin_url)}" target="_blank" rel="noopener">Referencia de portada</a>`:''}</footer></main>`}
function root(){let r=document.getElementById('studyV18Root');if(!r){r=document.createElement('div');r.id='studyV18Root';document.body.appendChild(r)}return r}
function wireTheme(scope){scope.querySelectorAll('[data-v18-theme]').forEach(b=>b.onclick=cycleTheme)}
function wireShelf(scope){scope.querySelectorAll('.v18Shelf').forEach(row=>row.addEventListener('wheel',e=>{if(row.scrollWidth<=row.clientWidth)return;const d=Math.abs(e.deltaY)>=Math.abs(e.deltaX)?e.deltaY:e.deltaX;if(!d)return;e.preventDefault();row.scrollLeft+=d},{passive:false}))}
function renderHome(push=true){activeCourse=null;if(push){const u=new URL(location.href);u.searchParams.delete('course');u.searchParams.delete('legacy');history.pushState({v18:'home'},'',u)}const r=root();r.innerHTML=homeHTML();wireTheme(r);wireShelf(r);r.querySelectorAll('[data-v18-year]').forEach(b=>b.onclick=()=>{openYear=Number(b.dataset.v18Year);renderHome(false)});r.querySelectorAll('[data-v18-course]').forEach(b=>b.onclick=()=>renderCourse(b.dataset.v18Course,true));window.scrollTo({top:0,behavior:'auto'})}
function renderCourse(id,push=true){const row=courseRow(id);if(!row)return;activeCourse=id;if(push){const u=new URL(location.href);u.searchParams.delete('legacy');u.searchParams.set('course',id);history.pushState({v18:'course',course:id},'',u)}const r=root();r.innerHTML=courseHTML(row);wireTheme(r);r.querySelector('[data-v18-back]').onclick=()=>renderHome(true);r.querySelectorAll('[data-v18-module]').forEach(b=>b.onclick=()=>openModule(row,b.dataset.v18Module,b));window.scrollTo({top:0,behavior:'auto'})}
function openModule(row,key,button){const r=root(),panel=r.querySelector('[data-v18-panel]');r.querySelectorAll('[data-v18-module]').forEach(x=>x.classList.toggle('on',x===button));if(key==='materials')panel.innerHTML=materialsPanel(row);else if(key==='classes')panel.innerHTML=migrationPanel(row,'Clases');else if(key==='chat')panel.innerHTML=migrationPanel(row,'Chat');else panel.innerHTML=migrationPanel(row,'Pizarrones')}
async function boot(){document.body.classList.add('studyV18');try{const [a,b]=await Promise.all([fetch(CURRICULUM,{cache:'no-store'}),fetch(ENRICHMENT,{cache:'no-store'})]);if(!a.ok||!b.ok)throw new Error('data');const c=await a.json(),e=await b.json();curriculum=(c.curriculum||[]).filter(x=>x.year_no>=1&&x.year_no<=4&&[1,2].includes(x.semester_no));enrich=e.courses||[];byId=new Map(enrich.map(x=>[x.course_id,x]));const requested=qs.get('course');if(requested&&courseRow(requested))renderCourse(requested,false);else renderHome(false);const live=document.createElement('div');live.className='v18ThemeLive';live.dataset.themeLive='';document.body.appendChild(live)}catch(err){console.warn('Study V18',err);root().innerHTML=`<main class="v18Shell"><div class="v18Error"><b>UP · Psicología</b><span>No pude cargar la biblioteca.</span><a href="${esc(legacyURL())}">Abrir versión anterior</a></div></main>`}}
window.addEventListener('popstate',()=>{const q=new URLSearchParams(location.search);const id=q.get('course');if(id&&courseRow(id))renderCourse(id,false);else renderHome(false)});
boot();
})();
