let docTimer;function syncDoc(){clearTimeout(docTimer);docTimer=setTimeout(async()=>{const txt=notes.sort((a,b)=>a.position-b.position).map(x=>x.content).filter(Boolean).join('\n\n');await roomClient.from('study_session_docs').upsert({session_id:room.id,shared_notes:txt,version:Date.now(),updated_by:st.profile.name,updated_at:new Date().toISOString()},{onConflict:'session_id'})},900)}
function renderChunks(){const el=$('#chunks');if(!el)return;const arr=[...chunks].sort((a,b)=>String(a.created_at||'').localeCompare(String(b.created_at||''))||(a.start_ms||0)-(b.start_ms||0));el.innerHTML=arr.map(x=>{const pend=['queued','transcribing'].includes(x.status),retry=x.status==='error'&&x.participant_id===st.profile.id?` · <button class="speak" data-retry="${x.id}">reintentar</button>`:'';return `<div class="chunk ${pend?'pending':''}"><div class="chunkMeta"><span>${esc(x.participant_name)} · ${ms(x.start_ms)}–${ms(x.end_ms)}</span><span>${x.status==='ready'?'listo':x.status==='error'?'error'+retry:`transcribiendo <span class="loader"><i></i><i></i><i></i></span>`}</span></div><div class="chunkText">${esc(x.transcript||x.provisional_text||'procesando audio…')}</div></div>`}).join('')||'<div class="chunk tiny ghost">La transcripción va a aparecer acá mientras grabás.</div>';$$('[data-retry]').forEach(b=>b.onclick=()=>retryChunk(b.dataset.retry));el.scrollTop=el.scrollHeight;renderFullTranscript()}
function ms(v){const s=Math.floor(Number(v||0)/1000);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}function fullText(){return [...chunks].filter(x=>x.status==='ready'&&x.transcript).sort((a,b)=>String(a.created_at||'').localeCompare(String(b.created_at||''))||(a.start_ms||0)-(b.start_ms||0)).map(x=>`[${x.participant_name} ${ms(x.start_ms)}] ${x.transcript}`).join('\n\n')}function renderFullTranscript(){if($('#fullTranscript'))$('#fullTranscript').textContent=fullText()||'Todavía no hay fragmentos terminados.'}
function renderChat(){const el=$('#chatList');if(!el)return;el.innerHTML=chat.map(m=>`<div class="msg" data-msg="${m.id}"><div class="msgHead"><span class="msgWho">${esc(m.author_name)}</span><span><button class="speak" data-speak="${m.id}">▶ voz</button> <span class="msgTime">${fmtClock(m.created_at)}</span></span></div><div class="msgBody">${esc(m.body)}</div></div>`).join('')||'<div class="tiny ghost" style="padding:12px 0">Chat de esta clase. Queda guardado.</div>';$$('[data-speak]').forEach(b=>b.onclick=()=>{const m=chat.find(x=>x.id===b.dataset.speak);if(m)queueSpeak(m)});el.scrollTop=el.scrollHeight}
async function sendChat(){const i=$('#chatInput'),body=i.value.trim();if(!body||!roomClient)return;const m={id:crypto.randomUUID(),session_id:room.id,author_id:st.profile.id,author_name:st.profile.name,body,voice_id:st.profile.voice,audio_mode:'edge',created_at:new Date().toISOString()};i.value='';const q=await roomClient.from('study_chat_messages').insert(m);if(q.error){toast('No se pudo enviar');return}chat.push(m);renderChat();broadcast('chat',{message:m});setActivity('chat');setTimeout(()=>setActivity('online'),900)}
function queueSpeak(m){audioChain=audioChain.then(()=>speak(m)).catch(()=>{});return audioChain}async function speak(m){const parts=(`Habla ${m.author_name}. `+m.body).match(/.{1,280}(?:\s|$)/g)||[m.body];for(const text of parts){const r=await fetch(TTS,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:text.trim(),voice:m.voice_id||'es-AR-TomasNeural'})});if(!r.ok)throw new Error('tts');const b=await r.blob(),u=URL.createObjectURL(b),a=new Audio(u);a.volume=st.audio.volume;await new Promise((res,rej)=>{a.onended=res;a.onerror=rej;a.play().catch(rej)});URL.revokeObjectURL(u)}}
async function connectRealtime(){cleanupChannel();channel=sb.channel('study-class-'+room.id+'-'+room.token.slice(0,16),{config:{presence:{key:st.profile.id}}});channel.on('presence',{event:'sync'},()=>{presence=channel.presenceState();renderRoster()}).on('broadcast',{event:'room'},({payload})=>onBroadcast(payload));channel.subscribe(async status=>{if(status==='SUBSCRIBED'){await trackPresence('online');renderRoster();startTranscriptPoll();resumeLocalPending()}})}function cleanupChannel(){if(channel){sb.removeChannel(channel);channel=null}presence={}}
function broadcast(type,data){channel?.send({type:'broadcast',event:'room',payload:{type,from:st.profile.id,...data}})}async function trackPresence(activity='online',blockId=null){if(channel)await channel.track({participantId:st.profile.id,name:st.profile.name,activity,blockId,at:Date.now()})}function setActivity(a,b=null){trackPresence(a,b);broadcast('activity',{activity:a,blockId:b,name:st.profile.name})}
function onBroadcast(p){if(!p||p.from===st.profile.id)return;if(p.type==='chat'){if(!chat.some(x=>x.id===p.message.id)){chat.push(p.message);renderChat();if(st.audio.autoplay)queueSpeak(p.message)}}else if(p.type==='note'){const b=p.block,i=notes.findIndex(x=>x.id===b.id),focused=document.activeElement?.closest?.('.noteBlock')?.dataset.block;if(focused!==b.id){if(i>=0)notes[i]=b;else notes.push(b);renderNotes()}}else if(p.type==='editing'){editingBy[p.blockId]=p.name;const e=$('#edit-'+p.blockId);if(e)e.textContent=p.name+' editando';setTimeout(()=>{if(editingBy[p.blockId]===p.name){delete editingBy[p.blockId];const x=$('#edit-'+p.blockId);if(x)x.textContent=''}},2600)}else if(p.type==='transcript'){const x=p.chunk,i=chunks.findIndex(c=>c.id===x.id);if(i>=0)chunks[i]={...chunks[i],...x};else chunks.push(x);renderChunks()}else if(p.type==='profile'){participants[p.participant.participant_id]=p.participant;renderRoster()}}
function cleanupRoom(){clearInterval(startTranscriptPoll.t);startTranscriptPoll.t=null;cleanupChannel();if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(rec&&rec.state!=='inactive')try{rec.stop()}catch{}clearTimeout(sliceTimer);stopRecognition();recLive=false;recPaused=false}
function pickMime(){return ['audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus','audio/mp4'].find(x=>MediaRecorder.isTypeSupported?.(x))||''}
async function startRecording(){if(recLive&&recPaused){recPaused=false;part++;recLive=true;startSlice();startRecognition();updateRecUI();renderParts();setActivity('grabando');return}if(recLive)return;try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}})}catch{toast('Necesito permiso de micrófono');return}recLive=true;recPaused=false;recStarted=Date.now();part=1;seq=0;startSlice();startRecognition();timerLoop();updateRecUI();renderParts();setActivity('grabando')}
function startSlice(){if(!recLive||recPaused||!stream)return;const mime=pickMime(),pieces=[];recPieces=pieces;sliceStarted=Date.now();rec=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);rec.ondataavailable=e=>{if(e.data?.size)pieces.push(e.data)};rec.onstop=()=>{const end=Date.now(),blob=new Blob(pieces,{type:rec.mimeType||pieces[0]?.type||'audio/webm'}),start=Math.max(0,sliceStarted-recStarted),finish=Math.max(start,end-recStarted);if(recLive&&!recPaused)startSlice();if(blob.size>500)handleAudioChunk(blob,start,finish)};rec.start();clearTimeout(sliceTimer);sliceTimer=setTimeout(rotateSlice,20000)}
function rotateSlice(){if(rec?.state==='recording')rec.stop()}
function toggleBreak(){if(!recLive)return;if(!recPaused){recPaused=true;clearTimeout(sliceTimer);if(rec?.state==='recording')rec.stop();stopRecognition();updateRecUI();setActivity('recreo')}else{recPaused=false;part++;startSlice();startRecognition();updateRecUI();renderParts();setActivity('grabando')}}
function finishRecording(){if(!recLive)return;recLive=false;recPaused=false;clearTimeout(sliceTimer);if(rec?.state==='recording')rec.stop();setTimeout(()=>{stream?.getTracks().forEach(t=>t.stop());stream=null},250);stopRecognition();room.status='complete';st.sessions[room.id]=room;save();roomClient.from('study_class_sessions').update({status:'complete',updated_at:new Date().toISOString()}).eq('id',room.id);updateRecUI();setActivity('online');toast('Clase cerrada · transcripciones pendientes siguen procesando')}
function updateRecUI(){const e=$('#recState');if(!e)return;e.classList.toggle('live',recLive&&!recPaused);$('#recLabel').textContent=!recLive?'listo':recPaused?'recreo':'grabando';$('#recStart').disabled=recLive&&!recPaused;$('#recStart').textContent=recLive&&recPaused?'REANUDAR':'GRABAR';$('#recBreak').disabled=!recLive;$('#recBreak').textContent=recPaused?'REANUDAR':'RECREO';$('#recFinish').disabled=!recLive}
function timerLoop(){if(!recLive){if($('#timer'))$('#timer').textContent='00:00';return}const s=Math.floor((Date.now()-recStarted)/1000);if($('#timer'))$('#timer').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;requestAnimationFrame(timerLoop)}
function startRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return;try{recognizer=new SR();recognizer.lang='es-AR';recognizer.continuous=true;recognizer.interimResults=true;recognizer.onresult=e=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript+' ';previewText=t.trim();if($('#preview'))$('#preview').textContent=previewText?`escuchando · ${previewText}`:'escuchando…'};recognizer.onend=()=>{if(recLive&&!recPaused)try{recognizer.start()}catch{}};recognizer.start()}catch{}}
function stopRecognition(){if(recognizer){try{recognizer.onend=null;recognizer.stop()}catch{}recognizer=null}previewText=''}
async function handleAudioChunk(blob,start,end){const id=crypto.randomUUID(),localKey=`${room.id}:${part}:${++seq}:${id}`,x={id,session_id:room.id,participant_id:st.profile.id,participant_name:st.profile.name,segment_no:part,seq,start_ms:start,end_ms:end,transcript:'',source:'whisper-large-v3-turbo',status:'queued',audio_chunk_id:localKey,mime_type:blob.type,byte_size:blob.size,provisional_text:previewText||'',created_at:new Date().toISOString()};chunks.push(x);renderChunks();broadcast('transcript',{chunk:x});putAudio(localKey,blob).catch(()=>{});transQueue.push({x,blob});pumpTranscription()}
async function pumpTranscription(){while(transActive<2&&transQueue.length){const j=transQueue.shift();transActive++;transcribeJob(j).finally(()=>{transActive--;pumpTranscription()})}}
async function transcribeJob({x,blob}){x.status='transcribing';renderChunks();broadcast('transcript',{chunk:x});const f=new FormData();f.append('audio',blob,`chunk-${x.seq}.webm`);for(const [k,v] of Object.entries({session_id:room.id,room_token:room.token,chunk_id:x.id,participant_id:x.participant_id,participant_name:x.participant_name,segment_no:x.segment_no,seq:x.seq,start_ms:x.start_ms,end_ms:x.end_ms,audio_chunk_id:x.audio_chunk_id,provisional_text:x.provisional_text||''}))f.append(k,String(v));try{const r=await fetch(TRANSCRIBE,{method:'POST',body:f}),data=await r.json();if(!r.ok||!data.ok)throw new Error(data.detail||data.error||'transcripción');x.status='ready';x.transcript=data.transcript||'';x.source=data.source||x.source;x.finished_processing_at=new Date().toISOString();broadcast('transcript',{chunk:x});renderChunks();await updateFullDoc()}catch(e){x.status='error';x.error=String(e.message||e);broadcast('transcript',{chunk:x});renderChunks()}}
async function updateFullDoc(){const txt=fullText();await roomClient.from('study_session_docs').upsert({session_id:room.id,full_transcript:txt,updated_by:st.profile.name,updated_at:new Date().toISOString(),version:Date.now()},{onConflict:'session_id'})}
function startTranscriptPoll(){clearInterval(startTranscriptPoll.t);startTranscriptPoll.t=setInterval(refreshTranscripts,8000)}
async function refreshTranscripts(){if(!roomClient||!room)return;const q=await roomClient.from('study_transcript_chunks').select('*').eq('session_id',room.id).order('created_at').limit(500);if(q.data){chunks=q.data;renderChunks()}}
async function resumeLocalPending(){for(const x of chunks.filter(x=>x.participant_id===st.profile.id&&['queued','error'].includes(x.status))){const blob=await getAudio(x.audio_chunk_id).catch(()=>null);if(blob){x.status='queued';transQueue.push({x,blob})}}pumpTranscription()}
async function retryChunk(id){const x=chunks.find(x=>x.id===id);if(!x)return;const blob=await getAudio(x.audio_chunk_id).catch(()=>null);if(!blob){toast('Ese audio no está en este dispositivo');return}x.status='queued';x.error=null;renderChunks();transQueue.push({x,blob});pumpTranscription()}
function openDB(){if(!dbPromise)dbPromise=new Promise((res,rej)=>{const q=indexedDB.open('study-audio-v4',1);q.onupgradeneeded=()=>q.result.createObjectStore('chunks');q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});return dbPromise}async function putAudio(k,b){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction('chunks','readwrite');t.objectStore('chunks').put(b,k);t.oncomplete=res;t.onerror=()=>rej(t.error)})}async function getAudio(k){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction('chunks','readonly'),r=t.objectStore('chunks').get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function openProfile(){const old=$('#profileSheet');old?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="profileSheet" id="profileSheet"><div class="sheet"><h2>Perfil de clase</h2><div class="profilePreview" id="profilePreview">${st.profile.avatar?`<img src="${st.profile.avatar}">`:esc(initials(st.profile.name))}</div><div class="field"><label>FOTO CUADRADA</label><input id="avatarFile" type="file" accept="image/*"></div><div class="field"><label>NOMBRE</label><input id="profileName" value="${esc(st.profile.name)}" maxlength="40"></div><div class="field"><label>VOZ WALKY</label><select id="profileVoice"><option value="es-AR-TomasNeural">Tomás · AR</option><option value="es-AR-ElenaNeural">Elena · AR</option><option value="es-UY-MateoNeural">Mateo · UY</option><option value="es-UY-ValentinaNeural">Valentina · UY</option><option value="es-MX-JorgeNeural">Jorge · MX</option><option value="es-MX-CarlotaNeural">Carlota · MX</option></select></div><div class="sheetActions"><button class="linkBtn" id="cancelProfile">cancelar</button><button class="primary" id="saveProfile">guardar</button></div></div></div>`);$('#profileVoice').value=st.profile.voice;$('#cancelProfile').onclick=()=>$('#profileSheet').remove();$('#avatarFile').onchange=async e=>{const f=e.target.files?.[0];if(f){st.profile.avatar=await avatarData(f);$('#profilePreview').innerHTML=`<img src="${st.profile.avatar}">`}};$('#saveProfile').onclick=async()=>{st.profile.name=$('#profileName').value.trim()||'Participante';st.profile.voice=$('#profileVoice').value;save();await ensureProfile();participants[st.profile.id]={...participants[st.profile.id],display_name:st.profile.name,avatar_data:st.profile.avatar,voice_id:st.profile.voice};broadcast('profile',{participant:participants[st.profile.id]});trackPresence('online');$('#profileSheet').remove();renderSession();connectRealtime()}}
function avatarData(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onerror=rej;fr.onload=()=>{const im=new Image();im.onerror=rej;im.onload=()=>{const c=document.createElement('canvas'),z=160;c.width=z;c.height=z;const g=c.getContext('2d'),s=Math.min(im.width,im.height),sx=(im.width-s)/2,sy=(im.height-s)/2;g.drawImage(im,sx,sy,s,s,0,0,z,z);res(c.toDataURL('image/jpeg',.78))};im.src=fr.result};fr.readAsDataURL(file)})}
async function bootstrap(){save();const q=new URLSearchParams(location.search),sid=q.get('session'),t=q.get('token'),cid=q.get('course');if(sid&&t){await joinShared(sid,t);return}if(cid&&C[cid])openCourse(cid);else renderLibrary()}
bootstrap();