(()=>{'use strict';
const qs=new URLSearchParams(location.search);
if(qs.get('legacy')==='1') return;
if(window.__STUDY_V18) return;
window.__STUDY_V18=true;
const CURRICULUM='./psychology-curriculum-v1.json?v=184';
const ENRICHMENT='./course-enrichment-v16.json?v=184';
const LOGO='https://upload.wikimedia.org/wikipedia/commons/b/b4/Logo-up.jpg';
const THEMES=['mono','violet','forest','clay'];
const THEME_LABEL={mono:'UP Mono',violet:'Noche violeta',forest:'Bosque',clay:'Arcilla'};
const YEARS={1:['1','RO'],2:['2','DO'],3:['3','RO'],4:['4','TO']};
let curriculum=[],enrich=[],byId=new Map(),openYear=1,activeCourse=null,activeTab='notes',logoSourcePromise=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const microlink=url=>'https://api.microlink.io/?'+new URLSearchParams({url,embed:'image.url'}).toString();
const currentTheme=()=>document.documentElement.dataset.studyTheme||'mono';
function parseColor(value){const c=document.createElement('canvas').getContext('2d');c.fillStyle='#000';c.fillStyle=value;const v=c.fillStyle;if(v[0]==='#'){const h=v.slice(1);if(h.length===3)return h.split('').map(x=>parseInt(x+x,16));return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]}const m=v.match(/rgba?\(([^)]+)\)/);return m?m[1].split(',').slice(0,3).map(Number):[0,0,0]}
function logoSource(){if(!logoSourcePromise)logoSourcePromise=new Promise((resolve,reject)=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>resolve(img);img.onerror=reject;img.src=LOGO});return logoSourcePromise}
async function paintLogos(scope=document){const canvases=[...scope.querySelectorAll('[data-up-logo]')];if(!canvases.length)return;try{const img=await logoSource();const st=getComputedStyle(document.documentElement),ink=parseColor(st.getPropertyValue('--v18-ink').trim()),bg=parseColor(st.getPropertyValue('--v18-bg').trim());for(const canvas of canvases){const ctx=canvas.getContext('2d',{willReadFrequently:true});const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);const data=ctx.getImageData(0,0,w,h),p=data.data;for(let i=0;i<p.length;i+=4){const t=(p[i]*.2126+p[i+1]*.7152+p[i+2]*.0722)/255;p[i]=Math.round(ink[0]*(1-t)+bg[0]*t);p[i+1]=Math.round(ink[1]*(1-t)+bg[1]*t);p[i+2]=Math.round(ink[2]*(1-t)+bg[2]*t);p[i+3]=255}ctx.putImageData(data,0,0);canvas.classList.remove('fallback')}}catch{for(const canvas of canvases)canvas.classList.add('fallback')}}
function setTheme(name){const t=THEMES.includes(name)?name:'mono';document.documentElement.dataset.studyTheme=t;try{localStorage.setItem('study:v18:theme',t)}catch{}const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=getComputedStyle(document.documentElement).getPropertyValue('--v18-bg').trim();paintLogos(root());const live=document.querySelector('[data-theme-live]');if(live){live.textContent=THEME_LABEL[t];live.classList.add('show');setTimeout(()=>live.classList.remove('show'),850)}}
function cycleTheme(){const i=THEMES.indexOf(currentTheme());setTheme(THEMES[(i+1+THEMES.length)%THEMES.length])}
function courseRow(id){return curriculum.find(x=>x.course_id===id)||null}
function enrichRow(id){return byId.get(id)||null}
function legacyURL(id){const u=new URL(location.href);u.search='';u.searchParams.set('legacy','1');if(id)u.searchParams.set('course',id);return u.toString()}
function coverURL(row){const e=enrichRow(row.course_id);return e?.cover?.pin_url?microlink(e.cover.pin_url):''}
function metaText(row){return `${row.year_no}º año · ${row.semester_no}º cuatrimestre`}
function logoBlock(){return `<div class="v18Brand"><canvas class="v18BrandLogo" data-up-logo width="240" height="240" role="img" aria-label="Universidad de Palermo"></canvas><strong>Psicología</strong></div>`}
function yearTile(y){const [n,s]=YEARS[y];return `<button class="v18Year ${openYear===y?'on':''}" data-v18-year="${y}" type="button" aria-label="${y}º año"><span class="v18YearMark"><span class="v18YearNum">${n}</span><span class="v18YearSuffix">${s}</span></span></button>`}
function coverCard(row){const img=coverURL(row);return `<div class="v18Course" role="button" tabindex="0" data-v18-course="${esc(row.course_id)}" aria-label="Abrir ${esc(row.canonical_title)}"><span class="v18CourseCover">${img?`<img src="${esc(img)}" alt="" loading="lazy" decoding="async" draggable="false" onerror="this.remove()">`:''}<span class="v18CourseTitleBar">${esc(row.canonical_title)}</span></span></div>`}
function semesterShelf(year,sem){const rows=curriculum.filter(x=>x.year_no===year&&x.semester_no===sem).sort((a,b)=>(a.order_no||99)-(b.order_no||99));return `<section class="v18Semester"><div class="v18Shelf"><aside class="v18SemesterRail"><span>${sem===1?'PRIMER':'SEGUNDO'}</span><b>CUATRIMESTRE</b></aside>${rows.map(coverCard).join('')}<span class="v18ShelfEnd" aria-hidden="true"></span></div><div class="v18ShelfLine"></div></section>`}
function optionsMenu(row){return `<div class="v18Options"><button class="v18Dots" type="button" data-v18-menu aria-label="Opciones">•••</button><div class="v18Menu" data-v18-menu-panel><button type="button" data-v18-login>Iniciar sesión</button><button type="button" data-v18-theme-menu>Cambiar tema</button><a href="${esc(legacyURL(row?.course_id||''))}">Versión anterior</a></div></div>`}
function homeHTML(){const left=(openYear-1)*25;return `<main class="v18Shell v18Home"><header class="v18Header">${logoBlock()}${optionsMenu(null)}</header><section class="v18Years" style="--indicator-left:${left}%">${[1,2,3,4].map(yearTile).join('')}<i class="v18YearIndicator" aria-hidden="true"></i></section><section class="v18YearContent">${semesterShelf(openYear,1)}${semesterShelf(openYear,2)}</section><footer class="v18Foot"><a href="${esc(legacyURL())}">Ver versión anterior</a></footer></main>`}
function examStrip(){return `<div class="v18Exams" aria-label="Evaluaciones"><span>1º parcial</span><span>2º parcial</span><span>Final</span></div>`}
function tabButton(key,label){return `<button class="v18Tab ${activeTab===key?'on':''}" type="button" data-v18-tab="${key}">${label}</button>`}
function driveIcon(){return `<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M17 7h14l12 21-7 12H12L5 28 17 7Zm0 0 12 21M5 28h24m14 0H29L17 7" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linejoin="round"/></svg>`}
function notesPanel(row){const items=[1,2,3,4].map((n,i)=>`<details class="v18NoteItem" ${i===0?'open':''}><summary><span>Clase ${String(n).padStart(2,'0')}</span><small>Fecha por definir</small></summary><div class="v18NoteBody"><p>Espacio compartido para las notas de esta clase. La fecha y el tema se vincularán al cronograma de la materia.</p><a href="${esc(legacyURL(row.course_id))}">Abrir herramientas anteriores</a></div></details>`).join('');return `<div class="v18SectionHead"><b>Notas de clase</b><span>Todas las clases en un solo lugar</span></div><div class="v18NotesList">${items}</div>`}
function resourcesPanel(row){const e=enrichRow(row.course_id),c=e?.current_external,h=e?.historical_archive,drive=h?.url||c?.url||'';const driveBtn=drive?`<a class="v18Drive" href="${esc(drive)}" target="_blank" rel="noopener"><i>${driveIcon()}</i><span><b>Drive viejo</b><small>Link al archivo de la materia</small></span><em>↗</em></a>`:`<div class="v18Drive disabled"><i>${driveIcon()}</i><span><b>Drive viejo</b><small>Link pendiente de configurar</small></span></div>`;const cards=[c?`<a href="${esc(c.url)}" target="_blank" rel="noopener"><b>Material actual</b><span>${esc(c.label||'Abrir carpeta')}</span></a>`:'',h?`<a href="${esc(h.url)}" target="_blank" rel="noopener"><b>Archivo histórico</b><span>${esc(h.label||'Abrir archivo')}</span></a>`:''].filter(Boolean).join('');return `<div class="v18SectionHead"><b>Recursos</b><span>Material y enlaces de la materia</span></div>${driveBtn}<div class="v18ResourceList">${cards||'<div class="v18Empty">Todavía no hay material asociado.</div>'}</div>`}
function schedulePanel(){return `<div class="v18SectionHead"><b>Cronograma</b><span>Clases, feriados y evaluaciones</span></div><div class="v18ScheduleStub"><b>Calendario de la materia</b><p>Acá se va a conectar el cronograma real: fechas de clase, feriados, parciales y encuentros sin clase.</p></div>`}
function morePanel(row){return `<div class="v18SectionHead"><b>Más</b><span>Accesos secundarios</span></div><div class="v18MoreList"><a href="${esc(legacyURL(row.course_id))}"><b>Versión anterior</b><span>Abrir la interfaz completa que ya existía</span></a></div>`}
function panelHTML(row){if(activeTab==='resources')return resourcesPanel(row);if(activeTab==='schedule')return schedulePanel();if(activeTab==='more')return morePanel(row);return notesPanel(row)}
function courseHTML(row){const img=coverURL(row);return `<main class="v18Shell v18CourseView"><header class="v18CourseTop"><button class="v18Back" type="button" data-v18-back aria-label="Volver">←</button>${optionsMenu(row)}</header><section class="v18CourseHero"><div class="v18HeroCover">${img?`<img src="${esc(img)}" alt="" decoding="async" draggable="false" onerror="this.remove()">`:''}</div><div class="v18HeroCopy"><span>${esc(metaText(row))}</span><h1>${esc(row.canonical_title)}</h1>${examStrip()}</div></section><nav class="v18Tabs" aria-label="Secciones">${tabButton('notes','Notas de clase')}${tabButton('resources','Recursos')}${tabButton('schedule','Cronograma')}${tabButton('more','Más')}</nav><section class="v18TabPanel" data-v18-panel>${panelHTML(row)}</section><footer class="v18Foot"><a href="${esc(legacyURL(row.course_id))}">Ver esta materia en la versión anterior</a></footer></main>`}
function root(){let r=document.getElementById('studyV18Root');if(!r){r=document.createElement('div');r.id='studyV18Root';document.body.appendChild(r)}return r}
function toast(text){const live=document.querySelector('[data-theme-live]');if(!live)return;live.textContent=text;live.classList.add('show');setTimeout(()=>live.classList.remove('show'),1100)}
function wireOptions(scope){const menu=scope.querySelector('[data-v18-menu-panel]'),btn=scope.querySelector('[data-v18-menu]');if(!menu||!btn)return;btn.onclick=e=>{e.stopPropagation();menu.classList.toggle('open')};scope.querySelector('[data-v18-theme-menu]')?.addEventListener('click',()=>{cycleTheme();menu.classList.remove('open')});scope.querySelector('[data-v18-login]')?.addEventListener('click',()=>{toast('Inicio de sesión · próximamente');menu.classList.remove('open')});scope.addEventListener('click',e=>{if(!e.target.closest('.v18Options'))menu.classList.remove('open')})}
function wireShelf(scope){scope.querySelectorAll('.v18Shelf').forEach(row=>{let sx=0,sy=0,drag=false,suppressUntil=0;row.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;drag=false},{passive:true});row.addEventListener('pointermove',e=>{if(Math.hypot(e.clientX-sx,e.clientY-sy)>7)drag=true},{passive:true});row.addEventListener('pointerup',()=>{if(drag)suppressUntil=Date.now()+350},{passive:true});row.addEventListener('pointercancel',()=>{if(drag)suppressUntil=Date.now()+350},{passive:true});row.addEventListener('click',e=>{if(Date.now()<suppressUntil){e.preventDefault();e.stopPropagation()}},true);row.addEventListener('wheel',e=>{if(row.scrollWidth<=row.clientWidth)return;const d=Math.abs(e.deltaY)>=Math.abs(e.deltaX)?e.deltaY:e.deltaX;if(!d)return;e.preventDefault();row.scrollLeft+=d},{passive:false})})}
function wireCourse(row){const r=root();r.querySelector('[data-v18-back]').onclick=()=>renderHome(true);wireOptions(r);r.querySelectorAll('[data-v18-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.v18Tab;r.querySelectorAll('[data-v18-tab]').forEach(x=>x.classList.toggle('on',x===b));r.querySelector('[data-v18-panel]').innerHTML=panelHTML(row)})}
function wireCourseCards(r){r.querySelectorAll('[data-v18-course]').forEach(el=>{const open=()=>renderCourse(el.dataset.v18Course,true);el.addEventListener('click',open);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
function renderHome(push=true){activeCourse=null;if(push){const u=new URL(location.href);u.searchParams.delete('course');u.searchParams.delete('legacy');history.pushState({v18:'home'},'',u)}const r=root();r.innerHTML=homeHTML();wireOptions(r);wireShelf(r);wireCourseCards(r);paintLogos(r);r.querySelectorAll('[data-v18-year]').forEach(b=>b.onclick=()=>{openYear=Number(b.dataset.v18Year);renderHome(false)});window.scrollTo({top:0,behavior:'auto'})}
function renderCourse(id,push=true){const row=courseRow(id);if(!row)return;activeCourse=id;activeTab='notes';if(push){const u=new URL(location.href);u.searchParams.delete('legacy');u.searchParams.set('course',id);history.pushState({v18:'course',course:id},'',u)}const r=root();r.innerHTML=courseHTML(row);wireCourse(row);window.scrollTo({top:0,behavior:'auto'})}
async function boot(){document.body.classList.add('studyV18');try{const [a,b]=await Promise.all([fetch(CURRICULUM,{cache:'no-store'}),fetch(ENRICHMENT,{cache:'no-store'})]);if(!a.ok||!b.ok)throw new Error('data');const c=await a.json(),e=await b.json();curriculum=(c.curriculum||[]).filter(x=>x.year_no>=1&&x.year_no<=4&&[1,2].includes(x.semester_no));enrich=e.courses||[];byId=new Map(enrich.map(x=>[x.course_id,x]));const requested=qs.get('course');if(requested&&courseRow(requested))renderCourse(requested,false);else renderHome(false);const live=document.createElement('div');live.className='v18ThemeLive';live.dataset.themeLive='';document.body.appendChild(live)}catch(err){console.warn('Study V18',err);root().innerHTML=`<main class="v18Shell"><div class="v18Error"><b>UP · Psicología</b><span>No pude cargar la biblioteca.</span><a href="${esc(legacyURL())}">Abrir versión anterior</a></div></main>`}}
window.addEventListener('popstate',()=>{const q=new URLSearchParams(location.search);const id=q.get('course');if(id&&courseRow(id))renderCourse(id,false);else renderHome(false)});
boot();
})();
