/* Prometeo Part 2 Platform v2.2 — immutable durable truth/metabolism composition root. */
((global)=>{
 'use strict';if(global.PrometeoPart2Platform)return;let singleton=null;function fail(code,msg,detail={}){const e=new Error(msg);e.code=code;e.detail=detail;throw e}
 async function bootstrap({base=null,fetcher=global.fetch}={}){if(singleton)return singleton;const required=['PrometeoDurable','PrometeoPrivacy','PrometeoCatalog','PrometeoLineage','PrometeoSupersession','PrometeoCurrentGraph','PrometeoContinuity','PrometeoBooks','PrometeoGolden','PrometeoContextFoundryV2','PrometeoContextPacks','PrometeoWorkflow','PrometeoLedger','PrometeoModificationResolver','PrometeoReincarnate','PrometeoOperatorView'],missing=required.filter(k=>!global[k]);if(missing.length)fail('PROMETEO_PART2_MISSING_RUNTIME','Missing Part 2 runtimes',{missing});const root=base?new URL(base,global.location?.href||'https://local.invalid/'):new URL('../',global.location?.href||'https://local.invalid/navigator/'),text=async path=>{const r=await fetcher(new URL(path,root).href,{cache:'no-store'});if(!r.ok)fail('PROMETEO_PART2_FETCH',`Failed ${path}`,{status:r.status});return r.text()},j=async p=>JSON.parse(await text(p)),jl=async p=>(await text(p)).trim().split(/\n+/).filter(Boolean).map(JSON.parse);
  const raw=await Promise.all([j('catalog/tree.json'),j('catalog/pages.json'),j('catalog/CATALOG_MANIFEST.json'),j('lineage/LINEAGE_GRAPH.json'),j('lineage/CAPABILITY_REGISTRY.json'),jl('lineage/SUPERSESSION.jsonl'),j('state/CURRENT_GRAPH.json'),j('state/HEAD.json'),j('state/DOT_STATE.json'),j('state/PARENT.json'),j('state/PENDING.json'),j('state/CARRY.json'),j('state/WATERMARKS.json'),j('context/books/HOT.json'),j('context/books/WARM.json'),j('context/books/COLD.json'),j('golden/GOLDEN_REFERENCES.json'),j('context/bytes/BYTE_REGISTRY.json'),j('context/registry/CONTEXT_INDEX.json'),j('reincarnation/BOOTSTRAP.json'),j('reincarnation/OPERATOR_CONTRACT.json'),jl('receipts/ledger.jsonl')]);let [tree,pages,manifest,lineage,caps,sup,current,head,dot,parent,pending,carry,watermarks,hot,warm,cold,golden,bytes,index,boot,operatorContract,ledger]=raw;
  const cat=global.PrometeoCatalog.validate({tree,pages,manifest});global.PrometeoLineage.validate(lineage,caps,{supersession:sup});global.PrometeoSupersession.validate(sup);const ledgerStatus=await global.PrometeoLedger.validate(ledger);global.PrometeoCurrentGraph.validate(current,{knownReceipts:ledgerStatus.ids,catalogIdentity:cat.sourceIdentity});global.PrometeoContinuity.validatePending(pending);global.PrometeoContinuity.validateCarry(carry);global.PrometeoContinuity.validateWatermarks(watermarks);global.PrometeoBooks.validate(hot,warm,cold);global.PrometeoGolden.validate(golden);
  const D=global.PrometeoDurable, trustedPrivacyReceipts=new Map(ledger.map(r=>[r.id,r.hash]));[tree,pages,manifest,lineage,caps,sup,current,head,dot,parent,pending,carry,watermarks,hot,warm,cold,golden,bytes,index,boot,operatorContract,ledger]=[tree,pages,manifest,lineage,caps,sup,current,head,dot,parent,pending,carry,watermarks,hot,warm,cold,golden,bytes,index,boot,operatorContract,ledger].map(D.immutable);
  const foundry=global.PrometeoContextFoundryV2.create({byteRegistry:bytes,index,privacy:global.PrometeoPrivacy,trustedPrivacyReceipts}),wake=()=>global.PrometeoReincarnate.wake({bootstrap:boot,currentGraph:current,head,dotState:dot,parent,pending,carry,watermarks,catalog:manifest,lineage,capabilities:caps,hotBook:hot,operatorContract,ledgerReceipts:ledger}),planChange=request=>global.PrometeoModificationResolver.plan({request,pages,manifest,foundry,privacy:'LOCAL'}),operator=()=>global.PrometeoOperatorView.project({currentGraph:current,pending,catalog:manifest});
  singleton=Object.freeze({schema:'prometeo.part2-platform/v1',catalog:D.immutable({tree,pages,manifest,status:cat}),lineage:D.immutable({graph:lineage,capabilities:caps,supersession:sup}),currentGraph:current,continuity:D.immutable({pending,carry,watermarks,books:{hot,warm,cold}}),golden,ledger,foundry,wake,planChange,operator,status:()=>D.immutable({catalog:cat,ledger:{count:ledgerStatus.count,lastHash:ledgerStatus.lastHash},currentRevision:current.revision,pending:(pending.items||[]).length,contextRecords:foundry.listRecords().length,visibleFrontend:current.pointers.visible_frontend_current.artifact_id})});global.__PROMETEO_PART2__=singleton;return singleton;
 }
 global.PrometeoPart2Platform=Object.freeze({version:'2.2.0-candidate',bootstrap,get:()=>singleton});
})(typeof globalThis!=='undefined'?globalThis:window);
