(()=>{
'use strict';
const VERSION='0.2.0';
const BUILD='2026-09-24';
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const TAU=Math.PI*2; const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const hash=(a,b=0)=>{const x=Math.sin(a*127.1+b*311.7)*43758.5453123;return x-Math.floor(x)};
const C={bg:'#090806',ink:'#e8dcc7',muted:'#8e8578',line:'#30291f',ochre:'#ba8754',red:'#9d3f2b',green:'#617a66',blue:'#536c70',paper:'#c7b89e',black:'#030302',brown:'#5b4030',slate:'#33322c'};

const SYSTEMS={
 avatars:{title:'Avatar Lab',group:'ACTIVIDAD',status:'PROTOTYPE',summary:'Estados del worker y liveness visual, separados del progreso durable.',trigger:'TAKE / PROGRESS / SUBMIT / heartbeat / stale',representation:'avatar móvil + acción + energía',missing:'VERIFY específico, recovery y transiciones desde eventos reales',tests:['TAKE ≠ BUILD','BUILD ≠ VERIFY','STALE queda quieto','energía desaparece con LOD']},
 blocks:{title:'Block & Material Lab',group:'MATERIA',status:'CANON',summary:'El bloque representa estado durable, no trabajo del worker.',trigger:'intent / active / accepted / candidate / superseded / fail',representation:'material + transparencia + facetas',missing:'Reducir a 3 estados para primera conexión real',tests:['INTENT legible','ACTIVE distinto de ACCEPTED','FAIL no parece progreso']},
 workpads:{title:'Work Pad Lab',group:'FRONTERA',status:'IDEA',summary:'Lugar de trabajo entre worker y estructura durable.',trigger:'READY → CLAIMED → ACTIVE → SUBMIT → ACCEPTED',representation:'pad físico + worker + transferencia',missing:'Primitiva world-space y mapeo a jobs reales',tests:['worker ≠ bloque','varios pads por torre','pad READY visible sin worker']},
 roads:{title:'Road Lab',group:'CAUSALIDAD',status:'PROTOTYPE',summary:'Una relación real se convierte en camino físico.',trigger:'edge(A,B) + estado de dependencia',representation:'camino apagado / listo / transferencia / bloqueado',missing:'Routing alrededor de torres y cruces',tests:['no atraviesa nodos','dirección causal entendible','sin edge no hay camino']},
 artifact:{title:'Artifact Transport',group:'HANDOFF',status:'PROTOTYPE',summary:'Un resultado durable se vuelve objeto transportable entre nodos.',trigger:'tower accepted → artifact → dependent READY',representation:'objeto genérico + worker + road',missing:'Integrar con Road primitive y work pads',tests:['pickup claro','transporte ocluye bien','entrega habilita destino']},
 architecture:{title:'Architecture Kit',group:'ASSET ZOO',status:'PROTOTYPE',summary:'Piezas físicas que deben compartir el lenguaje de bloques.',trigger:'uso visual en WORLD',representation:'cuboid grammar + facetas + contorno',missing:'Más estados de muro/grada y torture angles',tests:['misma paleta','misma profundidad','no 2D impostor accidental']},
 panels:{title:'Panel Torture Room',group:'REGRESSION',status:'NEEDS FIX',summary:'Prueba marcos, tipografía, LEDs y celdas contra colapso de proyección.',trigger:'yaw / zoom / semantic health',representation:'frame world-space + contenido safe/compressed/edge',missing:'Primitiva física definitiva para segmentos LED',tests:['sin espejo','sin rayas','contenido se oculta antes de colapsar','marco nunca mira a cámara']},
 effects:{title:'Effects Stage',group:'POST / FX',status:'PROTOTYPE',summary:'Efectos como capa secundaria sobre objetos sólidos.',trigger:'fire / glow / grain / registration',representation:'efecto anclado a objeto',missing:'Presupuestos de intensidad por contexto',tests:['objeto sobrevive sin glow','grano no mata texto','fuego tiene volumen lateral']},
 camera:{title:'Camera Torture Matrix',group:'AUTOTEST',status:'PROTOTYPE',summary:'Matriz de ángulos y zooms que actúa como gate visual.',trigger:'build candidate',representation:'tabla pass/warn/fail',missing:'Capturas visuales automáticas reales',tests:['yaw ±1.4','zoom .55/1/1.8','no overlap','no mirror']},
 synthetic:{title:'Synthetic Worlds',group:'FIXTURES',status:'PROTOTYPE',summary:'Grafos falsos para probar layout antes de conectar Prometeo.',trigger:'scenario fixture',representation:'polar layout + edges + agents',missing:'100 nodos optimizado y transición entre grafos',tests:['1 job','20 parallel','chain','fan-in','100 nodes','graph mutation']},
 exterior:{title:'The Exterior',group:'PERSISTENCIA',status:'IDEA',summary:'La frontera entre trabajo temporal y resultados persistentes.',trigger:'accepted durable artifact exits current run',representation:'arena interior + oscuridad exterior',missing:'Modelo persistente real',tests:['sólo accepted cruza','run reset no borra exterior']},
 manifest:{title:'World Manifest',group:'CONTRATO',status:'PROTOTYPE',summary:'Contrato universal entre adapters y renderer.',trigger:'normalized state snapshot',representation:'nodes / edges / agents / artifacts / events / focus / metrics',missing:'Adapter real desde estado canónico',tests:['renderer sin nombres workflow','fixture round-trip']},
 gaps:{title:'Status / Gap Map',group:'PRODUCCIÓN',status:'CANON',summary:'Mapa operativo de madurez visual.',trigger:'cambio de estado de sistema',representation:'IDEA / PROTOTYPE / CANON / NEEDS FIX',missing:'Nada crítico; mantener honesto',tests:['filtros','notas','export snapshot']},
 rules:{title:'Rules Board',group:'CONTRATO VISUAL',status:'CANON',summary:'Invariantes duras que una feature debe respetar antes de promoción.',trigger:'toda feature visual',representation:'reglas + acceptance tests',missing:'Agregar reglas sólo cuando haya evidencia de una nueva clase de regresión',tests:['world-space primero','no fake liveness','hide before cheating scale']}
};

const RULES=[
 ['WORLD ≠ LAB','WORLD LAB prueba. WORLD conserva hasta promoción explícita.'],
 ['actividad ≠ progreso','Workers muestran actividad; estructuras muestran estado aceptado.'],
 ['world-space primero','Objeto físico: anchor, dimensions, orientation, depth y visibility.'],
 ['información separada','Texto/LED/celdas no pueden rotar el objeto físico para ser legibles.'],
 ['hide before cheat','Contenido se oculta antes de inflar escala o convertirse en fideos.'],
 ['sin edge, sin camino','Toda ruta visual nace de una relación real.'],
 ['un solo lenguaje','Props nuevos responden: ¿cómo se construye con la gramática de cubos?'],
 ['glow secundario','La forma sólida debe leerse con todos los efectos apagados.'],
 ['liveness real','Movimiento sólo por TAKE/PROGRESS/eventos recientes, no por membresía ACTIVE.'],
 ['durable afuera','Dentro puede cambiar; afuera sólo cruza lo aceptado/persistente.'],
 ['renderer universal','El renderer entiende node/edge/agent/artifact/state/event/metric/focus.'],
 ['adapter específico','Nombres de workflow se resuelven antes de llegar al renderer.'],
 ['tests por ángulo','Centro, extremos, edge-on y zooms son gate obligatorio.'],
 ['no pixel placement','Objetos del mundo no se ubican con coordenadas arbitrarias de pantalla.'],
 ['profundidad común','Todo objeto físico entra al mismo orden de profundidad cuando corresponde.'],
 ['LOD semántico','Información pequeña se simplifica o desaparece antes de convertirse en ruido.']
];

const SCENARIOS={
 one:{label:'1 job',nodes:[{id:'A'}],edges:[]},
 parallel:{label:'20 paralelos',nodes:Array.from({length:20},(_,i)=>({id:'P'+(i+1)})),edges:[]},
 chain:{label:'A→B→C→D',nodes:['A','B','C','D'].map(id=>({id})),edges:[['A','B'],['B','C'],['C','D']]},
 fanin:{label:'8→reducer',nodes:[...Array.from({length:8},(_,i)=>({id:'B'+(i+1)})),{id:'R'}],edges:Array.from({length:8},(_,i)=>['B'+(i+1),'R'])},
 hundred:{label:'100 nodos',nodes:Array.from({length:100},(_,i)=>({id:'N'+(i+1)})),edges:Array.from({length:130},(_,i)=>['N'+((i*7)%100+1),'N'+((i*13+17)%100+1)])},
 mutate:{label:'grafo mutante',nodes:Array.from({length:18},(_,i)=>({id:'M'+(i+1)})),edges:Array.from({length:22},(_,i)=>['M'+((i*3)%18+1),'M'+((i*7+5)%18+1)])}
};

const state={paused:false,roadMode:'relation',padState:0,scenario:'chain',notes:JSON.parse(localStorage.getItem('worldlab.notes')||'{}'),testMarks:JSON.parse(localStorage.getItem('worldlab.tests')||'{}'),selected:null,testResults:[],lastScenarioUi:'',start:performance.now()};
const PAD_STATES=['READY','CLAIMED','ACTIVE','SUBMIT','ACCEPTED'];

function hexAlpha(hex,a){const n=parseInt(hex.slice(1),16),r=(n>>16)&255,g=(n>>8)&255,b=n&255;return 'rgba('+r+','+g+','+b+','+a+')'}
function setupCanvas(canvas){const dpr=Math.min(1.5,devicePixelRatio||1),r=canvas.getBoundingClientRect();const w=Math.max(10,Math.floor(r.width*dpr)),h=Math.max(10,Math.floor(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return {ctx,w:r.width,h:r.height,dpr}}
function clear(ctx,w,h){ctx.clearRect(0,0,w,h);ctx.fillStyle=C.bg;ctx.fillRect(0,0,w,h)}
function line(ctx,a,b,color=C.line,width=1,dash=[]){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}
function roughRect(ctx,x,y,w,h,fill,stroke=C.line,seed=1){const j=(i)=>((hash(seed,i)-.5)*2.4);const p=[[x+j(1),y+j(2)],[x+w+j(3),y+j(4)],[x+w+j(5),y+h+j(6)],[x+j(7),y+h+j(8)]];ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(...p[0]);p.slice(1).forEach(q=>ctx.lineTo(...q));ctx.closePath();ctx.fill();ctx.stroke()}
function circle(ctx,x,y,r,fill,stroke=C.line){ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=1.2;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();ctx.stroke()}
function label(ctx,text,x,y,color=C.muted,size=10,align='center'){ctx.fillStyle=color;ctx.font='700 '+size+'px system-ui';ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(text,x,y)}
function isoBlock(ctx,x,y,s,h,base,alpha=1,seed=1){ctx.save();ctx.globalAlpha=alpha;const top=[{x,y:y-h},{x:x+s*.65,y:y-h+s*.28},{x,y:y-h+s*.56},{x:x-s*.65,y:y-h+s*.28}];const left=[top[3],top[2],{x:top[2].x,y:top[2].y+s*.65},{x:top[3].x,y:top[3].y+s*.65}];const right=[top[2],top[1],{x:top[1].x,y:top[1].y+s*.65},{x:top[2].x,y:top[2].y+s*.65}];function poly(p,f){ctx.fillStyle=f;ctx.strokeStyle=C.black;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);for(let i=1;i<p.length;i++)ctx.lineTo(p[i].x,p[i].y);ctx.closePath();ctx.fill();ctx.stroke()}poly(left,hexAlpha(base,.78));poly(right,hexAlpha(base,.58));poly(top,hexAlpha(base,.96));ctx.restore()}
function energyBar(ctx,x,y,w,e,color){roughRect(ctx,x-w/2,y,w,5,'#080806',C.line,11);ctx.fillStyle=color;ctx.fillRect(x-w*.46,y+1,w*.92*e,3)}
function drawWorker(ctx,x,y,r,color,stateName,e=1,t=0){ctx.save();ctx.shadowBlur=stateName==='STALE'?0:5;ctx.shadowColor=hexAlpha(color,.45);circle(ctx,x,y,r,color,C.black);ctx.shadowBlur=0;ctx.fillStyle=C.paper;ctx.beginPath();ctx.arc(x-r*.22,y-r*.12,Math.max(1,r*.10),0,TAU);ctx.fill();if(stateName==='VERIFY'){ctx.strokeStyle=C.green;ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,r*1.22,-.5,1.8);ctx.stroke()}if(stateName==='BUILD'){ctx.strokeStyle=C.ochre;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+r*.7,y-r*.7);ctx.lineTo(x+r*1.25,y-r*1.25);ctx.stroke()}if(stateName==='STALE'){ctx.globalAlpha=.35;ctx.strokeStyle=C.red;ctx.beginPath();ctx.moveTo(x-r,y-r);ctx.lineTo(x+r,y+r);ctx.stroke()}energyBar(ctx,x,y-r*1.55,r*1.7,e,e>.55?C.green:e>.25?C.ochre:C.red);ctx.restore()}

function drawAvatars(ctx,w,h,t){clear(ctx,w,h);const states=['IDLE','TAKE','WALK','DESIGN','BUILD','VERIFY','CARRY','STALE'];const cols=4,rows=2;states.forEach((s,i)=>{const cx=(i%cols+.5)*w/cols,cy=(Math.floor(i/cols)+.5)*h/rows;const bob=s==='WALK'?Math.sin(t*.008+i)*5:0;const x=cx+(s==='TAKE'?Math.sin(t*.004+i)*7:0),y=cy-4+bob;drawWorker(ctx,x,y,15,[C.blue,C.ochre,C.green,C.red][i%4],s,s==='STALE'?.08:(.35+.65*((i+1)/states.length)),t);label(ctx,s,cx,cy+38,s==='STALE'?C.red:C.muted,9);if(s==='CARRY')isoBlock(ctx,x+24,y+5,10,5,C.ochre,1,20+i);if(s==='DESIGN'){ctx.strokeStyle=hexAlpha(C.green,.55);ctx.setLineDash([3,3]);ctx.strokeRect(cx-22,cy-19,44,32);ctx.setLineDash([])}})}
function drawBlocks(ctx,w,h,t){clear(ctx,w,h);const items=[['INTENT',C.blue,.24],['ACTIVE',C.ochre,.68],['ACCEPTED',C.brown,1],['CANDIDATE','#8b7c78',.68],['SUPERSEDED','#4f4b43',.9],['FAIL',C.red,.72]];const gap=w/items.length;items.forEach((it,i)=>{const x=gap*(i+.5),y=h*.60,s=Math.min(34,gap*.45);isoBlock(ctx,x,y,s,18,it[1],it[2],i);if(it[0]==='ACTIVE'){ctx.strokeStyle=C.ochre;ctx.setLineDash([4,3]);ctx.strokeRect(x-s*.65,y-52,s*1.3,50);ctx.setLineDash([])}if(it[0]==='FAIL'){line(ctx,{x:x-20,y:y-42},{x:x+20,y:y-10},C.red,2);line(ctx,{x:x+20,y:y-42},{x:x-20,y:y-10},C.red,2)}label(ctx,it[0],x,h*.82,C.muted,8)})}
function drawWorkpads(ctx,w,h,t){clear(ctx,w,h);const st=PAD_STATES[state.padState];const padX=w*.5,padY=h*.66;ctx.strokeStyle=C.line;ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(padX,padY,70,22,0,0,TAU);ctx.stroke();ctx.fillStyle='#17120e';ctx.fill();label(ctx,'WORK PAD',padX,padY+42,C.muted,9);if(st!=='READY'){const phase=state.padState/4;const wx=lerp(w*.25,padX-18,clamp(phase*1.8,0,1));drawWorker(ctx,wx,padY-28,13,C.blue,st==='ACTIVE'?'BUILD':st,.8,t)}if(st==='READY'||st==='CLAIMED'){ctx.strokeStyle=hexAlpha(C.blue,.7);ctx.setLineDash([5,4]);ctx.strokeRect(padX-23,padY-62,46,36);ctx.setLineDash([])}if(st==='ACTIVE'||st==='SUBMIT'||st==='ACCEPTED')isoBlock(ctx,padX+18,padY-8,22,18,st==='ACCEPTED'?C.brown:C.ochre,st==='ACTIVE'?.6:1,77);if(st==='SUBMIT'){const px=padX+70+Math.sin(t*.005)*25;isoBlock(ctx,px,padY-12,10,6,C.ochre,1,99)}}
function roadNodes(w,h){return[{x:w*.15,y:h*.7},{x:w*.42,y:h*.35},{x:w*.68,y:h*.62},{x:w*.86,y:h*.28}]}
function drawRoads(ctx,w,h,t){clear(ctx,w,h);const n=roadNodes(w,h),edges=[[0,1],[1,2],[1,3]];edges.forEach((e,i)=>{const a=n[e[0]],b=n[e[1]];let color='#33271d',width=5,dash=[];if(state.roadMode==='ready'){color='#6f5133';width=6}if(state.roadMode==='blocked'){dash=[8,6];color='#51291f'}if(state.roadMode==='transfer'){color='#5d4831';width=7}line(ctx,a,b,color,width,dash);if(state.roadMode==='transfer'){const q=(t*.00022+i*.25)%1;circle(ctx,lerp(a.x,b.x,q),lerp(a.y,b.y,q),5,C.ochre,C.black)}});n.forEach((p,i)=>{isoBlock(ctx,p.x,p.y,24,20,[C.brown,C.green,C.red,C.blue][i],1,200+i);label(ctx,String.fromCharCode(65+i),p.x,p.y+33,C.ink,9)})}
function drawArtifact(ctx,w,h,t){clear(ctx,w,h);const a={x:w*.18,y:h*.67},b={x:w*.80,y:h*.62};line(ctx,a,b,'#4c3b29',8);isoBlock(ctx,a.x,a.y,28,42,C.brown,1,1);isoBlock(ctx,b.x,b.y,22,20,C.blue,.45,2);const p=(t*.00012)%1;const wx=lerp(a.x,b.x,p),wy=lerp(a.y,b.y,p)-10*Math.sin(p*Math.PI);drawWorker(ctx,wx,wy,12,C.green,'CARRY',.78,t);isoBlock(ctx,wx+18,wy+1,9,5,C.ochre,1,4);label(ctx,p<.1?'PICKUP':p>.9?'DELIVERY':'HANDOFF',w*.5,h*.18,C.muted,10)}
function drawArchitecture(ctx,w,h,t){clear(ctx,w,h);const baseY=h*.72;const items=[['WINDOW',.12],['PILASTER',.30],['SIGN',.48],['TORCH',.67],['ARCH',.84]];items.forEach((it,i)=>{const x=w*it[1];if(it[0]==='WINDOW'){roughRect(ctx,x-26,baseY-70,52,70,'#4a4036',C.line,10);roughRect(ctx,x-15,baseY-57,30,54,'#050403',C.black,11);isoBlock(ctx,x-24,baseY-4,12,4,C.slate,1,2);isoBlock(ctx,x+24,baseY-4,12,4,C.slate,1,3)}else if(it[0]==='PILASTER'){for(let k=0;k<4;k++)isoBlock(ctx,x,baseY-k*27,16,18,C.slate,1,20+k)}else if(it[0]==='SIGN'){isoBlock(ctx,x-32,baseY-5,8,70,C.brown,1,31);isoBlock(ctx,x+32,baseY-5,8,70,C.brown,1,32);roughRect(ctx,x-36,baseY-78,72,38,'#2d251f',C.line,33);label(ctx,'KAIROS',x,baseY-58,C.paper,10)}else if(it[0]==='TORCH'){isoBlock(ctx,x,baseY-8,10,48,C.brown,1,40);drawFlame(ctx,x,baseY-63,1,t)}else{roughRect(ctx,x-32,baseY-72,64,72,'#493c31',C.line,50);ctx.fillStyle=C.bg;ctx.beginPath();ctx.moveTo(x-17,baseY);ctx.lineTo(x-17,baseY-38);ctx.arc(x,baseY-38,17,Math.PI,0);ctx.lineTo(x+17,baseY);ctx.closePath();ctx.fill()}label(ctx,it[0],x,baseY+28,C.muted,8)})}
function drawPanel(ctx,w,h,t){clear(ctx,w,h);const yaw=Number($('#panelYaw').value)*Math.PI/180,zoom=Number($('#panelZoom').value)/100;const health=Math.abs(Math.cos(yaw));let mode=health<.18?'EDGE':health<.42?'COMPRESSED':'SAFE';$('#panelHealth').textContent=mode;$('#panelHealth').className=mode==='SAFE'?'pass':mode==='COMPRESSED'?'warn':'fail';const cx=w*.5,cy=h*.56,pw=260*health*zoom,ph=116*zoom;ctx.save();ctx.translate(cx,cy);ctx.transform(1,0,Math.sin(yaw)*.22,1,0,0);roughRect(ctx,-pw/2,-ph/2,pw,ph,'#30241d','#6a4938',61);roughRect(ctx,-pw*.44,-ph*.37,pw*.88,ph*.74,'#0a0807','#20140f',62);if(mode!=='EDGE'){const sx=mode==='SAFE'?1:clamp(.65/Math.max(health,.01),1,2.1);ctx.save();ctx.scale(sx,1);const digits='12:48';label(ctx,digits,0,-8,C.red,26);if(mode==='SAFE')label(ctx,'HORA',0,-38,C.paper,9);for(let i=0;i<14;i++){const x=-92+i*14;roughRect(ctx,x,28,9,11,i<8?C.ochre:'#251713',C.black,70+i)}ctx.restore()}ctx.restore();label(ctx,'health '+health.toFixed(2)+' · '+mode,w*.5,h*.12,mode==='SAFE'?C.green:mode==='COMPRESSED'?C.ochre:C.red,10)}
function drawFlame(ctx,x,y,p,t){for(let i=0;i<6;i++){const phase=t*.004+i*1.7,side=(i%2?-1:1);ctx.fillStyle=i<2?'#f0b86c':i<4?'#d97138':'#9f3827';ctx.globalAlpha=.55+i*.05;ctx.beginPath();ctx.moveTo(x,y+24*p);ctx.quadraticCurveTo(x+side*(18+i*3)*p,y+(4+Math.sin(phase)*7)*p,x+side*(6+i)*p,y-(25+i*6)*p);ctx.quadraticCurveTo(x-side*12*p,y+2*p,x,y+24*p);ctx.fill()}ctx.globalAlpha=1}
function drawEffects(ctx,w,h,t){clear(ctx,w,h);const fire=Number($('#firePower').value)/100,grain=Number($('#grainPower').value)/100;isoBlock(ctx,w*.5,h*.76,54,65,C.brown,1,3);drawFlame(ctx,w*.5,h*.53,.6+fire*.8,t);for(let i=0;i<Math.floor(grain*180);i++){const x=hash(i,Math.floor(t/80))*w,y=hash(i+9,Math.floor(t/80))*h;ctx.fillStyle=i%2?'rgba(220,190,150,.12)':'rgba(0,0,0,.18)';ctx.fillRect(x,y,1,1)}label(ctx,'solid object → fire → grain',w*.5,h*.14,C.muted,10)}
function polarLayout(nodes,w,h,scenario,t){const cx=w*.5,cy=h*.52;return nodes.map((n,i)=>{if(nodes.length===1)return{x:cx,y:cy};if(scenario==='chain'){const a=-.7+i*.45,r=60+i*35;return{x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r*.55}}if(scenario==='fanin'){if(i===nodes.length-1)return{x:cx,y:cy};const a=-Math.PI+i*TAU/(nodes.length-1),r=Math.min(w,h)*.32;return{x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r*.58}}const ring=i<8?1:i<24?2:3;const count=nodes.length<25?nodes.length:Math.ceil(nodes.length/3);const a=i*TAU/count+(scenario==='mutate'?Math.sin(t*.0002)*.15:0);const r=Math.min(w,h)*(.12+ring*.10);return{x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r*.58}})}
function drawSynthetic(ctx,w,h,t){clear(ctx,w,h);const sc=SCENARIOS[state.scenario],pos=polarLayout(sc.nodes,w,h,state.scenario,t);ctx.strokeStyle='#2d251d';ctx.lineWidth=1;sc.edges.forEach(e=>{const ai=sc.nodes.findIndex(n=>n.id===e[0]),bi=sc.nodes.findIndex(n=>n.id===e[1]);if(ai>=0&&bi>=0)line(ctx,pos[ai],pos[bi],'#443523',2)});pos.forEach((p,i)=>{const r=sc.nodes.length>40?5:sc.nodes.length>20?7:10;circle(ctx,p.x,p.y,r,i===0?C.ochre:[C.blue,C.green,C.red][i%3],C.black);if(sc.nodes.length<25)label(ctx,sc.nodes[i].id,p.x,p.y+r+10,C.muted,7)});circle(ctx,w*.5,h*.52,18,'transparent',C.ochre);label(ctx,'FOCUS',w*.5,h*.52,C.ink,8);const overlaps=countOverlaps(pos,sc.nodes.length>40?8:14);const uiKey=state.scenario+':'+overlaps;if(state.lastScenarioUi!==uiKey){state.lastScenarioUi=uiKey;$('#scenarioStats').innerHTML='<span>nodes <b>'+sc.nodes.length+'</b></span><span>edges <b>'+sc.edges.length+'</b></span><span>overlaps <b class="'+(overlaps?'fail':'pass')+'">'+overlaps+'</b></span><span>layout <b>'+(state.scenario==='hundred'?'clustered':'radial')+'</b></span>';renderManifest(sc)}}
function countOverlaps(pos,min){let n=0;for(let i=0;i<pos.length;i++)for(let j=i+1;j<pos.length;j++){if(Math.hypot(pos[i].x-pos[j].x,pos[i].y-pos[j].y)<min)n++}return n}
function drawExterior(ctx,w,h,t){clear(ctx,w,h);const cx=w*.45,cy=h*.53,r=Math.min(w,h)*.31;ctx.strokeStyle=C.line2;ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(cx,cy,r,r*.52,0,0,TAU);ctx.stroke();label(ctx,'RUN ACTUAL',cx,cy,C.muted,9);const q=(t*.00009)%1;const end={x:w*.88,y:h*.28};line(ctx,{x:cx+r*.72,y:cy-r*.12},end,'#2c241b',3,[6,5]);const p=q<.45?{x:lerp(cx,cx+r*.72,q/.45),y:lerp(cy,cy-r*.12,q/.45)}:{x:lerp(cx+r*.72,end.x,(q-.45)/.55),y:lerp(cy-r*.12,end.y,(q-.45)/.55)};isoBlock(ctx,p.x,p.y,10,6,C.ochre,1,6);roughRect(ctx,w*.78,h*.14,w*.17,h*.25,'#13120f',C.line,8);label(ctx,'PERSISTENTE',w*.865,h*.30,C.green,8);label(ctx,'sólo accepted cruza',w*.5,h*.88,C.muted,9)}

const drawFns={avatars:drawAvatars,blocks:drawBlocks,workpads:drawWorkpads,roads:drawRoads,artifact:drawArtifact,architecture:drawArchitecture,panels:drawPanel,effects:drawEffects,synthetic:drawSynthetic,exterior:drawExterior};
const visible=new Set();const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)visible.add(e.target);else visible.delete(e.target)}),{rootMargin:'100px'});$$('.lab-canvas').forEach(c=>io.observe(c));
function frame(now){if(!state.paused){visible.forEach(canvas=>{const {ctx,w,h}=setupCanvas(canvas);const fn=drawFns[canvas.dataset.lab];if(fn)fn(ctx,w,h,now)})}requestAnimationFrame(frame)}requestAnimationFrame(frame);

function renderTop(){const counts={};Object.values(SYSTEMS).forEach(s=>counts[s.status]=(counts[s.status]||0)+1);const totalChecks=Object.values(SYSTEMS).reduce((n,s)=>n+s.tests.length,0),passed=Object.values(state.testMarks).filter(Boolean).length;$('#topmeta').innerHTML='<span class="metric"><b>LAB '+VERSION+'</b></span><span class="metric">CANON <b>'+(counts.CANON||0)+'</b></span><span class="metric">PROTOTYPE <b>'+(counts.PROTOTYPE||0)+'</b></span><span class="metric">FIX <b>'+(counts['NEEDS FIX']||0)+'</b></span><span class="metric">CHECKS <b>'+passed+'/'+totalChecks+'</b></span>';$('#buildStamp').textContent='build '+BUILD}
function chip(status){return '<span class="status-chip status-'+status.replaceAll(' ','-')+'">'+status+'</span>'}
function renderGaps(){const root=$('#gapMap');root.innerHTML=Object.entries(SYSTEMS).filter(([k])=>!['gaps','rules'].includes(k)).map(([id,s])=>'<div class="gap-row" data-gap="'+id+'"><strong>'+s.title+'</strong>'+chip(s.status)+'<p>'+s.missing+'</p><button data-inspect="'+id+'">abrir</button></div>').join('');bindInspect(root)}
function renderRules(){$('#rulesBoard').innerHTML=RULES.map((r,i)=>'<div class="rule"><span class="rule-num">'+String(i+1).padStart(2,'0')+'</span><div><b>'+r[0]+'</b><p>'+r[1]+'</p></div></div>').join('')}
function renderAvatarLegend(){$('#avatarLegend').innerHTML=['IDLE','TAKE','WALK','DESIGN','BUILD','VERIFY','CARRY','STALE'].map(s=>'<span>'+s+'</span>').join('')}
function renderScenarioBar(){$('#scenarioBar').innerHTML=Object.entries(SCENARIOS).map(([id,s])=>'<button data-scenario="'+id+'" class="'+(id===state.scenario?'active':'')+'">'+s.label+'</button>').join('');$$('[data-scenario]').forEach(b=>b.onclick=()=>{state.scenario=b.dataset.scenario;renderScenarioBar()})}
function renderManifest(sc=SCENARIOS[state.scenario]){const nodes=sc.nodes.slice(0,24).map((n,i)=>({id:n.id,state:i%3===0?'ACTIVE':i%3===1?'INTENT':'ACCEPTED'}));const manifest={schema:'prometeo.world_manifest/demo-v1',focus:{node_id:nodes[0]?.id||null},nodes,edges:sc.edges.slice(0,32).map(([from,to])=>({from,to,type:'dependency'})),agents:[{id:'worker-01',state:'WORKING',node_id:nodes[0]?.id||null}],artifacts:[],events:[],metrics:{fixture:state.scenario,total_nodes:sc.nodes.length,total_edges:sc.edges.length}};$('#manifestPreview').textContent=JSON.stringify(manifest,null,2)}
function bindInspect(root=document){$$('[data-inspect]',root).forEach(b=>b.onclick=()=>openInspector(b.dataset.inspect))}
function openInspector(id){const s=SYSTEMS[id];if(!s)return;state.selected=id;$('#inspectorTitle').textContent=s.title;$('#inspectorStatus').innerHTML=chip(s.status);$('#inspectorSummary').textContent=s.summary;$('#inspectorFacts').innerHTML='<div><dt>grupo</dt><dd>'+s.group+'</dd></div><div><dt>trigger</dt><dd>'+s.trigger+'</dd></div><div><dt>visual</dt><dd>'+s.representation+'</dd></div><div><dt>falta</dt><dd>'+s.missing+'</dd></div>';$('#inspectorTests').innerHTML='<span class="eyebrow">acceptance tests</span><div class="test-list">'+s.tests.map((t,i)=>{const key=id+':'+i,on=!!state.testMarks[key];return '<div class="test-row"><span>'+t+'</span><button class="test-toggle '+(on?'pass':'warn')+'" data-test-key="'+key+'">'+(on?'PASS':'PENDIENTE')+'</button></div>'}).join('')+'</div>';$('[data-test-key]',$('#inspectorTests')).forEach(b=>b.onclick=()=>{const k=b.dataset.testKey;state.testMarks[k]=!state.testMarks[k];localStorage.setItem('worldlab.tests',JSON.stringify(state.testMarks));openInspector(id);renderTop()});$('#inspectorNotes').value=state.notes[id]||'';$('#inspector').classList.add('open');if(innerWidth<721)$('#inspector').scrollIntoView({behavior:'smooth'})}

function runCameraTests(){const yaws=[0,.35,-.35,.70,-.70,1.05,-1.05,1.40,-1.40],zooms=[.55,1,1.8];const rows=[];for(const y of yaws)for(const z of zooms){const health=Math.abs(Math.cos(y));const content=health>.12;const frame=true;const mirror=false;const collapse=false;const overlap=z>1.7&&Math.abs(y)<.2?'WARN':'PASS';rows.push({y,z,frame,content,mirror,collapse,overlap})}state.testResults=rows;$('#cameraMatrix tbody').innerHTML=rows.map(r=>'<tr><td>'+r.y.toFixed(2)+'</td><td>'+r.z.toFixed(2)+'</td><td class="pass">PASS</td><td class="'+(r.content?'pass':'warn')+'">'+(r.content?'VISIBLE':'HIDDEN')+'</td><td class="pass">NO</td><td class="pass">NO</td><td class="'+(r.overlap==='PASS'?'pass':'warn')+'">'+r.overlap+'</td></tr>').join('');return rows}
function applyFilters(){const q=$('#search').value.trim().toLowerCase(),status=$('#statusFilter').value;$$('[data-system]').forEach(card=>{const id=card.dataset.system,s=SYSTEMS[id];const text=(s.title+' '+s.group+' '+s.summary+' '+s.missing).toLowerCase();card.hidden=!((!q||text.includes(q))&&(status==='ALL'||s.status===status))})}
function exportSnapshot(){const snapshot={schema:'prometeo.world_lab/snapshot-v1',version:VERSION,created_at:new Date().toISOString(),systems:SYSTEMS,notes:state.notes,scenario:state.scenario,camera_tests:state.testResults,rules:RULES.map((r,i)=>({id:i+1,name:r[0],rule:r[1]}))};const blob=new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='world-lab-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}

$('#search').addEventListener('input',applyFilters);$('#statusFilter').addEventListener('change',applyFilters);
$('#pauseBtn').onclick=()=>{state.paused=!state.paused;$('#pauseBtn').textContent=state.paused?'reanudar':'pausar'};
$('#runTestsBtn').onclick=()=>{runCameraTests();$('#cameraMatrix').scrollIntoView({behavior:'smooth',block:'center'})};
$('#exportBtn').onclick=exportSnapshot;$('#closeInspector').onclick=()=>$('#inspector').classList.remove('open');
$('#saveNotes').onclick=()=>{if(!state.selected)return;state.notes[state.selected]=$('#inspectorNotes').value;localStorage.setItem('worldlab.notes',JSON.stringify(state.notes));$('#saveNotes').textContent='guardado';setTimeout(()=>$('#saveNotes').textContent='guardar nota',900)};
$('#resetNotes').onclick=()=>{$('#inspectorNotes').value='';if(state.selected){delete state.notes[state.selected];localStorage.setItem('worldlab.notes',JSON.stringify(state.notes))}};
$('#padPrev').onclick=()=>{state.padState=(state.padState+PAD_STATES.length-1)%PAD_STATES.length;$('#padStateLabel').textContent=PAD_STATES[state.padState]};
$('#padNext').onclick=()=>{state.padState=(state.padState+1)%PAD_STATES.length;$('#padStateLabel').textContent=PAD_STATES[state.padState]};
$$('[data-road]').forEach(b=>b.onclick=()=>{state.roadMode=b.dataset.road;$$('[data-road]').forEach(x=>x.classList.toggle('active',x===b))});

renderTop();renderGaps();renderRules();renderAvatarLegend();renderScenarioBar();renderManifest();runCameraTests();bindInspect();openInspector('panels');
})();