import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!, ANON_KEY=Deno.env.get("SUPABASE_ANON_KEY")!, SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false}});
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Cache-Control":"no-store"};
const json=(x:any,status=200)=>new Response(JSON.stringify(x),{status,headers:{...CORS,"Content-Type":"application/json"}}); const now=()=>new Date().toISOString();
async function owner(req:Request){const auth=req.headers.get("Authorization")||"";if(!auth.startsWith("Bearer "))throw new Error("AUTH_REQUIRED");const c=createClient(SUPABASE_URL,ANON_KEY,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const {data,error}=await c.auth.getUser();if(error||!data.user)throw new Error("AUTH_INVALID");const {data:o,error:oe}=await db.from("prometeo_owner").select("auth_user_id").eq("singleton",true).maybeSingle();if(oe||!o||o.auth_user_id!==data.user.id)throw new Error("NOT_OWNER");return data.user.id}
async function conn(ownerId:string,kind:string){const {data,error}=await db.from("creator_provider_connections").select("*").eq("owner_id",ownerId).eq("kind",kind).eq("provider","google").eq("connection_key","default").maybeSingle();if(error)throw error;return data}
async function secret(id:string|null){if(!id)throw new Error("SECRET_MISSING");const {data,error}=await db.rpc("creator_vault_read",{p_secret_id:id});if(error||!data)throw error||new Error("SECRET_MISSING");return String(data)}
async function logEvent(ownerId:string,status:string,details:any={}){try{await db.from("creator_detection_events").insert({owner_id:ownerId,provider:"youtube",status,details})}catch{}}
async function linkOne(ownerId:string,ytConn:any,y:any){const {data:already}=await db.from("creator_channels").select("*").eq("owner_id",ownerId).eq("youtube_channel_id",y.id).maybeSingle();if(already)return already;const {data:unmatched,error}=await db.from("creator_channels").select("*").eq("owner_id",ownerId).is("youtube_channel_id",null).neq("status","ARCHIVED");if(error)throw error;if((unmatched||[]).length!==1)return null;const {data:u,error:ue}=await db.from("creator_channels").update({youtube_channel_id:y.id,youtube_connection_id:ytConn?.id||null,updated_at:now()}).eq("id",unmatched![0].id).select().single();if(ue)throw ue;return u}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(req.method!=="POST")return json({ok:false,error:"METHOD_NOT_ALLOWED"},405);try{const ownerId=await owner(req);let b:any={};try{b=await req.json()}catch{};const oauth=await conn(ownerId,"oauth"),client=await conn(ownerId,"oauth_client"),yt=await conn(ownerId,"youtube");if(!oauth?.vault_secret_id||!client?.vault_secret_id||!client?.metadata?.client_id)return json({ok:false,error:"GOOGLE_NOT_CONNECTED",reauthorize:true},409);const refreshToken=await secret(oauth.vault_secret_id),clientSecret=await secret(client.vault_secret_id);const tr=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:String(client.metadata.client_id),client_secret:clientSecret,refresh_token:refreshToken,grant_type:"refresh_token"}),signal:AbortSignal.timeout(20000)});const tp:any=await tr.json().catch(()=>({}));if(!tr.ok||!tp.access_token){await logEvent(ownerId,"TOKEN_REFRESH_FAILED",{status:tr.status,error:tp?.error||null});return json({ok:false,error:"GOOGLE_SESSION_NEEDS_REAUTH",reauthorize:true,detail:tp?.error_description||tp?.error||null},409)}const cr=await fetch("https://www.googleapis.com/youtube/v3/channels?part=id,snippet&mine=true&maxResults=50",{headers:{Authorization:`Bearer ${tp.access_token}`},signal:AbortSignal.timeout(20000)});const cp:any=await cr.json().catch(()=>({}));if(!cr.ok){await logEvent(ownerId,"CHANNELS_LIST_FAILED",{status:cr.status,error:cp?.error?.message||null});return json({ok:false,error:"YOUTUBE_CHANNEL_CHECK_FAILED",detail:cp?.error?.message||null},502)}const channels=(cp.items||[]).map((x:any)=>({id:String(x.id||""),title:String(x.snippet?.title||"YouTube"),custom_url:x.snippet?.customUrl||null,published_at:x.snippet?.publishedAt||null})).filter((x:any)=>x.id);let ytConn=yt;if(yt){const {data,error}=await db.from("creator_provider_connections").update({mode:channels.length?"VERIFIED_REAL":"CONFIGURED",verified_at:channels.length?now():yt.verified_at,last_probe:{ok:true,checked_at:now(),channel_count:channels.length},last_error:null,metadata:{...(yt.metadata||{}),channels,read_verified:true,last_detected_at:now()},external_account_id:channels.length===1?channels[0].id:yt.external_account_id,updated_at:now()}).eq("id",yt.id).select().single();if(error)throw error;ytConn=data}
let linked:any=null,needs_choice=false;const requested=String(b.youtube_channel_id||"").trim();if(requested){const chosen=channels.find((x:any)=>x.id===requested);if(!chosen)return json({ok:false,error:"CHANNEL_NOT_IN_ACCOUNT"},409);linked=await linkOne(ownerId,ytConn,chosen);if(!linked)return json({ok:false,error:"INTERNAL_CHANNEL_AMBIGUOUS"},409)}else if(channels.length===1){linked=await linkOne(ownerId,ytConn,channels[0]);needs_choice=!linked}else if(channels.length>1)needs_choice=true;await logEvent(ownerId,channels.length?"CHANNELS_FOUND":"NO_CHANNELS",{channel_count:channels.length,linked_channel_id:linked?.id||null});return json({ok:true,channels,linked,needs_choice,channel_count:channels.length});}catch(e){const m=String((e as any)?.message||e);return json({ok:false,error:m},m.startsWith("AUTH_")||m==="NOT_OWNER"?401:500)}});