/* Prometeo Student World Engine v1.1 — topology/progress only; visuals remain external. */
((global)=>{'use strict';if(global.PrometeoStudentWorld)return;const clone=v=>structuredClone(v),now=()=>new Date().toISOString();
function normalize(input){if(!input?.id)throw new Error('World id required');const nodes=(input.nodes||[]).map((n,i)=>({...n,id:n.id||`node-${i+1}`,kind:n.kind||'topic',requires:[...(n.requires||[])]}));const ids=new Set();for(const n of nodes){if(ids.has(n.id))throw new Error(`Duplicate world node ${n.id}`);ids.add(n.id);}nodes.forEach(n=>n.requires.forEach(r=>{if(!ids.has(r))throw new Error(`Unknown prerequisite ${r} for ${n.id}`);}));const byId=new Map(nodes.map(n=>[n.id,n])),visiting=new Set(),done=new Set();function visit(id){if(done.has(id))return;if(visiting.has(id))throw new Error(`Prerequisite cycle at ${id}`);visiting.add(id);for(const r of byId.get(id)?.requires||[])visit(r);visiting.delete(id);done.add(id);}nodes.forEach(n=>visit(n.id));const{nodes:_ignored,...rest}=input;return Object.freeze({...rest,nodes});}
function initial(config,seed={}){const incoming=seed.status||{},status={};config.nodes.forEach(n=>status[n.id]={state:n.requires.length?'LOCKED':'AVAILABLE',progress:0,visits:0,updatedAt:null,...clone(incoming[n.id]||{})});const fallback=config.nodes.find(n=>status[n.id]?.state!=='LOCKED')?.id||null;const currentNodeId=status[seed.currentNodeId]?seed.currentNodeId:fallback;const s={schema:'prometeo.student-world-state/v1',worldId:config.id,studentId:seed.studentId||config.studentId||null,currentNodeId,status,events:Array.isArray(seed.events)?clone(seed.events):[],updatedAt:seed.updatedAt||null};reconcile(config,s);return s;}
function reconcile(config,state){for(const n of config.nodes){const s=state.status[n.id];if(!s||s.state==='DONE')continue;const ready=n.requires.every(r=>state.status[r]?.state==='DONE');if(ready&&s.state==='LOCKED')s.state='AVAILABLE';if(!ready&&s.state==='AVAILABLE'&&n.requires.length)s.state='LOCKED';}}
function event(state,type,payload={}){state.updatedAt=now();state.events.push({seq:state.events.length+1,type,at:state.updatedAt,...clone(payload)});}
function reduce(config,state,action){const next=clone(state),id=action.nodeId||next.currentNodeId,s=next.status[id];switch(action.type){case'ENTER':if(!s)throw new Error('Node not found');if(s.state==='LOCKED')throw new Error('Node locked');next.currentNodeId=id;s.visits=(s.visits||0)+1;s.updatedAt=now();event(next,'WORLD_NODE_ENTERED',{nodeId:id});break;case'PROGRESS':if(!s)throw new Error('Node not found');if(s.state==='LOCKED')throw new Error('Node locked');s.progress=Math.max(0,Math.min(1,Number(action.progress)||0));s.updatedAt=now();event(next,'WORLD_NODE_PROGRESS',{nodeId:id,progress:s.progress});break;case'COMPLETE':if(!s)throw new Error('Node not found');if(s.state==='LOCKED')throw new Error('Node locked');s.progress=1;s.state='DONE';s.updatedAt=now();event(next,'WORLD_NODE_COMPLETED',{nodeId:id});reconcile(config,next);break;case'RESTORE_VIEW':if(action.nodeId&&!next.status[action.nodeId])throw new Error('Node not found');next.currentNodeId=action.nodeId||next.currentNodeId;event(next,'WORLD_VIEW_RESTORED',{nodeId:next.currentNodeId});break;default:throw new Error(`Unknown world action ${action.type}`);}return next;}
function create(configInput,seed={}){const config=normalize(configInput);let state=initial(config,seed);const listeners=new Set();return Object.freeze({config,getState:()=>clone(state),dispatch:a=>{state=reduce(config,state,a);listeners.forEach(fn=>fn(clone(state),a));return clone(state);},subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn);}});}
global.PrometeoStudentWorld=Object.freeze({version:'1.1.0-candidate',create,normalize,initial,reduce});})(typeof globalThis!=='undefined'?globalThis:window);
