const CACHE='casa-v6-retro';
const APP_SHELL=['./','./index.html','./style.css','./app.js','./manifest.webmanifest','./icon.svg'];
const DB_NAME='casa-push',STORE='pending';
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(APP_SHELL)).catch(()=>{}))});
self.addEventListener('activate',e=>{e.waitUntil(Promise.all([self.clients.claim(),caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k))))]))});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==self.location.origin)return;if(e.request.mode==='navigate'){e.respondWith(fetch(e.request).then(r=>{const x=r.clone();caches.open(CACHE).then(c=>c.put('./index.html',x)).catch(()=>{});return r}).catch(()=>caches.match('./index.html').then(r=>r||caches.match('./'))));return}e.respondWith(caches.match(e.request).then(c=>c||fetch(e.request).then(r=>{if(r.ok)caches.open(CACHE).then(x=>x.put(e.request,r.clone())).catch(()=>{});return r})))});
function openDb(){return new Promise((a,b)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'messageId'})};r.onsuccess=()=>a(r.result);r.onerror=()=>b(r.error)})}
async function save(data){const db=await openDb();return new Promise((a,b)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(data);t.oncomplete=a;t.onerror=()=>b(t.error)})}
self.addEventListener('push',e=>{let d={};try{d=e.data?.json()||{}}catch{try{d=JSON.parse(e.data?.text()||'{}')}catch{}}if(d.type!=='casa-message')return;e.waitUntil((async()=>{try{await save(d)}catch{}try{await self.registration.setAppBadge?.()}catch{}const i=new URL('./icon.svg',self.registration.scope).href;await self.registration.showNotification(`CASA // ${String(d.name||'MENSAJE').toUpperCase()}`,{body:d.text||'Nueva transmisión',icon:i,badge:i,tag:`casa-${d.messageId||Date.now()}`,renotify:true,silent:false,vibrate:[120,70,120],data:d})})())});
self.addEventListener('notificationclick',e=>{e.notification.close();const d=e.notification.data||{};e.waitUntil((async()=>{const w=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const c of w){if('focus'in c){await c.focus();c.postMessage({type:'casa-push-open',payload:d});return}}if(self.clients.openWindow){const c=await self.clients.openWindow('./');setTimeout(()=>c?.postMessage?.({type:'casa-push-open',payload:d}),500)}})())});