import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import { getHfZeroGpuToken,hfHeaders } from "../_shared/creator_hf_zerogpu.ts";

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')!;
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false}});
const SPACE='https://lightricks-ltx-2-5.hf.space';
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Cache-Control":"no-store"};
const json=(x:any,status=200)=>new Response(JSON.stringify(x),{status,headers:{...CORS,'Content-Type':'application/json'}});
const fail=(error:string,status=400,extra:any={})=>json({ok:false,error,...extra},status);

async function owner(req:Request){const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))throw new Error('AUTH_REQUIRED');const c=createClient(SUPABASE_URL,ANON_KEY,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const {data,error}=await c.auth.getUser();if(error||!data.user)throw new Error('AUTH_INVALID');const {data:o,error:oe}=await db.from('prometeo_owner').select('auth_user_id').eq('singleton',true).maybeSingle();if(oe||!o||o.auth_user_id!==data.user.id)throw new Error('NOT_OWNER');return data.user.id}
async function logProbe(ownerId:string,modality:'video'|'image_to_video',status:'PASS'|'CAPACITY'|'FAILED',detail:any){try{await db.from('creator_media_probe_log').insert({owner_id:ownerId,provider:'ltx25_zerogpu',modality,status,detail});}catch{}}
async function sha256(bytes:Uint8Array){const d=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function hasAtom(bytes:Uint8Array,name:string){const n=new TextEncoder().encode(name);outer:for(let i=0;i<=bytes.length-n.length;i++){for(let j=0;j<n.length;j++)if(bytes[i+j]!==n[j])continue outer;return true}return false}
function parseCompleted(s:string){
  if(/event:\s*error/i.test(s)){let detail='ZEROGPU_SPACE_ERROR';try{const m=s.match(/data:\s*(\{[\s\S]*\})\s*$/m);if(m){const p=JSON.parse(m[1]);detail=String(p.error||p.title||detail)}}catch{}throw new Error(detail)}
  const m=s.match(/event:\s*complete\s*\ndata:\s*(\[[\s\S]*\])\s*$/m)||s.match(/data:\s*(\[[\s\S]*\])\s*$/m);if(!m)throw new Error('ZEROGPU_RESULT_MISSING');const p=JSON.parse(m[1]),file=p?.[0],url=file?.url||file?.path;if(!url)throw new Error('ZEROGPU_VIDEO_URL_MISSING');return{url:String(url),enhancedPrompt:String(p?.[1]||''),seed:p?.[2]??null,length:String(p?.[3]||'')};
}
async function generate(prompt:string,duration=1,width=576,height=1024,inputImageUrl:string|null=null,token=''){
  duration=Math.max(1,Math.min(5,Number(duration||1)));width=Math.max(512,Math.min(1536,Math.round(width/64)*64));height=Math.max(512,Math.min(1536,Math.round(height/64)*64));
  const image=inputImageUrl?{url:inputImageUrl,path:inputImageUrl,orig_name:'input-image',meta:{_type:'gradio.FileData'}}:null;
  const data=[prompt,image,height,width,duration,42,'conv',false,true,false];
  const start=await fetch(`${SPACE}/gradio_api/call/run`,{method:'POST',signal:AbortSignal.timeout(15000),headers:hfHeaders(token,{'Content-Type':'application/json'}),body:JSON.stringify({data})});const first:any=await start.json().catch(()=>({}));if(!start.ok||!first.event_id)throw new Error(`ZEROGPU_SUBMIT_${start.status}`);
  const poll=await fetch(`${SPACE}/gradio_api/call/run/${encodeURIComponent(first.event_id)}`,{signal:AbortSignal.timeout(240000),headers:hfHeaders(token,{Accept:'text/event-stream'})});const text=await poll.text();if(!poll.ok)throw new Error(`ZEROGPU_POLL_${poll.status}`);const done=parseCompleted(text),fileUrl=done.url.startsWith('http')?done.url:`${SPACE}${done.url.startsWith('/')?'':'/'}${done.url}`;
  const vr=await fetch(fileUrl,{signal:AbortSignal.timeout(60000),headers:hfHeaders(token)});if(!vr.ok)throw new Error(`ZEROGPU_FETCH_${vr.status}`);const bytes=new Uint8Array(await vr.arrayBuffer());if(bytes.byteLength<3000)throw new Error('ZEROGPU_VIDEO_TOO_SMALL');if(!hasAtom(bytes,'ftyp')||!hasAtom(bytes,'moov')||!hasAtom(bytes,'mdat'))throw new Error('ZEROGPU_MP4_INVALID');return{bytes,event_id:first.event_id,duration,width,height,mode:inputImageUrl?'image-to-video':'text-to-video',enhancedPrompt:done.enhancedPrompt,seed:done.seed,length:done.length};
}

Deno.serve(async(req:Request)=>{
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});if(req.method!=='POST')return fail('METHOD_NOT_ALLOWED',405);let ownerId='',modality:'video'|'image_to_video'='video';
  try{
    ownerId=await owner(req);const b:any=await req.json().catch(()=>({})),prompt=String(b.prompt||'').trim();if(!prompt)return fail('PROMPT_REQUIRED');const videoId=String(b.video_id||'');if(!videoId)return fail('VIDEO_ID_REQUIRED');modality=b.image_asset_id?'image_to_video':'video';
    const {data:v,error:ve}=await db.from('creator_videos').select('id,channel_id,metadata,max_cost_cents').eq('id',videoId).eq('owner_id',ownerId).maybeSingle();if(ve||!v)return fail('VIDEO_NOT_FOUND',404);const {data:policy}=await db.from('creator_cost_policy').select('mode,hard_max_cost_cents').eq('owner_id',ownerId).maybeSingle();if(policy?.mode!=='FREE_ONLY'||Number(policy?.hard_max_cost_cents||0)!==0||Number(v.max_cost_cents||0)!==0)return fail('FREE_ONLY_REQUIRED',409);
    let imageAsset:any=null,inputImageUrl:string|null=null;if(b.image_asset_id){const {data:a,error}=await db.from('creator_assets').select('id,channel_id,bucket,object_path').eq('id',String(b.image_asset_id)).eq('owner_id',ownerId).eq('kind','IMAGE').maybeSingle();if(error||!a)return fail('IMAGE_ASSET_NOT_FOUND',404);if(a.channel_id&&a.channel_id!==v.channel_id)return fail('IMAGE_CHANNEL_MISMATCH',409);const {data:s,error:se}=await db.storage.from(a.bucket||'creator-assets').createSignedUrl(a.object_path,1800);if(se||!s?.signedUrl)throw se||new Error('IMAGE_SIGN_FAILED');imageAsset=a;inputImageUrl=s.signedUrl}
    const token=await getHfZeroGpuToken(db,ownerId),out=await generate(prompt,Number(b.duration||1),Number(b.width||576),Number(b.height||1024),inputImageUrl,token),quota=token?'authenticated_zerogpu':'anonymous_zerogpu',path=`${ownerId}/${v.channel_id}/${videoId}/${crypto.randomUUID()}-ltx25-zerogpu-master.mp4`;
    const up=await db.storage.from('creator-assets').upload(path,out.bytes,{contentType:'video/mp4',upsert:false,cacheControl:'3600'});if(up.error)throw up.error;const digest=await sha256(out.bytes);
    const {data:asset,error:ae}=await db.from('creator_assets').insert({owner_id:ownerId,channel_id:v.channel_id,video_id:videoId,kind:'MASTER',bucket:'creator-assets',object_path:path,mime_type:'video/mp4',byte_size:out.bytes.byteLength,duration_ms:Math.round(out.duration*1000),sha256:digest,provider:'huggingface-ltx25-zerogpu',provider_asset_id:out.event_id,metadata:{prompt,enhanced_prompt:out.enhancedPrompt,space:'Lightricks/LTX-2.5',model:'LTX-2.5-Diffusers distilled',mode:out.mode,parent_image_asset_id:imageAsset?.id||null,seed:out.seed,length:out.length,width:out.width,height:out.height,has_audio:true,cost_cents:0,quota,free_only:true}}).select().single();if(ae)throw ae;
    const {data:maxv,error:mve}=await db.from('creator_video_versions').select('version').eq('owner_id',ownerId).eq('video_id',videoId).order('version',{ascending:false}).limit(1).maybeSingle();if(mve)throw mve;const version=Number(maxv?.version||0)+1;const des=await db.from('creator_video_versions').update({selected:false}).eq('owner_id',ownerId).eq('video_id',videoId);if(des.error)throw des.error;
    const {data:vv,error:vve}=await db.from('creator_video_versions').insert({owner_id:ownerId,video_id:videoId,version,master_asset_id:asset.id,scene_manifest:[{kind:'generated_master',provider:'huggingface-ltx25-zerogpu',mode:out.mode,parent_image_asset_id:imageAsset?.id||null,duration_ms:Math.round(out.duration*1000),width:out.width,height:out.height,has_audio:true}],selected:true}).select().single();if(vve)throw vve;
    const findings=['mp4 atoms ftyp/moov/mdat present',`${out.width}x${out.height}`,`duration target ${out.duration}s`,out.mode,'LTX-2.5 audio/video output'];const qa=await db.from('creator_validation_runs').insert({owner_id:ownerId,video_id:videoId,video_version_id:vv.id,kind:'DETERMINISTIC',status:'PASS',score:1,findings,evidence:{provider:'huggingface-ltx25-zerogpu',mode:out.mode,parent_image_asset_id:imageAsset?.id||null,byte_size:out.bytes.byteLength,width:out.width,height:out.height,duration_ms:Math.round(out.duration*1000),cost_cents:0}});if(qa.error)throw qa.error;
    const metadata={...(v.metadata||{}),last_master_asset_id:asset.id,last_master_provider:'huggingface-ltx25-zerogpu',last_video_provider:'huggingface-ltx25-zerogpu',last_video_mode:out.mode,parent_image_asset_id:imageAsset?.id||null,free_only:true};const upd=await db.from('creator_videos').update({state:'READY',target_duration_ms:Math.round(out.duration*1000),actual_cost_cents:0,max_cost_cents:0,metadata}).eq('id',videoId).eq('owner_id',ownerId);if(upd.error)throw upd.error;
    const {data:signed,error:se}=await db.storage.from('creator-assets').createSignedUrl(path,3600);if(se)throw se;await logProbe(ownerId,modality,'PASS',{event_id:out.event_id,bytes:out.bytes.byteLength,cost_cents:0,authenticated:!!token,has_audio:true});return json({ok:true,provider:'huggingface-ltx25-zerogpu',mode:out.mode,cost_cents:0,video_id:videoId,video_version_id:vv.id,parent_image_asset_id:imageAsset?.id||null,asset:{id:asset.id,mime_type:'video/mp4',byte_size:out.bytes.byteLength,duration_ms:Math.round(out.duration*1000)},signed_url:signed.signedUrl,qa:{status:'PASS',findings},quota:token?'authenticated ZeroGPU':'anonymous ZeroGPU'});
  }catch(e){const m=String((e as any)?.message||e);console.error('creator-free-video-ltx25',m);const auth=/^(AUTH_|NOT_OWNER)/.test(m),capacity=/quota|GPU token|ZeroGPU|runs limit|capacity|ZEROGPU_POLL_429|ZEROGPU_SUBMIT_429/i.test(m);if(ownerId)await logProbe(ownerId,modality,capacity?'CAPACITY':'FAILED',{detail:m,cost_cents:0});return fail(capacity?'ZEROGPU_ANON_UNAVAILABLE':m,auth?401:capacity?429:500,{detail:m});}
});
