const API='https://catnohyouxqjjtseaueb.supabase.co/functions/v1/modelos-room-audio-v2';
const VOICE={id:'julian',prompt:'Argentine male teacher. Warm medium-low voice, clear and patient. Natural Rioplatense Spanish. Explain as if to one student, with brief useful pauses. Same speaker throughout.'};
const READER_SCHEMA='prometeo.reader-payload/v1';
const TTS_SCHEMA='prometeo.tts-chunk-set/v1';
const CHUNKER={id:'reader-sentence-pack',version:'1',max_chars:500,include_kinds:['heading','paragraph','list_item','quote','caption']};
const CONFIG={profile:'document-default',whitespace:'blocks-v1'};
const DOCS=[
 {slug:'mapa-modelos',title:'Mapa para comparar modelos teóricos',subtitle:'Apunte sintético · lectura breve',sections:[
  ['1. Qué compara un modelo',['Un modelo teórico organiza preguntas, conceptos y relaciones. No es solamente una lista de autores: propone una manera de decidir qué aspectos de una situación conviene mirar primero.','Para estudiar dos modelos sin mezclarlos sirve comparar siempre las mismas dimensiones: qué problema intentan explicar, qué conceptos usan, cómo entienden el cambio y qué tipo de evidencia consideran relevante.']],
  ['2. Evitar el resumen plano',['Un resumen plano repite definiciones una detrás de otra. Una comparación útil muestra diferencias de estructura. Dos modelos pueden usar palabras parecidas y, sin embargo, asignarles funciones distintas dentro de su explicación.','Por eso conviene formular una pregunta de contraste después de cada apartado: si este modelo observara el mismo caso que otro modelo, ¿qué describiría de manera diferente?']],
  ['3. Preparar una respuesta de parcial',['Una respuesta clara puede empezar con la idea central del modelo, seguir con dos conceptos vinculados y terminar con una comparación concreta. Esa secuencia evita enumerar datos sin mostrar comprensión.','En el examen, la comparación funciona mejor cuando cada diferencia está anclada en una consecuencia: cambia lo que se observa, cambia la explicación o cambia la intervención que tendría sentido proponer.']]
 ]},
 {slug:'leer-un-caso',title:'Cómo leer un caso sin perder el modelo',subtitle:'Guía sintética · aplicación conceptual',sections:[
  ['1. Separar datos de interpretación',['El caso ofrece datos y el modelo ofrece una forma de organizarlos. Antes de interpretar conviene identificar qué ocurrió, quiénes participaron y qué secuencia puede reconstruirse sin agregar explicaciones todavía.','Después aparece la lectura teórica. El objetivo no es insertar palabras técnicas en cualquier lugar, sino elegir conceptos que realmente permitan ordenar los datos del caso.']],
  ['2. Buscar relaciones, no etiquetas',['Una etiqueta aislada suele decir poco. Una relación muestra cómo un concepto se conecta con otro y qué cambio permite explicar. Esa conexión es lo que vuelve visible que estamos usando un modelo y no sólo vocabulario.','Si una afirmación podría pertenecer a cualquier teoría, probablemente falta especificidad. La pregunta útil es qué afirmación sería difícil de sostener sin ese modelo particular.']],
  ['3. Cerrar con una hipótesis limitada',['Una hipótesis de lectura no necesita presentarse como verdad definitiva. Puede formularse como una interpretación compatible con los datos disponibles y señalar qué información faltaría para sostenerla mejor.','Esa forma de cierre mantiene separados el material del caso y la inferencia teórica, algo especialmente útil cuando dos modelos producen lecturas distintas sobre la misma situación.']]
 ]},
 {slug:'respuesta-parcial',title:'Estructura de una respuesta desarrollada',subtitle:'Plantilla sintética · parcial escrito',sections:[
  ['1. Abrir con una tesis',['La primera oración debería responder la pregunta en vez de repetirla. Una tesis breve ubica desde qué modelo se responde y cuál es la relación principal que se va a desarrollar.','Esa tesis funciona como criterio de selección: si un dato no ayuda a sostenerla, probablemente no necesita ocupar espacio en la respuesta.']],
  ['2. Desarrollar con mecanismo y ejemplo',['El desarrollo mejora cuando cada concepto explica algo. Una secuencia simple es concepto, relación, mecanismo y ejemplo. El ejemplo no reemplaza la teoría: muestra cómo opera la relación que acabamos de describir.','Cuando hay dos autores o modelos, conviene terminar el párrafo con el contraste explícito. No alcanza con describir uno y después el otro si nunca queda dicha la diferencia relevante.']],
  ['3. Cerrar recuperando la pregunta',['El cierre no necesita introducir información nueva. Puede retomar la tesis y mostrar por qué las relaciones desarrolladas permiten responder exactamente lo que se preguntó.','Una respuesta corta pero organizada suele ser más legible que una acumulación de conceptos. La meta de esta plantilla es hacer visible el razonamiento y no sólo demostrar que se recuerdan términos.']]
 ]}
];
const $=id=>document.getElementById(id);
const E={library:$('libraryView'),reader:$('readerView'),list:$('docList'),back:$('backBtn'),title:$('readerTitle'),subtitle:$('readerSubtitle'),text:$('readerText'),dock:$('audioDock'),play:$('playBtn'),status:$('audioStatus'),count:$('audioCount'),buffer:$('bufferBar'),progress:$('playBar'),identity:$('readerIdentity')};
const state={docs:[],doc:null,index:0,intent:false,playing:false,audio:null,clips:new Map(),fallback:false,fallbackTimer:null};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function stable(v){if(Array.isArray(v))return `[${v.map(stable).join(',')}]`;if(v&&typeof v==='object')return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;return JSON.stringify(v)}
async function sha256(v){const text=typeof v==='string'?v:stable(v),buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function buildCanonical(def){
 const raw=[def.title,...def.sections.flatMap(([h,p])=>[h,...p])].join('\n\n');
 const src=await sha256(raw),configSha=await sha256(CONFIG);let order=0;const sections=[],segments=[];
 def.sections.forEach(([title,paras],i)=>{const sid=`sec-${String(i+1).padStart(2,'0')}`,ids=[];let id=`seg-${String(order+1).padStart(3,'0')}`;ids.push(id);segments.push({segment_id:id,section_id:sid,order:order++,kind:'heading',heading_level:2,text:title,source_locators:[{kind:'page',page:i+1}]});for(const p of paras){id=`seg-${String(order+1).padStart(3,'0')}`;ids.push(id);segments.push({segment_id:id,section_id:sid,order:order++,kind:'paragraph',text:p,source_locators:[{kind:'page',page:i+1}]})}sections.push({section_id:sid,order:i,title,level:2,segment_ids:ids})});
 const sourceVersion=`srcv1:sha256:${src}`;
 const cex=`cex1:sha256:${await sha256({source_version_id:sourceVersion,canonical_schema:'prometeo.canonical-document/v1',extractor_id:'synthetic-academic-fixture',extractor_version:'1.0.0',extractor_config_sha256:configSha})}`;
 const semantic={language:'es-AR',title:def.title,subtitle:def.subtitle,author:'Prometeo · documento de demostración',sections,segments:segments.map(({source_locators,...s})=>s),assets:[]};
 const contentHash=await sha256(semantic);
 return {schema:'prometeo.canonical-document/v1',document_id:`doc1:sha256:${contentHash}`,title:def.title,subtitle:def.subtitle,author:'Prometeo · documento de demostración',course_id:'modelos-teorias-iii-demo',language:'es-AR',source:{source_version_id:sourceVersion,content_sha256:src,hash_basis:'raw_bytes',media_type:'text/plain',byte_length:new TextEncoder().encode(raw).byteLength,provenance:[{provenance_id:`prov:fixture:modelos-iii:${def.slug}:1`,provider:'fixture',runtime_ref:`public-fixture:modelos-iii:${def.slug}`,visibility:'public'}]},extraction:{canonical_extraction_version_id:cex,extractor_id:'synthetic-academic-fixture',extractor_version:'1.0.0',extractor_config_sha256:configSha,canonical_content_sha256:contentHash},sections,segments,assets:[]};
}
async function canonicalToReader(doc){
 const ordered=[...doc.segments].sort((a,b)=>a.order-b.order||a.segment_id.localeCompare(b.segment_id));let cursor=0;
 const segments=ordered.map((s,index)=>{const start=cursor,end=start+s.text.length;cursor=end+(index===ordered.length-1?0:2);return {segment_id:s.segment_id,section_id:s.section_id,order:s.order,kind:s.kind,...(s.heading_level?{heading_level:s.heading_level}:{}),text:s.text,span:{start,end},source_locators:s.source_locators}});
 const readable_text=segments.map(s=>s.text).join('\n\n'),spanById=new Map(segments.map(s=>[s.segment_id,s.span]));
 const paragraphs=segments.filter(s=>s.kind==='paragraph').map((s,i)=>({paragraph_id:`p:${s.segment_id}`,section_id:s.section_id,order:i,segment_ids:[s.segment_id],span:s.span}));
 const sections=[...doc.sections].sort((a,b)=>a.order-b.order||a.section_id.localeCompare(b.section_id)).map(s=>({section_id:s.section_id,order:s.order,...(s.title!=null?{title:s.title}:{}),...(s.level!=null?{level:s.level}:{}),segment_ids:s.segment_ids.filter(id=>spanById.has(id))}));
 const identity={contract:READER_SCHEMA,projector:'canonical-to-reader',projector_version:'1',document_id:doc.document_id,canonical_extraction_version_id:doc.extraction.canonical_extraction_version_id,context:{title:doc.title,subtitle:doc.subtitle??null,author:doc.author??null,course_id:doc.course_id??null,language:doc.language},sections,segments:segments.map(({source_locators,...s})=>s),assets:[]};
 return {schema:READER_SCHEMA,document_id:doc.document_id,title:doc.title,subtitle:doc.subtitle??null,author:doc.author??null,course_id:doc.course_id??null,language:doc.language,reader_projection_version_id:`rpv1:sha256:${await sha256(identity)}`,canonical_extraction_version_id:doc.extraction.canonical_extraction_version_id,source_version_id:doc.source.source_version_id,offset_unit:'utf16_code_unit',sections,segments,paragraphs,readable_text,readable_text_length:readable_text.length,assets:[],provenance_ref:{document_id:doc.document_id,source_version_id:doc.source.source_version_id,canonical_extraction_version_id:doc.extraction.canonical_extraction_version_id,provenance_ids:doc.source.provenance.map(p=>p.provenance_id)}};
}
function sentenceUnits(segment,maxChars){const units=[],re=/[^.!?…]+[.!?…]+(?:[”»"])?|[^.!?…]+$/gu;let m;while((m=re.exec(segment.text))){let a=m.index,b=m.index+m[0].length;while(a<b&&/\s/u.test(segment.text[a]))a++;while(b>a&&/\s/u.test(segment.text[b-1]))b--;if(a===b)continue;let start=a;while(b-start>maxChars){const hard=start+maxChars;let cut=hard;for(let i=hard;i>start+Math.floor(maxChars*.55);i--){if(/\s/u.test(segment.text[i])){cut=i;break}}let end=cut;while(end>start&&/\s/u.test(segment.text[end-1]))end--;units.push({segment_id:segment.segment_id,segment_start:start,segment_end:end,text:segment.text.slice(start,end)});start=cut;while(start<b&&/\s/u.test(segment.text[start]))start++}if(start<b)units.push({segment_id:segment.segment_id,segment_start:start,segment_end:b,text:segment.text.slice(start,b)})}return units}
async function projectTtsChunks(reader){const chunker={...CHUNKER,include_kinds:[...CHUNKER.include_kinds]},ttsp=`ttsp1:sha256:${await sha256({reader_projection_version_id:reader.reader_projection_version_id,chunker})}`,byId=new Map(reader.segments.map(s=>[s.segment_id,s])),chunks=[];let pending=[],pendingLen=0;const flush=async()=>{if(!pending.length)return;let text='';const links=[];for(const u of pending){if(text)text+=' ';const cs=text.length;text+=u.text;const ce=text.length,seg=byId.get(u.segment_id);links.push({segment_id:u.segment_id,reader_span:{start:seg.span.start+u.segment_start,end:seg.span.start+u.segment_end},segment_span:{start:u.segment_start,end:u.segment_end},chunk_span:{start:cs,end:ce}})}const order=chunks.length,reader_span={start:links[0].reader_span.start,end:links[links.length-1].reader_span.end},identity={tts_projection_version_id:ttsp,order,text,links};chunks.push({chunk_id:`ttsc1:sha256:${await sha256(identity)}`,order,text,reader_span,links});pending=[];pendingLen=0};for(const segment of reader.segments){if(!chunker.include_kinds.includes(segment.kind)){await flush();continue}for(const u of sentenceUnits(segment,chunker.max_chars)){const next=pending.length?pendingLen+1+u.text.length:u.text.length;if(pending.length&&next>chunker.max_chars)await flush();pending.push(u);pendingLen=pending.length===1?u.text.length:pendingLen+1+u.text.length}}await flush();return {schema:TTS_SCHEMA,document_id:reader.document_id,reader_projection_version_id:reader.reader_projection_version_id,tts_projection_version_id:ttsp,language:reader.language,offset_unit:'utf16_code_unit',chunker,chunks}}
async function buildDoc(def){const canonical=await buildCanonical(def),reader=await canonicalToReader(canonical),tts=await projectTtsChunks(reader);return {...def,canonical,reader,tts}}
function setStatus(s){E.status.textContent=s}function setPlaying(v){state.playing=v;E.play.dataset.playing=v?'1':'0';E.play.setAttribute('aria-label',v?'Pausar':'Reproducir')}function openDock(){E.dock.dataset.open='1';E.buffer.style.width='18%';requestAnimationFrame(()=>E.buffer.style.width='70%')}
function disposeAudio(){state.intent=false;state.audio?.pause();state.audio=null;if('speechSynthesis'in window)speechSynthesis.cancel();clearInterval(state.fallbackTimer);state.fallbackTimer=null;for(const p of state.clips.values())Promise.resolve(p).then(a=>{if(a?.src?.startsWith('blob:'))URL.revokeObjectURL(a.src)}).catch(()=>{});state.clips.clear();state.index=0;state.fallback=false;setPlaying(false);E.progress.style.width='0';E.buffer.style.width='0';E.dock.dataset.open='0'}
function navigate(slug){const u=new URL(location.href);slug?u.searchParams.set('doc',slug):u.searchParams.delete('doc');history.pushState({},'',u);renderRoute()}
function renderLibrary(){disposeAudio();E.reader.hidden=true;E.library.hidden=false;E.list.innerHTML=state.docs.map((d,i)=>`<button class="doc-row" type="button" data-doc="${esc(d.slug)}"><span class="doc-num">${String(i+1).padStart(2,'0')}</span><span><span class="doc-title">${esc(d.reader.title)}</span><span class="doc-meta">${d.reader.paragraphs.length} párrafos · ${d.tts.chunks.length} chunks TTS · Canonical validado</span></span><span class="doc-arrow">→</span></button>`).join('');E.list.querySelectorAll('[data-doc]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.doc)))}
function renderReader(doc){disposeAudio();state.doc=doc;E.library.hidden=true;E.reader.hidden=false;E.title.textContent=doc.reader.title;E.subtitle.textContent=doc.reader.subtitle||'';E.identity.textContent=doc.reader.document_id.slice(0,28)+'…';E.count.textContent=`${doc.tts.chunks.length} chunks`;E.text.innerHTML=doc.reader.sections.map((sec,si)=>{const segs=sec.segment_ids.map(id=>doc.reader.segments.find(s=>s.segment_id===id)).filter(Boolean);return `<section class="section"><div class="section-num">${String(si+1).padStart(2,'0')}</div><div class="section-body">${segs.map(s=>s.kind==='heading'?`<h2 class="segment-heading" data-segment-id="${esc(s.segment_id)}">${esc(s.text)}</h2>`:`<p class="segment-paragraph" data-segment-id="${esc(s.segment_id)}" data-active="0">${esc(s.text)}</p>`).join('')}</div></section>`}).join('');E.play.disabled=false;setStatus('listo para reproducir')}
function renderRoute(){const slug=new URL(location.href).searchParams.get('doc'),doc=state.docs.find(d=>d.slug===slug);doc?renderReader(doc):renderLibrary();window.scrollTo(0,0)}
function markChunk(i){E.text.querySelectorAll('.segment-paragraph').forEach(n=>n.dataset.active='0');const chunk=state.doc?.tts.chunks[i];if(!chunk)return;for(const id of new Set(chunk.links.map(x=>x.segment_id))){const n=E.text.querySelector(`[data-segment-id="${CSS.escape(id)}"]`);if(n?.classList.contains('segment-paragraph'))n.dataset.active='1'}const a=E.text.querySelector('.segment-paragraph[data-active="1"]');if(a&&state.playing)a.scrollIntoView({behavior:'smooth',block:'center'})}
function overall(local=0){const n=state.doc?.tts.chunks.length||1;return Math.max(0,Math.min(1,(state.index+local)/n))}function updateProgress(local=0){E.progress.style.width=`${overall(local)*100}%`}function messageId(chunk){return `modelos3-demo-v1-${VOICE.id}-${chunk.chunk_id.slice(-24)}`}
async function fetchRemote(index){if(state.clips.has(index))return state.clips.get(index);const promise=(async()=>{const chunk=state.doc.tts.chunks[index],id=messageId(chunk),ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),18000);try{let r=await fetch(`${API}?id=${encodeURIComponent(id)}`,{cache:'no-store',signal:ctl.signal}).catch(()=>null);if(!r?.ok){setStatus('generando voz Prometeo…');r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({voicePrompt:VOICE.prompt,text:chunk.text,messageId:id}),signal:ctl.signal})}if(!r.ok)throw new Error(`tts ${r.status}`);const blob=await r.blob(),url=URL.createObjectURL(blob),a=new Audio(url);a.preload='auto';return a}finally{clearTimeout(timer)}})();state.clips.set(index,promise);try{return await promise}catch(e){state.clips.delete(index);throw e}}
function localSpeak(index){if(!('speechSynthesis'in window))throw new Error('speech unavailable');state.fallback=true;const chunk=state.doc.tts.chunks[index],u=new SpeechSynthesisUtterance(chunk.text);u.lang='es-AR';u.rate=.96;const v=speechSynthesis.getVoices().find(x=>/^es(-AR)?$/i.test(x.lang))||speechSynthesis.getVoices().find(x=>x.lang?.startsWith('es'));if(v)u.voice=v;let started=Date.now();u.onstart=()=>{started=Date.now();setPlaying(true);markChunk(index);setStatus('reproduciendo · voz del dispositivo');clearInterval(state.fallbackTimer);state.fallbackTimer=setInterval(()=>{const est=Math.max(5,chunk.text.split(/\s+/).length/2.4);updateProgress(Math.min(.96,(Date.now()-started)/1000/est))},160)};u.onend=()=>{clearInterval(state.fallbackTimer);state.fallbackTimer=null;advance()};u.onerror=()=>{clearInterval(state.fallbackTimer);state.intent=false;setPlaying(false);setStatus('audio no disponible')};speechSynthesis.speak(u)}
async function startCurrent(){if(!state.intent)return;openDock();markChunk(state.index);try{setStatus('preparando voz Prometeo…');const a=await fetchRemote(state.index);if(!state.intent)return;state.audio=a;a.ontimeupdate=()=>updateProgress(Number.isFinite(a.duration)&&a.duration?Math.min(1,a.currentTime/a.duration):0);a.onplay=()=>{setPlaying(true);setStatus('reproduciendo · voz Prometeo');markChunk(state.index);E.buffer.style.width='100%'};a.onpause=()=>{if(!a.ended)setPlaying(false)};a.onended=advance;await a.play();if(state.index+1<state.doc.tts.chunks.length)fetchRemote(state.index+1).catch(()=>{})}catch{if(!state.intent)return;setStatus('usando voz del dispositivo…');try{localSpeak(state.index)}catch{state.intent=false;setPlaying(false);setStatus('audio no disponible')}}}
function advance(){if(state.index>=state.doc.tts.chunks.length-1){state.intent=false;setPlaying(false);updateProgress(1);setStatus(state.fallback?'lectura completa · voz local':'lectura completa');return}state.index++;state.audio=null;startCurrent()}
function togglePlay(){openDock();if(state.playing){state.intent=false;state.audio?.pause();if(state.fallback&&'speechSynthesis'in window)speechSynthesis.pause();setPlaying(false);setStatus('pausado');return}if(state.fallback&&speechSynthesis.paused){state.intent=true;speechSynthesis.resume();setPlaying(true);setStatus('reproduciendo · voz del dispositivo');return}state.intent=true;startCurrent()}
E.back.addEventListener('click',()=>navigate(null));E.play.addEventListener('click',togglePlay);window.addEventListener('popstate',renderRoute);window.addEventListener('beforeunload',disposeAudio);
(async()=>{try{setStatus('construyendo Reader Payload…');state.docs=await Promise.all(DOCS.map(buildDoc));renderRoute()}catch(err){console.error(err);E.list.innerHTML='<p>No se pudo construir la biblioteca de ejemplo.</p>'}})();
