import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-study-token,x-study-workspace","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Cache-Control":"no-store"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"content-type":"application/json; charset=utf-8"}});
const db=()=>createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
async function hex(data:ArrayBuffer){const h=await crypto.subtle.digest("SHA-256",data);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function hashText(s:string){return hex(new TextEncoder().encode(s))}
async function auth(req:Request){const token=req.headers.get("x-study-token")||"",workspace=req.headers.get("x-study-workspace")||"colo-study";if(token.length<20)return null;const c=db(),q=await c.from("study_bb_workspaces").select("token_hash").eq("id",workspace).maybeSingle();if(q.error||!q.data)return null;return (await hashText(token))===q.data.token_hash?{workspace,c}:null}
function safeName(s:string){const x=(s||"archivo").normalize("NFKD").replace(/[^a-zA-Z0-9._ -]+/g,"_").replace(/\s+/g," ").trim().slice(0,160);return x||"archivo"}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});const a=await auth(req);if(!a)return json({error:"unauthorized"},401);const {workspace,c}=a,u=new URL(req.url),action=u.searchParams.get("action")||"index";
 try{
  if(req.method==="GET"&&action==="index"){const q=await c.from("study_bb_files").select("item_key,course_key,file_name,source_url,mime_type,size_bytes,sha256,mirrored_at").eq("workspace_id",workspace).order("mirrored_at",{ascending:false});if(q.error)throw q.error;return json({ok:true,files:q.data||[]})}
  if(req.method==="GET"&&action==="signed"){const item=u.searchParams.get("item_key")||"";const q=await c.from("study_bb_files").select("storage_path,file_name,mime_type").eq("workspace_id",workspace).eq("item_key",item).maybeSingle();if(q.error||!q.data)return json({error:"not_found"},404);const s=await c.storage.from("study-blackboard-files").createSignedUrl(q.data.storage_path,900,{download:q.data.file_name});if(s.error)throw s.error;return json({ok:true,url:s.data.signedUrl,file_name:q.data.file_name,mime_type:q.data.mime_type})}
  if(req.method==="POST"&&action==="upload"){const f=await req.formData(),file=f.get("file");if(!(file instanceof File))return json({error:"file_required"},400);if(file.size>52428800)return json({error:"file_too_large"},413);const item=String(f.get("item_key")||"").slice(0,500),course=String(f.get("course_key")||"").slice(0,240)||null,source=String(f.get("source_url")||"").slice(0,4000)||null,name=safeName(String(f.get("file_name")||file.name||"archivo"));if(!item)return json({error:"item_key_required"},400);const bytes=await file.arrayBuffer(),sha=await hex(bytes),id=(await hashText(item)).slice(0,20),coursePath=safeName(course||"sin-materia").replace(/ /g,"_"),path=`${workspace}/${coursePath}/${id}/${name}`;const prev=await c.from("study_bb_files").select("sha256,storage_path").eq("workspace_id",workspace).eq("item_key",item).maybeSingle();if(prev.data?.sha256===sha)return json({ok:true,unchanged:true,sha256:sha,size:file.size});const up=await c.storage.from("study-blackboard-files").upload(path,new Blob([bytes],{type:file.type||"application/octet-stream"}),{upsert:true,contentType:file.type||"application/octet-stream",cacheControl:"3600"});if(up.error)throw up.error;if(prev.data?.storage_path&&prev.data.storage_path!==path)await c.storage.from("study-blackboard-files").remove([prev.data.storage_path]);const row={workspace_id:workspace,item_key:item,course_key:course,file_name:name,storage_path:path,source_url:source,mime_type:file.type||null,size_bytes:file.size,sha256:sha,mirrored_at:new Date().toISOString()};const q=await c.from("study_bb_files").upsert(row,{onConflict:"workspace_id,item_key"});if(q.error)throw q.error;return json({ok:true,updated:!!prev.data,sha256:sha,size:file.size,file_name:name})}
  return json({error:"not_found"},404);
 }catch(e){console.error(e);return json({error:String((e as any)?.message||e)},500)}
});