(()=>{
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let mountedFor=null,mode='video',mounting=false;
async function channel(){const cs=await Creator.channels();return cs.find(x=>x.youtube_channel_id)||cs.find(x=>/carpincho/i.test(x.title||''))||null}
async function latestMedia(){const ch=await channel();if(!ch)return null;const {data,error}=await Creator.sb.from('creator_videos').select('id,title,hook,state,metadata,updated_at').eq('channel_id',ch.id).order('updated_at',{ascending:false}).limit(20);if(error)throw error;const v=(data||[]).find(x=>x.metadata?.last_video_provider||x.metadata?.last_image_provider);if(!v)return null;let image=null,master=null;const {data:imgs}=await Creator.sb.from('creator_assets').select('id,object_path,provider,metadata,created_at').eq('video_id',v.id).eq('kind','IMAGE').order('created_at',{ascending:false}).limit(1);if(imgs?.[0]){const s=await Creator.sb.storage.from('creator-assets').createSignedUrl(imgs[0].object_path,3600);if(!s.error)image={...imgs[0],url:s.data.signedUrl}}try{const m=await Creator.master(v.id);if(m?.signed_url||m?.url)master={url:m.signed_url||m.url}}catch{}return{video:v,image,master}}
async function renderPreview(){const root=document.querySelector('#v11Preview');if(!root)return;root.innerHTML='<div class="v11-preview-head"><b>Último resultado real</b><span>cargando…</span></div>';try{const x=await latestMedia();if(!x){root.innerHTML='<div class="v11-preview-head"><b>Último resultado real</b></div><div class="v11-empty">Todavía no hay media generada.</div>';return}const p=x.video.metadata?.last_video_provider||x.video.metadata?.last_image_provider||'media';root.innerHTML=`<div class="v11-preview-head"><b>Último resultado real</b><span>$0 · persistido</span></div><div class="v11-preview-media">${x.image?`<figure><img src="${esc(x.image.url)}" alt=""></figure>`:'<div></div>'}${x.master?`<video src="${esc(x.master.url)}" controls playsinline muted></video>`:''}</div><div class="v11-preview-meta"><strong>${esc(x.video.title)}</strong><span>${esc(x.video.state)} · ${esc(p)}${x.video.metadata?.last_video_mode?' · '+esc(x.video.metadata.last_video_mode):''}</span></div>`}catch(e){root.innerHTML=`<div class="v11-preview-head"><b>Último resultado real</b></div><div class="v11-empty">${esc(e.message||e)}</div>`}}
function formIdea(kind){const host=document.querySelector('#v11Mode');if(!host)return;const series=kind==='series';host.innerHTML=`<div class="v11-title">${series?'Abrir una rama de contenido.':'Guardar una idea sin producirla todavía.'}</div><div class="v11-field"><label>${series?'serie':'título'}</label><input id="v11Title" placeholder="${series?'ej. Carpinchos en trabajos humanos':'una frase alcanza'}"></div><div class="v11-field"><label>${series?'premisa':'idea / hook'}</label><textarea id="v11Body" placeholder="${series?'qué hace reconocible esta rama':'qué pasa o por qué alguien frenaría el scroll'}"></textarea></div><button class="v11-go" id="v11Save">${series?'crear serie':'guardar idea'} →</button><div class="v11-status" id="v11Status"></div>`;host.querySelector('#v11Save').onclick=async()=>{const title=host.querySelector('#v11Title').value.trim(),body=host.querySelector('#v11Body').value.trim(),status=host.querySelector('#v11Status');if(!title){status.textContent='falta el título';return}status.textContent='guardando…';try{const ch=await channel();if(series)await Creator.api(`/channels/${ch.id}/stories`,{method:'POST',body:{title,summary:body,story_data:{premise:body,episodes:[]}}});else await Creator.createVideo({channelId:ch.id,title,hook:body,targetDurationMs:30000});status.textContent='guardado ✓';host.querySelector('#v11Title').value='';host.querySelector('#v11Body').value='';await renderPreview()}catch(e){status.textContent=String(e.message||e)}}}
function mediaMode(kind){const host=document.querySelector('#v11Mode'),v5=document.querySelector('#v5Creative');if(!host)return;if(!v5){host.innerHTML='<div class="v11-copy">preparando motores…</div>';setTimeout(()=>mediaMode(kind),80);return}host.innerHTML='';host.appendChild(v5);v5.querySelector(`[data-v5="${kind}"]`)?.click()}
function setMode(next){mode=next;document.querySelectorAll('#v11Rail [data-studio]').forEach(b=>b.classList.toggle('active',b.dataset.studio===next));if(next==='idea'||next==='series')formIdea(next);else mediaMode(next)}
function mount(){if(mounting)return;const form=document.querySelector('#createForm'),modes=document.querySelector('.create-modes');if(!form||!modes)return;const section=form.closest('.real-section');if(!section||section.dataset.v11==='1')return;mounting=true;section.dataset.v11='1';const studio=document.createElement('div');studio.className='v11-studio';studio.innerHTML=`<div class="v11-work"><div class="v11-rail" id="v11Rail"><button data-studio="idea">idea</button><button data-studio="image">imagen</button><button data-studio="video" class="active">video</button><button data-studio="series">serie</button><button data-studio="sources">fuentes</button><span>FREE_ONLY · $0</span></div><div id="v11Mode" class="v11-mode"></div></div><aside class="v11-preview" id="v11Preview"></aside>`;const result=section.querySelector('#createResult');(result||form).after(studio);studio.querySelector('#v11Rail').onclick=e=>{const b=e.target.closest('[data-studio]');if(b)setMode(b.dataset.studio)};setMode(mode);renderPreview();mountedFor=section;mounting=false}
const mo=new MutationObserver(()=>queueMicrotask(mount));mo.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('creator:image-saved',()=>renderPreview());window.addEventListener('creator:video-saved',()=>renderPreview());mount();
})();
