(()=>{
'use strict';
const SB='https://catnohyouxqjjtseaueb.supabase.co',FREE_VIDEO=SB+'/functions/v1/creator-free-video',KEY='sb_publishable_eqh3PngXs4UjLLWiY3pz1w_nhHtf7X-';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const busy=new Set();
async function session(){return (await Creator.sb.auth.getSession()).data.session}
async function call(body){const s=await session();if(!s)throw Error('LOGIN_REQUIRED');const r=await fetch(FREE_VIDEO,{method:'POST',headers:{Authorization:'Bearer '+s.access_token,apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)}),p=await r.json().catch(()=>({}));if(!r.ok){const e=Error(p.error||('HTTP_'+r.status));e.status=r.status;throw e}return p}
async function promptFor(assetId,videoId){const[a,v]=await Promise.all([Creator.sb.from('creator_assets').select('metadata').eq('id',assetId).maybeSingle(),Creator.sb.from('creator_videos').select('title,hook').eq('id',videoId).maybeSingle()]);const base=a.data?.metadata?.prompt||v.data?.hook||v.data?.title||'Animate this image naturally';return `${base}. Natural coherent motion, preserve the subject and composition, cinematic but stable camera.`}
async function animate(btn){const assetId=btn.dataset.animateImage,videoId=btn.dataset.videoId;if(!assetId||!videoId||busy.has(assetId))return;busy.add(assetId);const fig=btn.closest('figure'),status=fig?.querySelector('.v6-animate-status')||btn.parentElement;btn.disabled=true;btn.textContent='animando…';try{const prompt=await promptFor(assetId,videoId);if(status)status.textContent='LTX ZeroGPU · generando 2 s…';const r=await call({prompt,video_id:videoId,image_asset_id:assetId,duration:2,width:288,height:512});if(status)status.innerHTML=`<video class="v5-video" src="${esc(r.signed_url||'')}" controls playsinline autoplay muted></video><div class="v5-result-meta">image→video · LTX ZeroGPU · QA ${esc(r.qa?.status||'PASS')} · $0</div><div class="v5-compose-row"><button data-v9-publish="${esc(videoId)}">subir privado →</button><button data-v9-open="${esc(videoId)}">abrir producción</button></div><div class="v5-result-meta" data-v9-job></div>`;status?.querySelector('[data-v9-publish]')?.addEventListener('click',async e=>{const j=status.querySelector('[data-v9-job]');j.textContent='YouTube · preparando…';try{const p=await Creator.publish(videoId,{privacy:'private',contains_synthetic_media:true}),d=await Creator.waitJob(p.job.id,x=>j.textContent='YouTube · '+String(x.status).toLowerCase());j.textContent=d.status==='SUCCEEDED'?'YouTube privado ✓':'YouTube · '+d.status}catch(err){j.textContent=String(err?.message||err)}});status?.querySelector('[data-v9-open]')?.addEventListener('click',()=>{document.querySelector(`[data-v4-open="${CSS.escape(videoId)}"]`)?.click()});window.dispatchEvent(new CustomEvent('creator:video-saved',{detail:{video_id:videoId,asset_id:r.asset?.id||null,provider:r.provider,mode:'image-to-video'}}));btn.textContent='animada ✓'}catch(e){if(status)status.textContent=e.status===429?'ZeroGPU sin cuota ahora; probá más tarde o conectá Hugging Face Free.':String(e?.message||e);btn.disabled=false;btn.textContent='animar esta imagen →'}finally{busy.delete(assetId)}}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-animate-image]');if(!b)return;e.preventDefault();animate(b)});
window.addEventListener('creator:image-saved',e=>{const d=e.detail||{},out=document.querySelector('#v5Output');if(!out||!d.asset_id||!d.video_id)return;if(out.querySelector('[data-animate-image]'))return;const row=document.createElement('div');row.className='v5-compose-row';row.innerHTML=`<button class="v5-inline" data-animate-image="${esc(d.asset_id)}" data-video-id="${esc(d.video_id)}">animar esta imagen →</button><div class="v6-animate-status"></div>`;out.appendChild(row)});
})();
