(()=>{
'use strict';
const SB='https://catnohyouxqjjtseaueb.supabase.co',MEDIA=SB+'/functions/v1/creator-media-router',FREE=SB+'/functions/v1/creator-free-image',COMMONS=SB+'/functions/v1/creator-free-commons',KEY='sb_publishable_eqh3PngXs4UjLLWiY3pz1w_nhHtf7X-';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));let running=false;
async function session(){return (await Creator.sb.auth.getSession()).data.session}
async function req(url,{method='GET',body=null}={}){const s=await session();if(!s)throw Error('LOGIN_REQUIRED');const h={Authorization:'Bearer '+s.access_token,apikey:KEY};if(body!==null)h['Content-Type']='application/json';const r=await fetch(url,{method,headers:h,body:body===null?undefined:JSON.stringify(body)}),p=await r.json().catch(()=>({}));if(!r.ok){const e=Error(p.error||('HTTP_'+r.status));e.status=r.status;e.payload=p;throw e}return p}
async function channel(){const cs=await Creator.channels();return cs.find(x=>x.youtube_channel_id)||cs.find(x=>/carpincho/i.test(x.title||''))||null}
async function route(){try{return await req(MEDIA+'/route/plan?modality=image')}catch{return null}}
async function commonsImage(prompt,ch,draft,out){out.textContent='ZeroGPU sin cuota · buscando imagen reutilizable…';return req(COMMONS,{method:'POST',body:{prompt,channel_id:ch.id,video_id:draft.id,modality:'image'}})}
async function generate(){if(running)return;const prompt=document.querySelector('#v5Prompt')?.value.trim(),out=document.querySelector('#v5Output');if(!prompt||!out){if(out)out.textContent='escribí un prompt';return}running=true;out.textContent='preparando imagen…';let draft=null;try{const ch=await channel();if(!ch)throw Error('CANAL_REAL_NO_ENCONTRADO');draft=await Creator.createVideo({channelId:ch.id,title:('Imagen · '+prompt).slice(0,120),hook:prompt,targetDurationMs:5000});const plan=await route(),ext=plan?.plan?.find(x=>x.kind==='external');let result=null,firstError=null;if(ext){out.textContent=`generando · ${ext.provider}…`;try{result=await req(MEDIA+'/generate/image',{method:'POST',body:{prompt,channel_id:ch.id,video_id:draft.id}})}catch(e){firstError=e}}
 if(!result){out.textContent='generando · FLUX Schnell ZeroGPU…';try{result=await req(FREE,{method:'POST',body:{prompt,channel_id:ch.id,video_id:draft.id,width:768,height:1024}})}catch(e){if(e.status===429){try{result=await commonsImage(prompt,ch,draft,out)}catch(ce){out.innerHTML='<div class="v5-note">La IA gratuita está sin cuota y no encontré una imagen reutilizable compatible.</div><button class="v5-inline" id="v7Sources">ampliar cuota gratis con Hugging Face →</button>';return}}else throw(firstError||e)}}
 const commons=result.provider==='wikimedia-commons',src=result.source||{},caption=commons?`Wikimedia Commons · ${esc(src.license||'licencia reutilizable')} · $0`:`${esc(result.provider)} · Storage privado · $0`;out.innerHTML=`<figure class="v5-result"><img src="${esc(result.signed_url)}" alt=""><figcaption>${caption}</figcaption></figure><div class="v5-result-meta">${commons?'fuente visual guardada':'guardada en este borrador'} ✓${commons&&src.artist?' · '+esc(src.artist):''}</div>${commons&&src.description_url?`<div class="v5-compose-row"><a class="v5-inline" href="${esc(src.description_url)}" target="_blank" rel="noopener">fuente + licencia ↗</a><button class="v5-inline" data-hf-quota>generar con IA cuando haya cuota →</button></div>`:''}`;window.dispatchEvent(new CustomEvent('creator:image-saved',{detail:{video_id:draft.id,asset_id:result.asset?.id||null,provider:result.provider,source:commons}}));
 }catch(e){out.textContent=String(e?.message||e)}finally{running=false}}
function updateRoute(){const active=document.querySelector('#v5Creative [data-v5="image"].active'),label=document.querySelector('#v5Route');if(active&&label&&!/cloudflare|external/i.test(label.textContent||''))label.textContent='FLUX Schnell → Commons · $0';}
document.addEventListener('click',e=>{const t=e.target.closest?.('#v5Generate');if(!t||!document.querySelector('#v5Creative [data-v5="image"].active'))return;e.preventDefault();e.stopImmediatePropagation();generate()},true);
const mo=new MutationObserver(()=>queueMicrotask(updateRoute));mo.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});updateRoute();
})();
