(()=>{
'use strict';
const SB='https://catnohyouxqjjtseaueb.supabase.co',FREE_VIDEO=SB+'/functions/v1/creator-free-video',KEY='sb_publishable_eqh3PngXs4UjLLWiY3pz1w_nhHtf7X-';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let running=false;
async function session(){return (await Creator.sb.auth.getSession()).data.session}
async function call(body){const s=await session();if(!s)throw Error('LOGIN_REQUIRED');const r=await fetch(FREE_VIDEO,{method:'POST',headers:{Authorization:'Bearer '+s.access_token,apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)}),p=await r.json().catch(()=>({}));if(!r.ok){const e=Error(p.error||('HTTP_'+r.status));e.status=r.status;e.payload=p;throw e}return p}
async function channel(){const cs=await Creator.channels();return cs.find(x=>x.youtube_channel_id)||cs.find(x=>/carpincho/i.test(x.title||''))||null}
async function fallbackTechnical(prompt,out,draft){out.innerHTML='<div class="v5-note">ZeroGPU está sin cuota en este momento. Uso el renderer técnico $0 como fallback; el borrador queda listo para regenerar con IA después.</div><div class="v5-result-meta">preparando fallback…</div>';const p=await Creator.produce(draft.id,0),j=await Creator.waitJob(p.job.id,x=>{const m=out.querySelector('.v5-result-meta');if(m)m.textContent='fallback · '+String(x.status).toLowerCase()});if(j.status!=='SUCCEEDED')throw Error(j.status);const m=await Creator.master(draft.id);out.innerHTML=`<div class="v5-note">Fallback técnico $0 · no es generación IA.</div><video class="v5-video" src="${esc(m.signed_url||m.url||'')}" controls playsinline></video><div class="v5-result-meta">READY · Storage privado · $0</div>`}
async function generate(){if(running)return;const prompt=document.querySelector('#v5Prompt')?.value.trim(),out=document.querySelector('#v5Output');if(!prompt||!out){if(out)out.textContent='escribí un prompt';return}running=true;let draft=null;try{const ch=await channel();if(!ch)throw Error('CANAL_REAL_NO_ENCONTRADO');out.textContent='creando borrador…';draft=await Creator.createVideo({channelId:ch.id,title:('Video · '+prompt).slice(0,120),hook:prompt,targetDurationMs:2000});out.textContent='generando · LTX Video Fast · ZeroGPU $0…';let r;try{r=await call({prompt,video_id:draft.id,duration:2,width:288,height:512})}catch(e){if(e.status===429||/ZEROGPU_ANON_UNAVAILABLE/i.test(e.message)){await fallbackTechnical(prompt,out,draft);return}throw e}out.innerHTML=`<div class="v5-note">Video IA real · LTX Video Fast · ZeroGPU</div><video class="v5-video" src="${esc(r.signed_url||'')}" controls playsinline autoplay muted></video><div class="v5-result-meta">READY · ${esc(r.asset?.duration_ms?Math.round(r.asset.duration_ms/1000)+' s':'2 s')} · QA ${esc(r.qa?.status||'PASS')} · Storage privado · $0</div><div class="v5-compose-row"><button id="v8Publish">subir privado a YouTube →</button><button id="v8Open">abrir producción</button></div><div id="v8Job" class="v5-result-meta"></div>`;out.querySelector('#v8Publish').onclick=async()=>{const j=out.querySelector('#v8Job');j.textContent='YouTube · preparando…';try{const p=await Creator.publish(draft.id,{privacy:'private',contains_synthetic_media:true}),done=await Creator.waitJob(p.job.id,x=>j.textContent='YouTube · '+String(x.status).toLowerCase());j.textContent=done.status==='SUCCEEDED'?'YouTube privado ✓':'YouTube · '+done.status}catch(e){j.textContent=String(e.message||e)}};out.querySelector('#v8Open').onclick=()=>{document.querySelector('[data-rview="create"]')?.click();setTimeout(()=>{const b=[...document.querySelectorAll('[data-video]')].find(x=>x.dataset.video===draft.id);b?.click()},150)};window.dispatchEvent(new CustomEvent('creator:video-saved',{detail:{video_id:draft.id,asset_id:r.asset?.id||null,provider:r.provider}}))}catch(e){out.textContent=String(e?.message||e)}finally{running=false}}
function updateRoute(){const active=document.querySelector('#v5Creative [data-v5="video"].active'),label=document.querySelector('#v5Route');if(active&&label)label.textContent='LTX Video Fast · ZeroGPU $0 · 2 s'}
document.addEventListener('click',e=>{const t=e.target.closest?.('#v5Generate');if(!t||!document.querySelector('#v5Creative [data-v5="video"].active'))return;e.preventDefault();e.stopImmediatePropagation();generate()},true);
const mo=new MutationObserver(()=>queueMicrotask(updateRoute));mo.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});updateRoute();
})();
