(()=>{
'use strict';
const SB='https://catnohyouxqjjtseaueb.supabase.co',MEDIA=SB+'/functions/v1/creator-media-router',FREE=SB+'/functions/v1/creator-free-image',KEY='sb_publishable_eqh3PngXs4UjLLWiY3pz1w_nhHtf7X-';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));let running=false;
async function session(){return (await Creator.sb.auth.getSession()).data.session}
async function req(url,{method='GET',body=null}={}){const s=await session();if(!s)throw Error('LOGIN_REQUIRED');const h={Authorization:'Bearer '+s.access_token,apikey:KEY};if(body!==null)h['Content-Type']='application/json';const r=await fetch(url,{method,headers:h,body:body===null?undefined:JSON.stringify(body)}),p=await r.json().catch(()=>({}));if(!r.ok){const e=Error(p.error||('HTTP_'+r.status));e.status=r.status;e.payload=p;throw e}return p}
async function channel(){const cs=await Creator.channels();return cs.find(x=>x.youtube_channel_id)||cs.find(x=>/carpincho/i.test(x.title||''))||null}
async function route(){try{return await req(MEDIA+'/route/plan?modality=image')}catch{return null}}
async function generate(){if(running)return;const prompt=document.querySelector('#v5Prompt')?.value.trim(),out=document.querySelector('#v5Output');if(!prompt||!out){if(out)out.textContent='escribí un prompt';return}running=true;out.textContent='preparando imagen…';let draft=null;try{const ch=await channel();if(!ch)throw Error('CANAL_REAL_NO_ENCONTRADO');draft=await Creator.createVideo({channelId:ch.id,title:('Imagen · '+prompt).slice(0,120),hook:prompt,targetDurationMs:5000});const plan=await route(),ext=plan?.plan?.find(x=>x.kind==='external');let result=null,firstError=null;if(ext){out.textContent=`generando · ${ext.provider}…`;try{result=await req(MEDIA+'/generate/image',{method:'POST',body:{prompt,channel_id:ch.id,video_id:draft.id}})}catch(e){firstError=e}}
 if(!result){out.textContent='generando · FLUX Schnell ZeroGPU…';try{result=await req(FREE,{method:'POST',body:{prompt,channel_id:ch.id,video_id:draft.id,width:768,height:1024}})}catch(e){if(e.status===429){out.innerHTML='<div class="v5-note">La cuota anónima gratuita de ZeroGPU está ocupada o agotada. Conectar una cuenta Free de Hugging Face aumenta la cuota gratuita.</div><button class="v5-inline" id="v7Sources">conectar Hugging Face →</button>';out.querySelector('#v7Sources').onclick=()=>document.querySelector('[data-v5="sources"]')?.click();return}throw(firstError||e)}}
 out.innerHTML=`<figure class="v5-result"><img src="${esc(result.signed_url)}" alt=""><figcaption>${esc(result.provider)} · Storage privado · $0</figcaption></figure><div class="v5-result-meta">guardada en este borrador ✓</div>`;window.dispatchEvent(new CustomEvent('creator:image-saved',{detail:{video_id:draft.id,asset_id:result.asset?.id||null}}));
 }catch(e){out.textContent=String(e?.message||e)}finally{running=false}}
function updateRoute(){const active=document.querySelector('#v5Creative [data-v5="image"].active'),label=document.querySelector('#v5Route');if(active&&label&&!/cloudflare|external/i.test(label.textContent||''))label.textContent='FLUX Schnell · ZeroGPU $0';}
document.addEventListener('click',e=>{const t=e.target.closest?.('#v5Generate');if(!t||!document.querySelector('#v5Creative [data-v5="image"].active'))return;e.preventDefault();e.stopImmediatePropagation();generate()},true);
const mo=new MutationObserver(()=>queueMicrotask(updateRoute));mo.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});updateRoute();
})();
