(()=>{
'use strict';
const MEDIA='https://catnohyouxqjjtseaueb.supabase.co/functions/v1/creator-media-router';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let providerCache=null,mode=null,busy=false;
async function session(){const x=await Creator.sb?.auth.getSession();return x?.data?.session||null}
async function media(path,{method='GET',body=null}={}){const s=await session();if(!s)throw new Error('LOGIN_REQUIRED');const h={Authorization:'Bearer '+s.access_token,apikey:'sb_publishable_eqh3PngXs4UjLLWiY3pz1w_nhHtf7X-'};if(body!==null)h['Content-Type']='application/json';const r=await fetch(MEDIA+path,{method,headers:h,body:body===null?undefined:JSON.stringify(body)}),p=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(p.error||('HTTP_'+r.status));e.payload=p;throw e}return p}
async function realChannel(){const cs=await Creator.channels();return cs.find(x=>x.youtube_channel_id)||cs.find(x=>String(x.slug||'').includes('carpincho'))||null}
function statusText(p){const c=p.connection;if(!c)return'sin conectar';if(c.mode==='BLOCKED')return'credencial rechazada';if(c.mode==='CONFIGURED')return'guardado · no probado';if(p.provider==='huggingface_zerogpu'&&c.mode==='VERIFIED_REAL')return'listo $0 · cuota ampliada';if(c.mode==='VERIFIED_REAL'&&c.metadata?.free_safe)return'listo $0';if(c.mode==='VERIFIED_REAL')return'conectado · bloqueado en $0';return String(c.mode||'').toLowerCase()}
function policyText(p){if(p.free_policy==='HARD_FREE_PLAN')return'plan gratis duro';if(p.free_policy==='HARD_FREE_QUOTA')return'cuota gratis';if(p.free_policy==='FREE_CREDITS')return'créditos gratis';if(p.free_policy==='BUDGETED_CREDITS')return'créditos con límite';if(p.free_policy==='PAID')return'pago';return'promo / pago'}
async function getProviders(force=false){if(providerCache&&!force)return providerCache;providerCache=await media('/providers');return providerCache}
function mount(){const form=document.querySelector('#createForm'),modes=document.querySelector('.create-modes');if(!form||!modes||document.querySelector('#v5Creative'))return;const root=document.createElement('section');root.id='v5Creative';root.className='v5-creative';root.innerHTML=`<div class="v5-switch"><button data-v5="image">imagen</button><button data-v5="video">video</button><button data-v5="sources">fuentes</button><span>gasto máximo $0</span></div><div id="v5Host"></div>`;modes.after(root);root.querySelectorAll('[data-v5]').forEach(b=>b.onclick=()=>select(b.dataset.v5));}
function select(next){mode=next;document.querySelectorAll('#v5Creative [data-v5]').forEach(b=>b.classList.toggle('active',b.dataset.v5===next));if(next==='sources')renderSources();else renderComposer(next)}
async function renderComposer(kind){const host=document.querySelector('#v5Host');if(!host)return;const label=kind==='image'?'imagen':'video';host.innerHTML=`<div class="v5-composer"><div class="v5-line"><label>prompt</label><textarea id="v5Prompt" placeholder="describí ${label==='imagen'?'la imagen':'el video'} que querés producir"></textarea></div><div class="v5-compose-row"><button id="v5Generate">${kind==='image'?'generar imagen':'generar video'} →</button><button id="v5SourcesQuick">fuentes</button><span id="v5Route">buscando ruta $0…</span></div><div id="v5Output"></div></div>`;host.querySelector('#v5SourcesQuick').onclick=()=>select('sources');try{const p=await media('/route/plan?modality='+kind);const ext=p.plan?.find(x=>x.kind==='external');host.querySelector('#v5Route').textContent=ext?`${ext.provider} · $0`:(kind==='video'?'demo técnico $0 disponible · generador externo sin conectar':'sin generador externo $0 conectado');host.querySelector('#v5Generate').onclick=()=>generate(kind,p)}catch(e){host.querySelector('#v5Route').textContent=e.message}}
async function generate(kind,plan){if(busy)return;const prompt=document.querySelector('#v5Prompt')?.value.trim(),out=document.querySelector('#v5Output');if(!prompt){out.textContent='escribí un prompt';return}busy=true;try{if(kind==='image'){const ext=plan?.plan?.find(x=>x.kind==='external');if(!ext){out.innerHTML='<div class="v5-note">Todavía no hay una fuente externa demostrablemente $0. Conectá Cloudflare Free o una fuente gratuita verificable.</div><button class="v5-inline" id="v5GoSources">conectar fuente →</button>';out.querySelector('#v5GoSources').onclick=()=>select('sources');return}out.textContent='generando imagen…';const ch=await realChannel();if(!ch)throw new Error('CANAL_REAL_NO_ENCONTRADO');const draft=await Creator.createVideo({channelId:ch.id,title:prompt.slice(0,96),hook:prompt,targetDurationMs:5000});const r=await media('/generate/image',{method:'POST',body:{prompt,channel_id:ch.id,video_id:draft.id}});out.innerHTML=`<figure class="v5-result"><img src="${esc(r.signed_url)}" alt=""><figcaption>${esc(r.provider)} · Storage privado · $0</figcaption></figure>`}else{out.textContent='preparando demo técnico $0…';const ch=await realChannel();if(!ch)throw new Error('CANAL_REAL_NO_ENCONTRADO');const v=await Creator.createVideo({channelId:ch.id,title:prompt.slice(0,96),hook:prompt,targetDurationMs:5000});const p=await Creator.produce(v.id,0),j=await Creator.waitJob(p.job.id,x=>out.textContent=`video · ${String(x.status).toLowerCase()}`);if(j.status!=='SUCCEEDED')throw new Error(j.status);const m=await Creator.master(v.id);out.innerHTML=`<div class="v5-note">Este es el renderer técnico gratuito, no IA generativa. El prompt queda guardado en el borrador.</div><video class="v5-video" src="${esc(m.signed_url||m.url||'')}" controls playsinline></video><div class="v5-result-meta">READY · Storage privado · $0</div>`}}catch(e){out.textContent=String(e?.message||e)}finally{busy=false}}
async function renderSources(){const host=document.querySelector('#v5Host');if(!host)return;host.innerHTML='<div class="v5-note">cargando fuentes…</div>';try{const x=await getProviders(true),ps=x.providers||[],top=ps.slice(0,4),rest=ps.slice(4);host.innerHTML=`<div class="v5-source-head"><div><b>Fuentes de creación</b><span>${ps.filter(p=>p.connection).length} conectadas · política ${esc(x.policy?.mode||'FREE_ONLY')}</span></div><small>Las pagas pueden guardarse, pero Prometeo no las usa mientras $0 esté activo.</small></div><div id="v5ProviderList">${top.map(providerRow).join('')}</div>${rest.length?`<details class="v5-more"><summary>más fuentes · ${rest.length}</summary>${rest.map(providerRow).join('')}</details>`:''}<div id="v5ConnectBox"></div>`;host.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>connectForm(ps.find(p=>p.provider===b.dataset.provider)))}catch(e){host.innerHTML=`<div class="v5-note">${esc(e.message)}</div>`}}
function providerRow(p){return `<button class="v5-provider" data-provider="${esc(p.provider)}"><span><b>${esc(p.label)}</b><small>${esc((p.capabilities||[]).join(' · '))}</small></span><span><small>${esc(policyText(p))}</small><b>${esc(statusText(p))}</b></span></button>`}
function connectForm(p){const box=document.querySelector('#v5ConnectBox');if(!box)return;const fields=(p.auth_fields||[]).map(f=>`<label>${esc(f.label)}<input data-field="${esc(f.key)}" type="${f.secret?'password':'text'}" autocomplete="off"></label>`).join('');box.innerHTML=`<section class="v5-connect"><div class="v5-connect-top"><div><b>${esc(p.label)}</b><span>${esc(p.free_notes||'')}</span></div><a href="${esc(p.setup_url||'#')}" target="_blank" rel="noopener">abrir cuenta / clave ↗</a></div><div class="v5-fields">${fields}</div><div class="v5-compose-row"><button id="v5SaveProvider">guardar + probar →</button><span id="v5ProviderResult">Los secretos van al Vault; no quedan en este HTML.</span></div></section>`;box.querySelector('#v5SaveProvider').onclick=async()=>{const r=box.querySelector('#v5ProviderResult'),payload={};box.querySelectorAll('[data-field]').forEach(i=>payload[i.dataset.field]=i.value.trim());r.textContent='probando…';try{const out=await media(`/providers/${encodeURIComponent(p.provider)}/connect`,{method:'POST',body:payload});r.textContent=p.provider==='huggingface_zerogpu'&&out.connection?.mode==='VERIFIED_REAL'?'conectado · cuota ZeroGPU ampliada $0 ✓':out.connection?.metadata?.free_safe?'conectado · habilitado $0 ✓':out.connection?.mode==='VERIFIED_REAL'?'conectado ✓ · Prometeo lo mantiene bloqueado para gasto':'guardado ✓';providerCache=null;setTimeout(renderSources,500)}catch(e){r.textContent=String(e?.message||e)}}}
const obs=new MutationObserver(()=>mount());obs.observe(document.documentElement,{childList:true,subtree:true});mount();
})();
