/* Prometeo Reincarnation v1.1 — cross-file validated wake packet; no chat memory required. */
((global)=>{
 'use strict';if(global.PrometeoReincarnate)return;function fail(code,msg,detail={}){const e=new Error(msg);e.code=code;e.detail=detail;throw e}function freeze(v,seen=new WeakSet()){if(v===null||typeof v!=='object'||seen.has(v))return v;seen.add(v);for(const k of Reflect.ownKeys(v))freeze(v[k],seen);return Object.freeze(v)}const imm=v=>global.PrometeoDurable?.immutable?global.PrometeoDurable.immutable(v):freeze(structuredClone(v));
 function wake({bootstrap,currentGraph,head,dotState,parent,pending,carry,watermarks,catalog,lineage,capabilities,hotBook,ledgerReceipts}={}){
  const schemas=[[bootstrap,'prometeo.reincarnation-bootstrap/v1','PROMETEO_WAKE_BOOTSTRAP'],[currentGraph,'prometeo.current-graph/v1','PROMETEO_WAKE_CURRENT'],[head,'prometeo.head/v1','PROMETEO_WAKE_HEAD'],[dotState,'prometeo.dot-state/v1','PROMETEO_WAKE_DOT'],[parent,'prometeo.parent/v1','PROMETEO_WAKE_PARENT'],[pending,'prometeo.pending/v1','PROMETEO_WAKE_PENDING'],[carry,'prometeo.carry/v1','PROMETEO_WAKE_CARRY'],[watermarks,'prometeo.watermarks/v1','PROMETEO_WAKE_WATERMARKS'],[catalog,'prometeo.catalog-manifest/v1','PROMETEO_WAKE_CATALOG'],[lineage,'prometeo.lineage-graph/v1','PROMETEO_WAKE_LINEAGE'],[capabilities,'prometeo.capability-registry/v1','PROMETEO_WAKE_CAPABILITIES'],[hotBook,'prometeo.context-book/v1','PROMETEO_WAKE_HOT']];for(const [doc,schema,code] of schemas)if(doc?.schema!==schema)fail(code,`Invalid/missing ${schema}`);
  const requiredRoles=new Set((bootstrap.required||[]).map(x=>x.role));for(const role of ['current_graph','head','dot_state','parent','pending','carry','watermarks','catalog','lineage','capabilities','hot_book','ledger'])if(!requiredRoles.has(role))fail('PROMETEO_WAKE_BOOTSTRAP_REQUIRED','Bootstrap missing required durable role',{role});
  if(!Array.isArray(ledgerReceipts)||!ledgerReceipts.length)fail('PROMETEO_WAKE_LEDGER_REQUIRED','Validated ledger receipts are required for wake');const receiptIds=new Set(ledgerReceipts.map(r=>r.id));const candidate=currentGraph.pointers?.candidate_current;if(!candidate)fail('PROMETEO_WAKE_CANDIDATE','candidate_current missing');if(head.artifact_id!==candidate.artifact_id||head.receipt_id!==candidate.receipt_id)fail('PROMETEO_WAKE_HEAD_DRIFT','HEAD and candidate_current disagree');if(parent.child!==head.artifact_id)fail('PROMETEO_WAKE_PARENT_DRIFT','PARENT child and HEAD disagree');if(dotState.last_receipt!==currentGraph.last_durable_receipt)fail('PROMETEO_WAKE_RECEIPT_DRIFT','DOT_STATE and Current Graph last receipt disagree');if(dotState.active_branch!==currentGraph.active_workstream?.branch)fail('PROMETEO_WAKE_BRANCH_DRIFT','DOT_STATE and Current Graph branch disagree');if(catalog.source_contract?.identity!==currentGraph.catalog_identity)fail('PROMETEO_WAKE_CATALOG_DRIFT','Catalog identity drift');for(const [name,p] of Object.entries(currentGraph.pointers||{}))if(!receiptIds.has(p.receipt_id))fail('PROMETEO_WAKE_POINTER_RECEIPT','Pointer receipt absent from ledger',{name,receipt_id:p.receipt_id});if(!receiptIds.has(head.receipt_id)||!receiptIds.has(dotState.last_receipt))fail('PROMETEO_WAKE_LEDGER_DRIFT','Durable state references receipt absent from ledger');
  const visible=currentGraph.pointers?.visible_frontend_current?.artifact_id||null,human=Object.entries(currentGraph.pointers||{}).filter(([k])=>k.startsWith('human_accepted')).map(([scope,p])=>({scope,artifact_id:p.artifact_id}));
  return imm({schema:'prometeo.wake-packet/v1',WHAT_IS_PROMETEO:'A durable, chat-agnostic system whose visible frontend is separate from backstage truth, context, work metabolism and release authority.',CURRENT:{head:head.artifact_id,visible_frontend:visible,candidate:candidate.artifact_id,phase:dotState.phase,parent:parent.parent},HUMAN_ACCEPTED_SCOPES:human,SERVED_INHERITED:currentGraph.pointers?.served_current||null,ACTIVE_FRONTEND:visible,PAGES:{count:(catalog.pages||[]).length,identity:catalog.source_contract?.identity||null},CAPABILITIES:(capabilities.capabilities||[]).map(c=>({id:c.id,best_known:c.best_known,human_accepted:c.human_accepted,rollback_donor:c.rollback_donor})),PENDING:structuredClone(pending.items||[]),RULES:(carry.items||[]).map(x=>x.text),HOW_TO_CHANGE:'Resolve target → Seed → Work Item → minimal Context Pack → execution → Artifact Return → verification → Candidate.',HOW_TO_TEST:'Use domain tests + known diseases; browser/perceptual layers remain separate.',HOW_TO_RELEASE:'Candidate → exact verification → Human Acceptance → receipt-backed Current transition → Served verification (Part 3).',WATERMARKS:structuredClone(watermarks.sources||{}),HOT:structuredClone(hotBook.items||[]),lineage_reopen:'lineage/LINEAGE_GRAPH.json'});
 }
 global.PrometeoReincarnate=Object.freeze({version:'1.1.0-candidate',wake});
})(typeof globalThis!=='undefined'?globalThis:window);
