#!/usr/bin/env bash
set -euo pipefail
PORT="${P3_PORT:-4176}"; BASE="http://127.0.0.1:${PORT}"; URL="${BASE}/lab/p3-01-browser-harness/"; ART="${P3_ARTIFACT_DIR:-artifacts/p3-macro}"; S="${P3_SESSION:-p3-macro}"
mkdir -p "$ART/viewports"
python3 -m http.server "$PORT" --bind 127.0.0.1 >"$ART/server.log" 2>&1 & SERVER_PID=$!
cleanup(){ agent-browser --session "$S" close >/dev/null 2>&1||true; kill "$SERVER_PID" >/dev/null 2>&1||true; wait "$SERVER_PID" >/dev/null 2>&1||true; }; trap cleanup EXIT
for _ in $(seq 1 40); do curl -fsS "$URL" >/dev/null 2>&1 && break; sleep .25; done
agent-browser --session "$S" open >/dev/null
agent-browser --session "$S" navigate "$URL" >/dev/null
agent-browser --session "$S" wait --load networkidle >/dev/null
agent-browser --session "$S" wait --fn "document.documentElement.dataset.p3Ready === 'true'" >/dev/null
setvp(){ local w="$1"; local h="$2"; if agent-browser --session "$S" set viewport "$w" "$h" >/dev/null 2>&1; then return 0; fi; if agent-browser --session "$S" viewport "$w" "$h" >/dev/null 2>&1; then return 0; fi; echo "agent-browser viewport command unavailable" >&2; return 88; }
checkvp(){ local w="$1"; local h="$2"; local tag="${w}x${h}"; setvp "$w" "$h"; agent-browser --session "$S" wait 120 >/dev/null; agent-browser --session "$S" eval '(()=>{const f=document.getElementById("prometeo-v53"),d=f?.contentDocument,w=f?.contentWindow,r=w?.__PROMETEO_V53__;if(!d||!w||!r)throw new Error("V53_RUNTIME_MISSING");const rect=d.querySelector(".viewport")?.getBoundingClientRect();const inv={responsive:r.responsiveInvariant?.(),depth:r.depthSlotsInvariant?.(),solver:r.edgeSolverInvariant?.(),seal:r.rightmostSealInvariant?.(),backplate:r.backplateInvariant?.(),horizontal:r.horizontalInvariant?.()};for(const [k,v] of Object.entries(inv)){if(v&&"ok" in v&&v.ok!==true)throw new Error("INVARIANT_"+k+" "+JSON.stringify(v));}const main=d.querySelector("main#viewport"),interactive=[...d.querySelectorAll("button,a,input,select,textarea,[role=button],[tabindex]")];return JSON.stringify({outer:{w:innerWidth,h:innerHeight},frame:{w:w.innerWidth,h:w.innerHeight},rect:{w:rect?.width||0,h:rect?.height||0,left:rect?.left||0,top:rect?.top||0},build:w.__PROMETEO_BUILD__,title:d.title,mainAria:main?.getAttribute("aria-label"),tabIndex:main?.tabIndex,bodyScroll:{w:d.documentElement.scrollWidth,h:d.documentElement.scrollHeight},interactive:interactive.length,invariants:inv,state:r.getState(),layout:r.layout?.()})})()' >"$ART/viewports/${tag}.json"; if [[ "$tag" == "320x240" || "$tag" == "399x800" || "$tag" == "1280x720" ]]; then agent-browser --session "$S" screenshot "$ART/viewports/${tag}.png" --full >/dev/null; fi; }
for vp in 160x120 200x200 240x320 320x240 399x800 480x800 768x1024 1280x720 1440x900; do checkvp "${vp%x*}" "${vp#*x}"; done
# Navigator / resize / Exact Back sequence.
setvp 1280 720
agent-browser --session "$S" navigate "$URL" >/dev/null; agent-browser --session "$S" wait --load networkidle >/dev/null; agent-browser --session "$S" wait --fn "document.documentElement.dataset.p3Ready === 'true'" >/dev/null
agent-browser --session "$S" eval '(()=>{const r=document.getElementById("prometeo-v53").contentWindow.__PROMETEO_V53__;return JSON.stringify(r.getState())})()' >"$ART/nav-0.json"
agent-browser --session "$S" eval 'document.getElementById("prometeo-v53").contentWindow.__PROMETEO_V53__.right();true' >/dev/null; agent-browser --session "$S" wait 500 >/dev/null
agent-browser --session "$S" eval '(()=>{const r=document.getElementById("prometeo-v53").contentWindow.__PROMETEO_V53__;return JSON.stringify(r.getState())})()' >"$ART/nav-1.json"
agent-browser --session "$S" eval 'document.getElementById("prometeo-v53").contentWindow.__PROMETEO_V53__.down();true' >/dev/null; agent-browser --session "$S" wait 380 >/dev/null
agent-browser --session "$S" eval '(()=>{const r=document.getElementById("prometeo-v53").contentWindow.__PROMETEO_V53__;return JSON.stringify(r.getState())})()' >"$ART/nav-2.json"
agent-browser --session "$S" eval 'document.getElementById("prometeo-v53").contentWindow.__PROMETEO_V53__.right();true' >/dev/null; agent-browser --session "$S" wait 520 >/dev/null
agent-browser --session "$S" eval '(()=>{const r=document.getElementById("prometeo-v53").contentWindow.__PROMETEO_V53__;return JSON.stringify(r.getState())})()' >"$ART/nav-3.json"
setvp 399 800; agent-browser --session "$S" wait 220 >/dev/null
agent-browser --session "$S" eval 'document.getElementById("prometeo-v53").contentWindow.__PROMETEO_V53__.left();true' >/dev/null; agent-browser --session "$S" wait 650 >/dev/null
agent-browser --session "$S" eval '(()=>{const r=document.getElementById("prometeo-v53").contentWindow.__PROMETEO_V53__;return JSON.stringify({state:r.getState(),normalize:r.backNormalizeInvariant?.(),layout:r.layout?.()})})()' >"$ART/nav-back-after-resize.json"
# Independent current-main products.
setvp 399 800
agent-browser --session "$S" navigate "${BASE}/pages/calendar/index.html" >/dev/null; agent-browser --session "$S" wait --load networkidle >/dev/null; agent-browser --session "$S" eval 'JSON.stringify({title:document.title,text:(document.body.innerText||"").slice(0,200),buttons:document.querySelectorAll("button").length,scrollW:document.documentElement.scrollWidth,innerW:innerWidth})' >"$ART/calendar.json"; agent-browser --session "$S" screenshot "$ART/calendar.png" --full >/dev/null
agent-browser --session "$S" navigate "${BASE}/arte/" >/dev/null; agent-browser --session "$S" wait --load networkidle >/dev/null; agent-browser --session "$S" eval 'JSON.stringify({title:document.title,text:(document.body.innerText||"").slice(0,200),links:document.querySelectorAll("a").length,scrollW:document.documentElement.scrollWidth,innerW:innerWidth})' >"$ART/arte.json"; agent-browser --session "$S" screenshot "$ART/arte.png" --full >/dev/null
agent-browser --session "$S" console --json >"$ART/console.json"; agent-browser --session "$S" errors --json >"$ART/errors.json"
export P3_ART="$ART"
node <<'NODE'
const fs=require('fs'),path=require('path'),{execFileSync}=require('child_process');const art=process.env.P3_ART;const parseEval=p=>{let x=JSON.parse(fs.readFileSync(p,'utf8').trim());if(typeof x==='string')x=JSON.parse(x);return x};const vps=fs.readdirSync(path.join(art,'viewports')).filter(x=>x.endsWith('.json')).sort().map(f=>({tag:f.replace('.json',''),...parseEval(path.join(art,'viewports',f))}));if(vps.length!==9)throw new Error('VIEWPORT_MATRIX_INCOMPLETE');for(const v of vps){if(v.build!=='PROMETEO_V53_COMPLETE_EXAMPLE_ATLAS_20260901'||v.rect.w<1||v.rect.h<1||!v.mainAria)throw new Error('VIEWPORT_FAIL '+JSON.stringify(v));}
const nav=[0,1,2,3].map(i=>parseEval(`${art}/nav-${i}.json`)),back=parseEval(`${art}/nav-back-after-resize.json`);if(nav[0].history.length!==0||nav[1].history.length<1)throw new Error('NAV_ENTER_FAIL');if(nav[3].history.length<2)throw new Error('NAV_DEPTH_FAIL '+JSON.stringify(nav));if(back.state.history.length!==nav[3].history.length-1)throw new Error('EXACT_BACK_HISTORY_FAIL');if(back.normalize?.canonical!==true)throw new Error('BACK_NOT_NORMALIZED '+JSON.stringify(back));const calendar=parseEval(`${art}/calendar.json`),arte=parseEval(`${art}/arte.json`);if(!/Calendario/i.test(calendar.title+calendar.text)||calendar.buttons<1)throw new Error('CALENDAR_FAIL');if(!/Adriana/i.test(arte.title+arte.text)||arte.links<1)throw new Error('ARTE_FAIL');const errors=JSON.parse(fs.readFileSync(`${art}/errors.json`,'utf8'))?.data?.errors||[],messages=JSON.parse(fs.readFileSync(`${art}/console.json`,'utf8'))?.data?.messages||[],consoleErrors=messages.filter(m=>String(m?.type||m?.level||'').toLowerCase()==='error');if(errors.length||consoleErrors.length)throw new Error('BROWSER_DIAGNOSTICS '+JSON.stringify({errors,consoleErrors}));const commit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();const evidence={schema:'prometeo.p3-macro-browser-evidence/v1',commit,runner:'agent-browser@0.34.0',viewports:vps,navigator:{initial:nav[0],entered:nav[1],vertical:nav[2],depth:nav[3],backAfterResize:back},independentProducts:{calendar,arte},diagnostics:{pageErrors:errors.length,consoleErrors:consoleErrors.length},performance:{viewportCount:vps.length,maxResourceFreeDomCheck:true},gates:{'P3-06':'PASS','P3-07':'PASS_WITH_SCOPE','P3-08':'PASS','P3-10':'PASS','P3-11':'PASS'}};fs.writeFileSync(`${art}/browser-evidence.json`,JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({ok:true,commit,viewports:vps.length,back:true,calendar:true,arte:true}));
NODE
