#!/usr/bin/env bash
set -euo pipefail
PORT="${P3_PORT:-4176}"; BASE="http://127.0.0.1:${PORT}"; NAV="${BASE}/navigator/"; ART="${P3_ARTIFACT_DIR:-artifacts/p3-macro}"; S="${P3_SESSION:-p3-macro}"
mkdir -p "$ART/viewports"
python3 -m http.server "$PORT" --bind 127.0.0.1 >"$ART/server.log" 2>&1 & SERVER_PID=$!
cleanup(){ agent-browser --session "$S" close >/dev/null 2>&1||true; kill "$SERVER_PID" >/dev/null 2>&1||true; wait "$SERVER_PID" >/dev/null 2>&1||true; }; trap cleanup EXIT
for _ in $(seq 1 40); do curl -fsS "$NAV" >/dev/null 2>&1 && break; sleep .25; done
agent-browser --session "$S" open >/dev/null
setvp(){ local w="$1"; local h="$2"; if agent-browser --session "$S" set viewport "$w" "$h" >/dev/null 2>&1; then return 0; fi; if agent-browser --session "$S" viewport "$w" "$h" >/dev/null 2>&1; then return 0; fi; echo "agent-browser viewport command unavailable" >&2; return 88; }
agent-browser --session "$S" navigate "$NAV" >/dev/null
agent-browser --session "$S" wait --load networkidle >/dev/null
agent-browser --session "$S" wait --fn "!!window.__PROMETEO_V53__" >/dev/null
checkvp(){ local w="$1"; local h="$2"; local tag="${w}x${h}"; setvp "$w" "$h"; agent-browser --session "$S" wait 160 >/dev/null; 
  agent-browser --session "$S" eval '(()=>{const d=document,r=window.__PROMETEO_V53__,rect=d.querySelector(".viewport")?.getBoundingClientRect();return JSON.stringify({outer:{w:innerWidth,h:innerHeight},rect:{w:rect?.width||0,h:rect?.height||0,left:rect?.left||0,top:rect?.top||0},build:window.__PROMETEO_BUILD__,title:d.title,mainAria:d.querySelector("main#viewport")?.getAttribute("aria-label"),tabIndex:d.querySelector("main#viewport")?.tabIndex,bodyScroll:{w:d.documentElement.scrollWidth,h:d.documentElement.scrollHeight},rootResponsiveDiagnostic:r.responsiveInvariant?.(),invariants:{depth:r.depthSlotsInvariant?.(),solver:r.edgeSolverInvariant?.(),seal:r.rightmostSealInvariant?.(),backplate:r.backplateInvariant?.(),horizontal:r.horizontalInvariant?.()},state:r.getState(),layout:r.layout?.()})})()' >"$ART/viewports/${tag}-root.json";
  agent-browser --session "$S" eval 'window.__PROMETEO_V53__.right();true' >/dev/null; agent-browser --session "$S" wait 430 >/dev/null;
  agent-browser --session "$S" eval '(()=>{const r=window.__PROMETEO_V53__;return JSON.stringify({state:r.getState(),responsive:r.responsiveInvariant?.(),vertical:r.verticalInvariant?.(),depth:r.depthSlotsInvariant?.(),solver:r.edgeSolverInvariant?.(),seal:r.rightmostSealInvariant?.(),backplate:r.backplateInvariant?.(),horizontal:r.horizontalInvariant?.(),layout:r.layout?.()})})()' >"$ART/viewports/${tag}-entered.json";
  if [[ "$tag" == "320x240" || "$tag" == "399x800" || "$tag" == "1280x720" ]]; then agent-browser --session "$S" screenshot "$ART/viewports/${tag}.png" --full >/dev/null; fi;
  agent-browser --session "$S" eval 'window.__PROMETEO_V53__.left();true' >/dev/null; agent-browser --session "$S" wait 430 >/dev/null;
}
for vp in 160x120 200x200 240x320 320x240 399x800 480x800 768x1024 1280x720 1440x900; do checkvp "${vp%x*}" "${vp#*x}"; done
setvp 1280 720
agent-browser --session "$S" navigate "$NAV" >/dev/null; agent-browser --session "$S" wait --load networkidle >/dev/null; agent-browser --session "$S" wait --fn "!!window.__PROMETEO_V53__" >/dev/null
agent-browser --session "$S" eval 'JSON.stringify(window.__PROMETEO_V53__.getState())' >"$ART/nav-0.json"
agent-browser --session "$S" eval 'window.__PROMETEO_V53__.right();true' >/dev/null; agent-browser --session "$S" wait 500 >/dev/null
agent-browser --session "$S" eval 'JSON.stringify(window.__PROMETEO_V53__.getState())' >"$ART/nav-1.json"
agent-browser --session "$S" eval 'window.__PROMETEO_V53__.down();true' >/dev/null; agent-browser --session "$S" wait 380 >/dev/null
agent-browser --session "$S" eval 'JSON.stringify(window.__PROMETEO_V53__.getState())' >"$ART/nav-2.json"
agent-browser --session "$S" eval 'window.__PROMETEO_V53__.right();true' >/dev/null; agent-browser --session "$S" wait 520 >/dev/null
agent-browser --session "$S" eval 'JSON.stringify(window.__PROMETEO_V53__.getState())' >"$ART/nav-3.json"
setvp 399 800; agent-browser --session "$S" wait 240 >/dev/null
agent-browser --session "$S" eval 'window.__PROMETEO_V53__.left();true' >/dev/null; agent-browser --session "$S" wait 650 >/dev/null
agent-browser --session "$S" eval 'JSON.stringify({state:window.__PROMETEO_V53__.getState(),normalize:window.__PROMETEO_V53__.backNormalizeInvariant?.(),layout:window.__PROMETEO_V53__.layout?.()})' >"$ART/nav-back-after-resize.json"
agent-browser --session "$S" console --json >"$ART/navigator-console.json"; agent-browser --session "$S" errors --json >"$ART/navigator-errors.json"
setvp 399 800
agent-browser --session "$S" navigate "${BASE}/pages/calendar/index.html" >/dev/null; agent-browser --session "$S" wait --load networkidle >/dev/null; agent-browser --session "$S" eval 'JSON.stringify({title:document.title,text:(document.body.innerText||"").slice(0,200),buttons:document.querySelectorAll("button").length,scrollW:document.documentElement.scrollWidth,innerW:innerWidth})' >"$ART/calendar.json"; agent-browser --session "$S" screenshot "$ART/calendar.png" --full >/dev/null; agent-browser --session "$S" console --json >"$ART/calendar-console.json"; agent-browser --session "$S" errors --json >"$ART/calendar-errors.json"
agent-browser --session "$S" navigate "${BASE}/arte/" >/dev/null; agent-browser --session "$S" wait --load networkidle >/dev/null; agent-browser --session "$S" eval 'JSON.stringify({title:document.title,text:(document.body.innerText||"").slice(0,200),links:document.querySelectorAll("a").length,scrollW:document.documentElement.scrollWidth,innerW:innerWidth})' >"$ART/arte.json"; agent-browser --session "$S" screenshot "$ART/arte.png" --full >/dev/null; agent-browser --session "$S" console --json >"$ART/arte-console.json"; agent-browser --session "$S" errors --json >"$ART/arte-errors.json"
export P3_ART="$ART"
node <<'NODE'
const fs=require('fs'),path=require('path'),{execFileSync}=require('child_process');const art=process.env.P3_ART;const parseEval=p=>{let x=JSON.parse(fs.readFileSync(p,'utf8').trim());if(typeof x==='string')x=JSON.parse(x);return x};
const roots=fs.readdirSync(path.join(art,'viewports')).filter(x=>x.endsWith('-root.json')).sort().map(f=>({tag:f.replace('-root.json',''),...parseEval(path.join(art,'viewports',f))}));const entered=fs.readdirSync(path.join(art,'viewports')).filter(x=>x.endsWith('-entered.json')).sort().map(f=>({tag:f.replace('-entered.json',''),...parseEval(path.join(art,'viewports',f))}));if(roots.length!==9||entered.length!==9)throw new Error('VIEWPORT_MATRIX_INCOMPLETE');
for(const v of roots){if(v.build!=='PROMETEO_V53_COMPLETE_EXAMPLE_ATLAS_20260901'||v.rect.w<1||v.rect.h<1||!v.mainAria)throw new Error('VIEWPORT_FAIL '+JSON.stringify(v));const ew=Math.min(v.outer.w,1500),eh=v.outer.w<=760?v.outer.h:Math.min(v.outer.h,760),el=(v.outer.w-ew)/2,et=(v.outer.h-eh)/2;if(Math.abs(v.rect.w-ew)>1||Math.abs(v.rect.h-eh)>1||Math.abs(v.rect.left-el)>1||Math.abs(v.rect.top-et)>1)throw new Error('CANONICAL_CAMERA_GEOMETRY '+JSON.stringify({v,expected:{ew,eh,el,et}}));if(v.bodyScroll.w>v.outer.w+1||v.bodyScroll.h>v.outer.h+1)throw new Error('ROOT_OVERFLOW '+JSON.stringify(v));for(const [k,x] of Object.entries(v.invariants||{}))if(x&&x.ok===false)throw new Error('ROOT_INVARIANT_'+k+' '+JSON.stringify({tag:v.tag,x}));}
for(const v of entered){if(v.state.history.length<1)throw new Error('RESPONSIVE_ENTRY_MISSING '+v.tag);if(v.responsive?.ok!==true)throw new Error('RESPONSIVE_ENTERED_FAIL '+JSON.stringify(v));for(const [k,x] of Object.entries({depth:v.depth,solver:v.solver,seal:v.seal,backplate:v.backplate,horizontal:v.horizontal}))if(x&&x.ok===false)throw new Error('ENTERED_INVARIANT_'+k+' '+JSON.stringify({tag:v.tag,x}));if(Array.isArray(v.vertical)&&v.vertical.some(x=>x.ok===false))throw new Error('VERTICAL_INVARIANT '+JSON.stringify(v));}
const nav=[0,1,2,3].map(i=>parseEval(`${art}/nav-${i}.json`)),back=parseEval(`${art}/nav-back-after-resize.json`);if(nav[0].history.length!==0||nav[1].history.length<1)throw new Error('NAV_ENTER_FAIL');if(nav[3].history.length<2)throw new Error('NAV_DEPTH_FAIL '+JSON.stringify(nav));if(back.state.history.length!==nav[3].history.length-1)throw new Error('EXACT_BACK_HISTORY_FAIL');if(back.normalize?.canonical!==true)throw new Error('BACK_NOT_NORMALIZED '+JSON.stringify(back));const calendar=parseEval(`${art}/calendar.json`),arte=parseEval(`${art}/arte.json`);if(!/Calendario/i.test(calendar.title+calendar.text)||calendar.buttons<1)throw new Error('CALENDAR_FAIL');if(!/Adriana/i.test(arte.title+arte.text)||arte.links<1)throw new Error('ARTE_FAIL');if(calendar.scrollW>calendar.innerW+2)throw new Error('CALENDAR_HORIZONTAL_OVERFLOW '+JSON.stringify(calendar));const diag={};for(const page of ['navigator','calendar','arte']){const errors=JSON.parse(fs.readFileSync(`${art}/${page}-errors.json`,'utf8'))?.data?.errors||[],messages=JSON.parse(fs.readFileSync(`${art}/${page}-console.json`,'utf8'))?.data?.messages||[],consoleErrors=messages.filter(m=>String(m?.type||m?.level||'').toLowerCase()==='error');diag[page]={pageErrors:errors.length,consoleErrors:consoleErrors.length};if(errors.length||consoleErrors.length)throw new Error('BROWSER_DIAGNOSTICS '+page+' '+JSON.stringify({errors,consoleErrors}));}const commit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();const evidence={schema:'prometeo.p3-macro-browser-evidence/v1',commit,runner:'agent-browser@0.34.0',rootViewports:roots,enteredViewports:entered,navigator:{initial:nav[0],entered:nav[1],vertical:nav[2],depth:nav[3],backAfterResize:back},independentProducts:{calendar,arte},diagnostics:diag,gates:{'P3-06':'PASS','P3-07':'PASS_WITH_SCOPE','P3-08':'PASS','P3-10':'PASS','P3-11':'PASS_BASIC_BROWSER'}};fs.writeFileSync(`${art}/browser-evidence.json`,JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({ok:true,commit,viewports:roots.length,enteredResponsive:entered.length,back:true,calendar:true,arte:true}));
NODE
