import json, pathlib, hashlib
root=pathlib.Path('.')
materialized='3ac361b8402dd355391467a81833310dcd61c658'; run_id=33873602023
payload='11528f5406ec8d93cb42c8bf3d98bf365fdf83b30bdfb3b9752f9219396432e2'
catalog_id='catalog-v1:31cb2fefb32e2ccda67100ec7e872c3e3c2a5b61+4d471d2721b3ead0bf5b00c3896fdd5abc79b348'
def load(p): return json.loads((root/p).read_text(encoding='utf-8'))
def save(p,v): (root/p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def stable(v):
    if v is None:return 'null'
    if v is True:return 'true'
    if v is False:return 'false'
    if isinstance(v,(int,float)):return json.dumps(v,separators=(',',':'),ensure_ascii=False)
    if isinstance(v,str):return json.dumps(v,separators=(',',':'),ensure_ascii=False)
    if isinstance(v,list):return '['+','.join(stable(x) for x in v)+']'
    return '{'+','.join(json.dumps(k,ensure_ascii=False)+':'+stable(v[k]) for k in sorted(v))+'}'
m=load('coordination/PART2_CANDIDATE_MANIFEST.json');m['status']='TESTED_CANDIDATE_GITHUB_CI_PASS';m['github_materialization']={'tested_source_head':'0e9896fbd12bbd190ef4a0d1d6fa6466c740e845','materialized_commit':materialized,'workflow_run':run_id,'conclusion':'success','payload_sha256':payload,'transport_removed':True};m['phases']={k:'PASS_GITHUB_CI' for k in m['phases']};m['next_gate']='PART2_ADVERSARIAL_AUDIT_AND_PART3_PREP';m['tested_receipt']='R-P2-COMPLETE-0003';save('coordination/PART2_CANDIDATE_MANIFEST.json',m)
p=load('state/PENDING.json');p['items']=[{'id':'PENDING-PART2-AUDIT-001','title':'Adversarially critique and repair Part 2; prepare Part 3','state':'READY','owner':'single-worker','dependencies':['R-P2-COMPLETE-0003'],'blocker':None,'next_action':'Attack Part 2 durable truth, context/privacy, workflow, lineage, receipts and reincarnation; repair findings; compile Part 3 execution plan without starting Part 3 production.','source_frontier':{'part2_materialized_commit':materialized,'github_ci_run':run_id,'catalog_identity':catalog_id}}];save('state/PENDING.json',p)
g=load('state/CURRENT_GRAPH.json');g['revision']=2;g['artifacts']['part2-workstream']={'state':'TESTED_CANDIDATE','source':'gitcommit:'+materialized,'product':'prometeo-platform'};g['artifacts']['classes-runtime-v2']={'state':'TESTED_CANDIDATE','source':'path:shared/classes/runtime/v2','product':'classes-runtime'};g['artifacts']['student-world-runtime-v2']={'state':'TESTED_CANDIDATE','source':'path:shared/student-world/runtime/v2','product':'student-world-runtime'};g['artifacts']['context-foundry-v2']={'state':'TESTED_CANDIDATE','source':'path:shared/context-foundry/v2','product':'context-foundry'};g['pointers']['candidate_current']={'artifact_id':'part2-workstream','receipt_id':'R-P2-COMPLETE-0003'};g['active_workstream']={'branch':'candidate/part2-durable-metabolism-20260904','phase':'PART2_AUDIT_PREP','status':'READY_FOR_ADVERSARIAL_AUDIT','parent_commit':'936d4217cb9ce1e244722e76e5843d8aadbb31f6','materialized_commit':materialized};g['pending_work']=['PENDING-PART2-AUDIT-001'];g['last_durable_receipt']='R-P2-COMPLETE-0003';save('state/CURRENT_GRAPH.json',g)
save('state/HEAD.json',{'schema':'prometeo.head/v1','namespace':'prometeo','artifact_id':'part2-workstream','source':'gitcommit:'+materialized,'receipt_id':'R-P2-COMPLETE-0003'});save('state/DOT_STATE.json',{'schema':'prometeo.dot-state/v1','phase':'PART2_AUDIT_PREP','state':'READY','active_branch':'candidate/part2-durable-metabolism-20260904','next_gate':'PART2_ADVERSARIAL_AUDIT_AND_PART3_PREP','last_receipt':'R-P2-COMPLETE-0003'})
lp=root/'receipts/ledger.jsonl';rows=[json.loads(x) for x in lp.read_text(encoding='utf-8').splitlines() if x.strip()]
if not any(x['id']=='R-P2-COMPLETE-0003' for x in rows):
 r={'schema':'prometeo.receipt/v1','id':'R-P2-COMPLETE-0003','type':'PART2_TESTED_CANDIDATE','operation_id':'OP-P2-MATERIALIZE-CERTIFY','work_item_id':'PENDING-PART2-001','actor':'Prometeo Candidate CI + single-worker','model':None,'base_artifact':'gitcommit:936d4217cb9ce1e244722e76e5843d8aadbb31f6','source_digests':['gitblob:7ca5f3e223ca843e3f9e4b7be1e53b5b65dd3418','gitblob:31cb2fefb32e2ccda67100ec7e872c3e3c2a5b61','gitblob:4d471d2721b3ead0bf5b00c3896fdd5abc79b348','sha256:'+payload],'files_changed':['catalog/','context/','golden/','lineage/','receipts/','reincarnation/','runtime/','schemas/','shared/','state/','tests/'],'output_digests':['gitcommit:'+materialized],'tests':['github-actions:33873602023:success','PART1_REGRESSION_PASS','PART2_SUITE_PASS','JS_SYNTAX_PASS','JSON_PARSE_PASS'],'privacy_decisions':['LOCAL_INHERITANCE_FAIL_CLOSED','EXPLICIT_ID_DOES_NOT_BYPASS_PRIVACY','EXTERNAL_LOCAL_PACK_BLOCKED'],'candidate_identity':'gitcommit:'+materialized,'acceptance_identity':None,'served_identity':None,'rollback_refs':['gitcommit:936d4217cb9ce1e244722e76e5843d8aadbb31f6','sha256:f15f67240794b9d3224cc11f1899819485c08554b517b48ea6fca8458eb41398'],'timestamp':'2026-09-04T12:36:24Z','claim':'Part 2 durable metabolism was materialized as normal repository files and passed the full Part 1 regression plus Part 2 verification suite before commit. Candidate only; no Human Accepted or Served pointer moved.','prev_hash':rows[-1]['hash']};r['hash']=hashlib.sha256(stable(r).encode()).hexdigest();rows.append(r)
lp.write_text('\n'.join(json.dumps(x,ensure_ascii=False,separators=(',',':')) for x in rows)+'\n',encoding='utf-8')
rp=root/'coordination/PART2_EXECUTION_REPORT.md';t=rp.read_text(encoding='utf-8').replace('Status: **LOCAL_TESTED_CANDIDATE — GITHUB CI PENDING — NOT HUMAN ACCEPTED — NOT SERVED**','Status: **TESTED_CANDIDATE — GITHUB CI PASS — NOT HUMAN ACCEPTED — NOT SERVED**')
if '## GitHub materialization certification' not in t:t+=f'\n\n## GitHub materialization certification\n- Payload SHA-256 `{payload}` verified.\n- Materialization run `{run_id}`: **SUCCESS**.\n- Materialized commit `{materialized}`.\n- Part 1 regressions + Part 2 suite + syntax + JSON passed before materialization commit.\n- Temporary transport removed. No Human Accepted or Served pointer moved.\n\n## Handoff\nPart 2 production is complete for this stage. Next: `PENDING-PART2-AUDIT-001` (critique/repair Part 2 + prepare Part 3). Part 3 production has not started.\n'
rp.write_text(t,encoding='utf-8')
ci='''name: Part 2 Candidate CI\non:\n  push:\n    branches: [candidate/part2-durable-metabolism-20260904]\n  workflow_dispatch:\npermissions:\n  contents: read\njobs:\n  verify:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Verify all candidate tests\n        shell: bash\n        run: |\n          set -euo pipefail\n          for f in tests/r1_candidate.test.mjs tests/runtime-ownership.test.mjs tests/platform-engines.test.mjs tests/part1-static.test.mjs tests/part1-contract.test.mjs tests/part1-runtime-services.test.mjs tests/part1-persistent-engines.test.mjs tests/part1-semantic-restore.test.mjs tests/part1-persistence-cas.test.mjs tests/part1-engine-invariants.test.mjs; do test -f "$f" && node "$f"; done\n          for f in tests/part2-*.test.mjs; do node "$f"; done\n          find shared -type f -name '*.js' -print0 | xargs -0 -n1 node --check\n          python - <<'PY'\n          import json,pathlib\n          for p in pathlib.Path('.').rglob('*.json'):\n              if '.git' not in p.parts:\n                  with p.open(encoding='utf-8') as f: json.load(f)\n          PY\n          test ! -e .transport/part2\n          test "$(git hash-object navigator/index.html)" = "7ca5f3e223ca843e3f9e4b7be1e53b5b65dd3418"\n          grep -q 'TESTED_CANDIDATE_GITHUB_CI_PASS' coordination/PART2_CANDIDATE_MANIFEST.json\n          grep -q 'R-P2-COMPLETE-0003' state/CURRENT_GRAPH.json\n          grep -q 'PENDING-PART2-AUDIT-001' state/PENDING.json\n'''
(root/'.github/workflows/part2-candidate-ci.yml').write_text(ci,encoding='utf-8')
(root/'.github/workflows/part2-finalize.yml').unlink(missing_ok=True)
pathlib.Path(__file__).unlink(missing_ok=True)
