const api=typeof browser!=='undefined'?browser:chrome;
const BB_API='https://catnohyouxqjjtseaueb.supabase.co/functions/v1/study-blackboard-v1';
const BB_INGEST=BB_API+'?action=ingest';
const BB_DATA=BB_API+'?action=data';
const BB_FILES='https://catnohyouxqjjtseaueb.supabase.co/functions/v1/study-blackboard-files-v1';
const BB_WORKSPACE='colo-study';
let bbRunning=null;
async function bbStore(){const x=await api.storage.local.get(['studyToken','deviceId','lastSync']);if(!x.deviceId){x.deviceId=crypto.randomUUID();await api.storage.local.set({deviceId:x.deviceId})}return x}
function bbHeaders(token){return{'x-study-token':token,'x-study-workspace':BB_WORKSPACE}}
async function bbIngest(payload){const s=await bbStore();if(!s.studyToken)throw new Error('not_paired');const r=await fetch(BB_INGEST,{method:'POST',credentials:'omit',headers:{'content-type':'application/json',...bbHeaders(s.studyToken)},body:JSON.stringify({...payload,device_id:s.deviceId})});if(!r.ok)throw new Error('ingest_'+r.status);return r.json()}
async function bbKnownCourseUrls(token){try{const r=await fetch(BB_DATA,{headers:bbHeaders(token),cache:'no-store'});if(!r.ok)return[];const d=await r.json();return [...new Set((d.courses||[]).map(x=>x.href).filter(x=>x&&x.startsWith(BB_BASE)))]}catch{return[]}}
async function bbNotify(data){const tabs=await api.tabs.query({url:'https://juanmanuelpm.github.io/prometeo/pages/study-library/*'}).catch(()=>[]);for(const t of tabs)if(t.id!=null)api.tabs.sendMessage(t.id,{type:'PROMETEO_BB_EVENT',data}).catch(()=>{})}
async function bbFetchPage(url){const r=await fetch(url,{credentials:'include',redirect:'follow',cache:'no-store',headers:{accept:'text/html,application/xhtml+xml'}});const ct=r.headers.get('content-type')||'';if(!r.ok||!ct.includes('text/html'))return null;return{url:r.url||url,...parseBBPage(await r.text(),r.url||url)}}
function bbNameFromDisposition(cd,fallback){const m=String(cd||'').match(/filename\*?=(?:UTF-8''|"?)([^";]+)/i);if(!m)return fallback;try{return decodeURIComponent(m[1].replace(/^"|"$/g,''))}catch{return m[1].replace(/^"|"$/g,'')}}
async function bbMirrorFiles(items=[]){
 const s=await bbStore();if(!s.studyToken)return{mirrored:0,skipped:0,failed:0,candidates:0,errors:['not_paired']};let known=[];try{const r=await fetch(BB_FILES+'?action=index',{headers:bbHeaders(s.studyToken),cache:'no-store'});if(r.ok)known=(await r.json()).files||[]}catch{}
 const km=new Map(known.map(x=>[x.item_key,x])),cut=Date.now()-12*60*60*1000;
 const candidates=items.filter(x=>x?.item_type==='file'&&x.href&&!/\.(mp4|mov|avi|mkv|webm|wav|flac)(?:[?#]|$)/i.test(x.href)).filter(x=>!km.has(x.item_key)||new Date(km.get(x.item_key).mirrored_at||0).getTime()<cut).slice(0,80);
 let mirrored=0,skipped=0,failed=0,index=0;const errors=[];
 async function worker(){while(index<candidates.length){const x=candidates[index++];try{const r=await fetch(x.href,{credentials:'include',redirect:'follow',cache:'no-store'});if(!r.ok)throw new Error('file_'+r.status);const ct=(r.headers.get('content-type')||'application/octet-stream').split(';')[0].trim();if(/text\/html/i.test(ct)){skipped++;if(errors.length<6)errors.push('html:'+String(x.title||x.href).slice(0,100));continue}const len=Number(r.headers.get('content-length')||0);if(len>52428800){skipped++;continue}const blob=await r.blob();if(blob.size>52428800||!blob.size){skipped++;continue}const fd=new FormData();fd.append('item_key',x.item_key);fd.append('course_key',x.course_key||'');fd.append('source_url',x.href);fd.append('file_name',bbNameFromDisposition(r.headers.get('content-disposition'),x.file_name||x.title||'archivo'));fd.append('file',new File([blob],x.file_name||x.title||'archivo',{type:ct}));const up=await fetch(BB_FILES+'?action=upload',{method:'POST',headers:bbHeaders(s.studyToken),body:fd});if(!up.ok){let detail='';try{detail=(await up.json()).error||''}catch{}throw new Error('mirror_'+up.status+(detail?':'+detail:''))}mirrored++;if((mirrored+failed)%4===0)await bbNotify({state:'mirroring',mirrored,remaining:Math.max(0,candidates.length-mirrored-skipped-failed),at:Date.now()})}catch(e){failed++;if(errors.length<6)errors.push(String(e?.message||e).slice(0,160))}}}
 await Promise.all([worker(),worker(),worker()]);return{mirrored,skipped,failed,candidates:candidates.length,errors}
}
async function bbSync(reason='manual'){
 if(bbRunning)return bbRunning;
 bbRunning=(async()=>{const store=await bbStore();await bbNotify({state:'syncing',reason,at:Date.now()});const known=store.studyToken?await bbKnownCourseUrls(store.studyToken):[],queue=[BB_BASE+'/',BB_BASE+'/ultra/course',BB_BASE+'/webapps/portal/execute/tabs/tabAction?tab_tab_group_id=_1_1',...known],seen=new Set(),courses=new Map(),items=new Map();let pages=0,login=false;
 while(queue.length&&pages<120&&items.size<2600){const url=queue.shift();if(!url||seen.has(url))continue;seen.add(url);let p=null;try{p=await bbFetchPage(url)}catch{}if(!p)continue;if(p.password||/login|auth/i.test(new URL(p.url).pathname)){login=true;continue}pages++;for(const c of p.courses){const prev=courses.get(c.course_key);if(!prev||bbCourseTitleScore(c.title,c.course_key)>=bbCourseTitleScore(prev.title,prev.course_key))courses.set(c.course_key,{...prev,...c})}for(const x of p.items)if(items.size<2600)items.set(x.item_key,x);for(const h of p.enqueue)if(!seen.has(h)&&!queue.includes(h)&&bbUseful(h))queue.push(h);if(pages%8===0)await bbNotify({state:'syncing',pages,courses:courses.size,items:items.size,at:Date.now()})}
 if(!pages&&login){await bbNotify({state:'needs_login',at:Date.now()});return{ok:false,needs_login:true}}
 if(!pages){const out={state:'error',error:'Abrí Blackboard una vez y volvé a sincronizar.',at:Date.now()};await bbNotify(out);return{ok:false,...out}}
 const all=[...items.values()],result=await bbIngest({courses:[...courses.values()],items:all,pages}),mirror=await bbMirrorFiles(all),out={state:'ok',pages,courses:courses.size,items:items.size,files:mirror,ingest:result?.ingest||{},at:Date.now()};await api.storage.local.set({lastSync:out});await bbNotify(out);return{ok:true,...out}})().finally(()=>bbRunning=null);return bbRunning
}
api.runtime.onInstalled.addListener(()=>api.alarms.create('prometeo-bb-auto',{periodInMinutes:15}));
api.alarms.onAlarm.addListener(a=>{if(a.name==='prometeo-bb-auto')api.storage.local.get('studyToken').then(x=>x.studyToken&&bbSync('auto')).catch(()=>{})});
api.runtime.onMessage.addListener(m=>{if(!m)return;if(m.type==='PAIR')return api.storage.local.set({studyToken:m.token,workspace:BB_WORKSPACE}).then(()=>{api.alarms.create('prometeo-bb-auto',{periodInMinutes:15});return bbSync('pair')});if(m.type==='SYNC')return bbSync('manual');if(m.type==='STATUS')return bbStore().then(x=>({paired:!!x.studyToken,lastSync:x.lastSync||null,running:!!bbRunning}));if(m.type==='OPEN_BLACKBOARD')return api.tabs.create({url:BB_BASE+'/'});if(m.type==='PAGE_SNAPSHOT'&&m.payload)return bbIngest({courses:m.payload.courses||[],items:m.payload.items||[],pages:1}).then(async()=>{const mirror=await bbMirrorFiles(m.payload.items||[]);await bbNotify({state:'page_captured',url:m.payload.url,files:mirror,at:Date.now()})}).catch(()=>{})});
