const bbApi2=typeof browser!=='undefined'?browser:chrome;
const bbC=(x,n=2000)=>String(x||'').replace(/\s+/g,' ').trim().slice(0,n);
function bbCourse(url){try{const u=new URL(url),q=u.searchParams;if(q.get('course_id'))return q.get('course_id');if(q.get('courseId'))return q.get('courseId');if((q.get('type')||'').toLowerCase()==='course'&&q.get('id'))return q.get('id');const m=u.pathname.match(/\/courses\/([^/?#]+)/i);return m?decodeURIComponent(m[1]):''}catch{return''}}
function bbF(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
const bbIsFile=(h,t='')=>/bbcswebdav|\.(pdf|pptx?|docx?|xlsx?|zip|rar|7z|txt|csv|jpg|jpeg|png|mp4|mp3)(?:[?#]|$)|download|attachment/i.test(h+' '+t);
function bbTitleScore(t,k=''){const s=bbC(t,500),n=s.toLowerCase();let q=Math.min(40,s.length/4);if(!s)q-=100;if(/\.(png|jpe?g|gif|pdf|pptx?|docx?|xlsx?|zip)$/i.test(s))q-=80;if(/^https?:|abrir enlaces rapidos|enlaces rapidos|ir$/i.test(n))q-=70;if(/202\dC\dC_/i.test(s))q+=45;if(k&&s.includes(k))q+=18;if(/\([^)]*202\dC\dC_[^)]+\)/i.test(s))q+=35;return q}
function bbPretty(label='',code=''){let s=bbC(label,500)||String(code||'').replace(/^202\dC\dC_/i,'');s=s.replace(/^[-\s]+/,'').replace(/\s*\([^)]*\)\s*$/,'').replace(/_M_[A-Z]{2}_[\d.]+-\d{2}_\d{2}_\d{4}.*$/i,'').replace(/_M_[A-Z]{2}_[\d.]+.*$/i,'').replace(/_/g,' ').replace(/\s+/g,' ').trim();return s||code}
function bbCode(text=''){const m=String(text).match(/202\dC\dC_[A-Z0-9ÁÉÍÓÚÑ._-]+/i);return m?m[0]:''}
function bodyCourses(text=''){const out=new Map(),re=/-?([A-ZÁÉÍÓÚÑ0-9._-]{5,}?)\s*\((202\dC\dC_[^)]+)\)/gi;let m;while((m=re.exec(String(text||'')))){const code=bbC(m[2],300),label=bbPretty(m[1],code);if(code)out.set(code,{course_key:code,title:`${label} (${code})`,href:'',raw:{captured:true,via:'page_text'}})}return [...out.values()]}
function snapshot(){
  const url=location.href,ck=bbCourse(url),title=bbC(document.querySelector('h1')?.textContent||document.querySelector('#pageTitleText')?.textContent||document.title,500),courses=[],items=[],seen=new Set(),courseMap=new Map();
  const addCourse=(k,n,h,raw={})=>{if(!k)return;const next={course_key:k,title:bbC(n,500)||k,href:bbIsFile(h,n)?'':h,raw:{captured:true,...raw}},prev=courseMap.get(k);if(!prev||bbTitleScore(next.title,k)>bbTitleScore(prev.title,k)||(!prev.href&&next.href))courseMap.set(k,{...prev,...next});};if(ck&&!bbIsFile(url,title))addCourse(ck,title,url,{via:'page'});
  const body=bbC(document.body?.innerText||'',30000);for(const c of bodyCourses(body))addCourse(c.course_key,c.title,c.href,c.raw);
  for(const a of [...document.querySelectorAll('a[href]')].slice(0,1600)){
    let href='';try{href=new URL(a.href,location.href).href}catch{}if(!href||!href.startsWith(location.origin))continue;const text=bbC(a.textContent||a.title||a.getAttribute('aria-label'),600),near=bbC(a.closest('li,article,div,tr')?.textContent||'',1200),k=bbCourse(href)||ck||bbCode(near);if(k&&!bbIsFile(href,text))addCourse(k,/^202\dC\dC_/i.test(k)?bbPretty('',k):text,href,{via:'link'});if(!text&&!bbIsFile(href,text))continue;const type=bbIsFile(href,text)?'file':/announcement|anuncio/i.test(href+' '+text)?'announcement':/assignment|assessment|test|quiz|submit/i.test(href+' '+text)?'assignment':'link';if(type==='link'&&!k)continue;const key=(k||'global')+':live:'+bbF((a.id||href)+'|'+text);if(seen.has(key))continue;seen.add(key);items.push({item_key:key,course_key:k||null,item_type:type,title:text||href.split('/').pop()||type,href,source_page:url,raw:{live:true}})}
  courses.push(...courseMap.values());
  const pk=(ck||'global')+':livepage:'+bbF(url);items.push({item_key:pk,course_key:ck||null,item_type:/announcement/i.test(url)?'announcement-page':/calendar/i.test(url)?'calendar-page':/stream/i.test(url)?'activity-page':/message/i.test(url)?'messages-page':'page',title:title||url,body_text:body,href:url,source_page:url,raw:{live:true}});
  return{url,courses,items};
}
function sendSnapshot(){bbApi2.runtime.sendMessage({type:'PAGE_SNAPSHOT',payload:snapshot()}).catch(()=>{})}
setTimeout(sendSnapshot,1600);setTimeout(sendSnapshot,5000);
if(!document.getElementById('prometeo-bb-dot')){
 const b=document.createElement('button');b.id='prometeo-bb-dot';b.textContent='P';b.title='Sincronizar con Prometeo';Object.assign(b.style,{position:'fixed',right:'10px',bottom:'10px',zIndex:'2147483647',width:'28px',height:'28px',border:'1px solid rgba(0,0,0,.25)',background:'#111326',color:'#d8d1ff',font:'700 11px system-ui',opacity:'.42',cursor:'pointer'});b.onmouseenter=()=>b.style.opacity='.92';b.onmouseleave=()=>b.style.opacity='.42';b.onclick=async()=>{b.textContent='…';try{sendSnapshot();await bbApi2.runtime.sendMessage({type:'SYNC'});b.textContent='✓';setTimeout(()=>b.textContent='P',1500)}catch{b.textContent='!'}};document.documentElement.appendChild(b)
}
