const BB_BASE='https://palermo.blackboard.com';
const bbClean=(x,n=2000)=>String(x||'').replace(/\s+/g,' ').trim().slice(0,n);
const bbAbs=(x,b=BB_BASE)=>{try{return new URL(x,b).href}catch{return ''}};
function bbHash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
function bbCourseKey(url){try{const u=new URL(url),q=u.searchParams;if(q.get('course_id'))return q.get('course_id');if(q.get('courseId'))return q.get('courseId');if((q.get('type')||'').toLowerCase()==='course'&&q.get('id'))return q.get('id');const m=u.pathname.match(/\/courses\/([^/?#]+)/i);return m?decodeURIComponent(m[1]):''}catch{return''}}
const bbCourseLink=h=>/course_id=|courseId=|type=Course|\/courses\//i.test(h);
function bbUseful(h){return !!h&&h.startsWith(BB_BASE)&&!/logout|logoff|delete|remove|modify|editMode|gradebook\/do|email/i.test(h)&&/course_id=|courseId=|type=Course|\/courses\/|\/ultra\/course|outline|listContent|announcement|message|mygrades|grade|content|calendar|bbcswebdav|attachment|resource/i.test(h)}
const bbFile=(h,t='')=>/bbcswebdav|\.(pdf|pptx?|docx?|xlsx?|zip|rar|7z|txt|rtf|csv|jpg|jpeg|png|gif|mp4|mp3|wav)(?:[?#]|$)/i.test(h)||/download|attachment|\.pdf|\.ppt|\.doc|\.xls|\.zip/i.test(h+' '+t);
const bbAssignment=(h,t='')=>/assignment|assessment|test|quiz|gradable|submit/i.test(h+' '+t);
const bbAnnouncement=(h,t='')=>/announcement|anuncio/i.test(h+' '+t);
const bbMessage=(h,t='')=>/message|mensaj/i.test(h+' '+t);
function bbDue(text){const m=bbClean(text,900).match(/(?:fecha de entrega|vencimiento|vence|due date|due)\s*[:\-]?\s*(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})(?:\s+(\d{1,2}):(\d{2}))?/i);if(!m)return null;let y=+m[3];if(y<100)y+=2000;const d=new Date(y,+m[2]-1,+m[1],+(m[4]||23),+(m[5]||59));return isNaN(d)?null:d.toISOString()}
function bbPageType(url,title=''){const s=(url+' '+title).toLowerCase();return s.includes('announcement')?'announcement-page':s.includes('message')?'messages-page':s.includes('grade')?'grades-page':s.includes('calendar')?'calendar-page':'page'}
function bbCourseTitleScore(title,key=''){const t=bbClean(title,500),n=t.toLowerCase();let s=Math.min(40,t.length/4);if(!t)s-=100;if(/\.(png|jpe?g|gif|pdf|pptx?|docx?|xlsx?|zip)$/i.test(t))s-=80;if(/^https?:|abrir enlaces rapidos|enlaces rapidos|ir$/i.test(n))s-=70;if(/202\dC\dC_/i.test(t))s+=45;if(/[A-Z_]{8,}/.test(t))s+=12;if(key&&t.includes(key))s+=18;if(/\([^)]*202\dC\dC_[^)]+\)/i.test(t))s+=35;return s}
function parseBBPage(html,url){
 const d=new DOMParser().parseFromString(html,'text/html'),title=bbClean(d.querySelector('h1')?.textContent||d.querySelector('#pageTitleText')?.textContent||d.title||'',500),password=!!d.querySelector('input[type=password]'),body=bbClean(d.body?.innerText||d.body?.textContent||'',20000),ck=bbCourseKey(url),courses=new Map(),items=new Map(),enqueue=[];
 const addCourse=(k,n,h)=>{if(!k)return;const next={course_key:k,title:bbClean(n,500)||k,href:h||'',raw:{discovered_from:url}},prev=courses.get(k);if(!prev||bbCourseTitleScore(next.title,k)>bbCourseTitleScore(prev.title,k))courses.set(k,{...prev,...next});else if(prev&&!prev.href&&h)prev.href=h};if(ck)addCourse(ck,title,url);
 for(const a of d.querySelectorAll('a[href]')){const href=bbAbs(a.getAttribute('href'),url);if(!href||!href.startsWith(BB_BASE))continue;const text=bbClean(a.textContent||a.title||a.getAttribute('aria-label')||'',600),k=bbCourseKey(href)||ck;if(bbCourseLink(href))addCourse(bbCourseKey(href),text,href);let type='link';if(bbFile(href,text))type='file';else if(bbAssignment(href,text))type='assignment';else if(bbAnnouncement(href,text))type='announcement';else if(bbMessage(href,text))type='message-link';if(type!=='link'||(text&&k)){const stable=(a.id||a.closest('[id]')?.id||href).slice(0,1200),key=(k||'global')+':'+bbHash(stable+'|'+text);items.set(key,{item_key:key,course_key:k||null,item_type:type,title:text||href.split('/').pop()||type,href,file_name:type==='file'?(text||null):null,due_at:bbDue(a.closest('li,article,div,tr')?.textContent||''),source_page:url,raw:{anchor_id:a.id||null}})}if(bbUseful(href))enqueue.push(href)}
 for(const b of [...d.querySelectorAll('li[id^="contentListItem"],.contentListItem,.liItem,.announcementList li,[class*="announcement"]')].slice(0,450)){const text=bbClean(b.innerText||b.textContent||'',4000);if(text.length<3)continue;const a=b.querySelector('a[href]'),href=a?bbAbs(a.getAttribute('href'),url):url,type=bbAnnouncement(href,text)?'announcement':bbAssignment(href,text)?'assignment':'content',key=(ck||bbCourseKey(href)||'global')+':block:'+(b.id||bbHash(text.slice(0,500)+href));items.set(key,{item_key:key,course_key:ck||bbCourseKey(href)||null,item_type:type,title:bbClean(b.querySelector('h2,h3,h4,.item')?.textContent||a?.textContent||text,800),body_text:text,href,due_at:bbDue(text),source_page:url,raw:{dom_id:b.id||null}})}
 const pk=(ck||'global')+':page:'+bbHash(url);items.set(pk,{item_key:pk,course_key:ck||null,item_type:bbPageType(url,title),title:title||url,body_text:body,href:url,due_at:bbDue(body),source_page:url,raw:{}});
 return{title,password,courses:[...courses.values()],items:[...items.values()],enqueue:[...new Set(enqueue)]};
}
