(()=>{'use strict';
const API='https://catnohyouxqjjtseaueb.supabase.co/functions/v1/modelos-room-audio-v2';
const VOICE_PROMPT='Argentine male teacher. Warm medium-low voice, clear and patient. Natural Rioplatense Spanish. Explain as if to one student, with brief useful pauses. Same speaker throughout.';
const POST_GAP=3400,WORKERS=3,MAX_CHARS=450;
const UNITS=[
{id:'u1',title:'Unidad 1 · Memoria y aprendizaje',paras:[
'La memoria no funciona como un depósito pasivo en el que la información queda guardada sin cambios. Recordar implica seleccionar, organizar y reconstruir. Por eso, lo que una persona recuerda depende tanto de la información original como de la manera en que fue procesada y recuperada.',
'Para estudiar conviene distinguir entre codificación, almacenamiento y recuperación. La codificación transforma la información para que pueda ser representada; el almacenamiento permite conservarla; y la recuperación vuelve disponible una representación cuando la necesitamos. Una falla en cualquiera de estos momentos puede sentirse como olvido.',
'El aprendizaje mejora cuando la persona relaciona ideas nuevas con conocimientos previos, produce ejemplos propios y vuelve sobre el material en distintos momentos. La repetición mecánica puede ayudar a mantener algo durante poco tiempo, pero suele ser menos sólida que una elaboración activa.' ]},
{id:'u2',title:'Unidad 2 · Atención y selección',paras:[
'La atención permite priorizar una parte de la información disponible. No significa que el resto del ambiente desaparezca, sino que ciertos estímulos reciben más recursos de procesamiento que otros. Esta selección cambia según la tarea, las expectativas y el estado de la persona.',
'Cuando una tarea exige sostener la atención durante mucho tiempo, el rendimiento puede fluctuar. También aparece interferencia cuando dos actividades compiten por recursos similares. Por eso, dividir una actividad compleja en tramos claros puede reducir errores y hacer más visible el progreso.',
'En una situación de estudio, orientar la atención no consiste solamente en eliminar distractores. También importa saber qué buscar: una pregunta previa, un concepto central o una relación concreta pueden organizar la lectura y evitar que todo el texto parezca igualmente importante.' ]},
{id:'u3',title:'Unidad 3 · Recuperación y práctica',paras:[
'Releer produce familiaridad, pero familiaridad no es lo mismo que poder recuperar una idea sin ayuda. La práctica de recuperación obliga a reconstruir la información y permite detectar con bastante precisión qué partes todavía son frágiles.',
'Una pregunta útil puede funcionar como una clave de recuperación. Si la respuesta aparece con demasiado apoyo, la sensación de dominio puede ser engañosa. En cambio, intentar responder antes de mirar la solución genera una evidencia más informativa sobre lo que realmente se sabe.',
'La práctica distribuida agrega otro componente importante: volver sobre el contenido después de cierto intervalo. Cada recuperación exitosa fortalece rutas de acceso y permite combinar repaso, corrección y nuevas conexiones sin depender de una única sesión extensa.' ]}
];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
function chunkText(text){const sentences=text.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[text];const out=[];let cur='';for(const raw of sentences){const s=raw.trim();if(!s)continue;if((cur+' '+s).trim().length<=MAX_CHARS){cur=(cur+' '+s).trim();continue}if(cur)out.push(cur);if(s.length<=MAX_CHARS){cur=s;continue}let rest=s;while(rest.length>MAX_CHARS){let cut=rest.lastIndexOf(' ',MAX_CHARS);if(cut<220)cut=MAX_CHARS;out.push(rest.slice(0,cut).trim());rest=rest.slice(cut).trim()}cur=rest}if(cur)out.push(cur);return out}
function makeState(unit){const full=unit.paras.join(' ');const texts=chunkText(full);let pos=0;const chunks=texts.map((text,i)=>{const start=pos,end=pos+text.length;pos=end;return{i,text,start,end,status:'idle',audio:null,url:null,attempts:0,queued:false}});return{unit,chunks,total:Math.max(1,pos),current:0,intent:false,playing:false,pendingLocal:0,views:[],lastRatio:0}}
const states=new Map(UNITS.map(u=>[u.id,makeState(u)]));
let activeUnit=null,queue=[],activeJobs=0,lastPost=0,postGate=Promise.resolve();
const preloadStatus=document.getElementById('preloadStatus');
function msgId(st,c){return `summary-compare-v1-julian-${st.unit.id}-${c.i}-${hash(c.text)}`}
function svg(){return `<svg class="play" viewBox="0 0 12 14" aria-hidden="true"><path d="M2.2 1.5c0-.7.77-1.12 1.36-.75l7.1 4.45c.55.35.55 1.15 0 1.5l-7.1 4.45a.88.88 0 0 1-1.36-.75V1.5Z" fill="currentColor"/></svg><svg class="pause" viewBox="0 0 12 14" aria-hidden="true"><rect x="1" y="1" width="3" height="12" rx="1" fill="currentColor"/><rect x="8" y="1" width="3" height="12" rx="1" fill="currentColor"/></svg>`}
function unitHTML(u){return `<article class="unit" data-unit="${u.id}"><div class="rail"><div class="railTrack"><div class="railBuffer"></div><div class="railFill"></div><button class="railThumb" aria-label="Reproducir ${u.title}" data-playing="0">${svg()}</button></div></div><h3 class="unitTitle">${u.title}</h3><div class="unitText">${u.paras.map(p=>`<p>${p}</p>`).join('')}</div><div class="unitMeta">preparando audio…</div></article>`}
for(const [id,cls] of [['exampleA','a'],['exampleB','b'],['exampleC','c']]){const root=document.getElementById(id);root.innerHTML=UNITS.map(unitHTML).join('');root.querySelectorAll('.unit').forEach(el=>registerView(el,cls))}
function registerView(el,variant){const st=states.get(el.dataset.unit);const v={el,variant,rail:el.querySelector('.rail'),track:el.querySelector('.railTrack'),buffer:el.querySelector('.railBuffer'),fill:el.querySelector('.railFill'),thumb:el.querySelector('.railThumb'),meta:el.querySelector('.unitMeta'),drag:null};st.views.push(v);bindRail(st,v);updateState(st)}
function currentClip(st){return st.chunks[st.current]}
function currentRatio(st){const c=currentClip(st);if(!c)return st.lastRatio||0;let f=st.pendingLocal||0;if(c.audio&&Number.isFinite(c.audio.duration)&&c.audio.duration>0)f=clamp(c.audio.currentTime/c.audio.duration,0,1);const r=clamp((c.start+(c.end-c.start)*f)/st.total,0,1);st.lastRatio=r;return r}
function bufferedRatio(st){let end=0;for(const c of st.chunks){if(c.status==='ready')end=c.end;else break}return clamp(end/st.total,0,1)}
function updateState(st){const p=currentRatio(st),b=bufferedRatio(st),loading=st.intent&&!st.playing;for(const v of st.views){if(!v.drag){v.thumb.style.top=`${p*100}%`;v.fill.style.height=`${p*100}%`}v.buffer.style.height=`${b*100}%`;v.thumb.dataset.playing=st.playing?'1':'0';v.thumb.classList.toggle('loading',loading);if(v.meta){v.meta.textContent=b>=.999?'audio completo':loading?'cargando este punto…':`${Math.round(b*100)}% precargado`}}updatePreloadStatus()}
function updateAll(){for(const st of states.values())updateState(st)}
function updatePreloadStatus(){let ready=0,total=0;for(const st of states.values())for(const c of st.chunks){total++;if(c.status==='ready')ready++}preloadStatus.textContent=ready===total?`Audio completo · ${ready}/${total} fragmentos listos`:`Precargando · ${ready}/${total} fragmentos listos`}
function stopOthers(st){if(activeUnit&&activeUnit!==st){activeUnit.intent=false;activeUnit.playing=false;currentClip(activeUnit)?.audio?.pause();updateState(activeUnit)}activeUnit=st}
function bindAudio(st,c){const a=c.audio;if(!a)return;a.ontimeupdate=()=>updateState(st);a.onplay=()=>{st.playing=true;updateState(st)};a.onpause=()=>{if(!a.ended){st.playing=false;updateState(st)}};a.onended=()=>advance(st)}
function setAudioTime(st,c,local,resume){const a=c.audio;if(!a)return;const go=()=>{a.currentTime=(a.duration||0)*clamp(local,0,1);st.pendingLocal=local;updateState(st);if(resume)playCurrent(st)};Number.isFinite(a.duration)&&a.duration>0?go():a.addEventListener('loadedmetadata',go,{once:true})}
async function playCurrent(st){stopOthers(st);st.intent=true;const c=currentClip(st);if(!c)return;if(c.status!=='ready'){enqueue(st,c,1000);pump();updateState(st);return}bindAudio(st,c);st.pendingLocal=clamp(st.pendingLocal,0,1);if(Number.isFinite(c.audio.duration)&&Math.abs(c.audio.currentTime/c.audio.duration-st.pendingLocal)>.04)c.audio.currentTime=c.audio.duration*st.pendingLocal;try{await c.audio.play();st.playing=true}catch{st.playing=false}updateState(st)}
function toggle(st){if(st.playing){st.intent=false;currentClip(st)?.audio?.pause();st.playing=false;updateState(st);return}playCurrent(st)}
function advance(st){if(st.current>=st.chunks.length-1){st.intent=false;st.playing=false;st.pendingLocal=1;updateState(st);return}st.current++;st.pendingLocal=0;st.playing=false;const c=currentClip(st);enqueue(st,c,1000);for(let i=1;i<=2;i++)if(st.chunks[st.current+i])enqueue(st,st.chunks[st.current+i],700-i*50);if(st.intent)playCurrent(st);updateState(st)}
function seek(st,ratio,resume){ratio=clamp(ratio,0,1);const target=ratio*st.total;let idx=st.chunks.findIndex(c=>target<=c.end);if(idx<0)idx=st.chunks.length-1;const old=currentClip(st);old?.audio?.pause();st.current=idx;st.playing=false;st.intent=!!resume;const c=currentClip(st),local=clamp((target-c.start)/Math.max(1,c.end-c.start),0,1);st.pendingLocal=local;enqueue(st,c,1200);for(let i=1;i<=3;i++)if(st.chunks[idx+i])enqueue(st,st.chunks[idx+i],800-i*50);if(c.status==='ready')setAudioTime(st,c,local,resume);else if(resume)playCurrent(st);updateState(st);pump()}
function bindRail(st,v){const ratioFromY=y=>{const r=v.track.getBoundingClientRect();return clamp((y-r.top)/Math.max(1,r.height),0,1)};v.rail.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();const onThumb=e.target.closest('.railThumb');v.drag={id:e.pointerId,startY:e.clientY,onThumb:!!onThumb,moved:false,resume:st.playing||st.intent};try{v.rail.setPointerCapture(e.pointerId)}catch{};if(!onThumb){currentClip(st)?.audio?.pause();st.playing=false;st.intent=false;v.rail.classList.add('dragging');const r=ratioFromY(e.clientY);v.thumb.style.top=`${r*100}%`;v.fill.style.height=`${r*100}%`}});v.rail.addEventListener('pointermove',e=>{if(!v.drag||v.drag.id!==e.pointerId)return;if(Math.abs(e.clientY-v.drag.startY)>4)v.drag.moved=true;if(v.drag.moved){currentClip(st)?.audio?.pause();st.playing=false;st.intent=false;v.rail.classList.add('dragging');const r=ratioFromY(e.clientY);v.thumb.style.top=`${r*100}%`;v.fill.style.height=`${r*100}%`}});const end=e=>{if(!v.drag||v.drag.id!==e.pointerId)return;const d=v.drag;v.drag=null;v.rail.classList.remove('dragging');try{v.rail.releasePointerCapture(e.pointerId)}catch{};if(d.onThumb&&!d.moved)toggle(st);else seek(st,ratioFromY(e.clientY),d.resume)};v.rail.addEventListener('pointerup',end);v.rail.addEventListener('pointercancel',end)}
function enqueue(st,c,priority){if(!c||c.status==='ready'||c.status==='generating')return;const existing=queue.find(j=>j.c===c);if(existing){existing.priority=Math.max(existing.priority,priority);queue.sort((a,b)=>b.priority-a.priority);return}c.queued=true;c.status='queued';queue.push({st,c,priority});queue.sort((a,b)=>b.priority-a.priority)}
async function reservePost(){let release;const mine=new Promise(r=>release=r),prev=postGate;postGate=mine;await prev;const wait=Math.max(0,POST_GAP-(Date.now()-lastPost));if(wait)await sleep(wait);lastPost=Date.now();release()}
async function accept(st,c,r){const blob=await r.blob();c.url=URL.createObjectURL(blob);c.audio=new Audio(c.url);c.audio.preload='auto';c.status='ready';c.queued=false;bindAudio(st,c);c.audio.load();if(st.intent&&currentClip(st)===c)playCurrent(st);updateState(st)}
async function generate(st,c){c.status='generating';c.queued=false;c.attempts++;await reservePost();try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({voicePrompt:VOICE_PROMPT,text:c.text,messageId:msgId(st,c)})});if(r.ok){await accept(st,c,r);return}if(r.status===429){c.status='idle';await sleep(10000);enqueue(st,c,500);return}}catch{}c.status='idle';await sleep(Math.min(30000,3000+c.attempts*4000));enqueue(st,c,300)}
async function pump(){while(activeJobs<WORKERS&&queue.length){const job=queue.shift();if(job.c.status==='ready'||job.c.status==='generating')continue;activeJobs++;generate(job.st,job.c).finally(()=>{activeJobs--;pump()})}}
async function checkCache(st,c){c.status='checking';try{const r=await fetch(`${API}?id=${encodeURIComponent(msgId(st,c))}`,{cache:'no-store'});if(r.ok){await accept(st,c,r);return true}}catch{}c.status='idle';return false}
async function preloadAll(){updatePreloadStatus();const checks=[];for(const st of states.values())for(const c of st.chunks)checks.push(checkCache(st,c));await Promise.allSettled(checks);for(const st of states.values()){if(st.chunks[0]?.status!=='ready')enqueue(st,st.chunks[0],900);if(st.chunks[1]?.status!=='ready')enqueue(st,st.chunks[1],700)}for(const st of states.values())for(let i=2;i<st.chunks.length;i++)if(st.chunks[i].status!=='ready')enqueue(st,st.chunks[i],200);pump();updateAll()}
preloadAll();setInterval(updateAll,300);
})();