plugins { id 'com.android.application' }

android {
    namespace 'ar.prometeo.kindlebridge'
    compileSdk 35

    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }

    defaultConfig {
        applicationId 'ar.prometeo.kindlebridge'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
}

dependencies {
    implementation 'com.github.mwiede:jsch:0.2.26'
}
