create table if not exists public.creator_media_probe_log (
  id bigint generated by default as identity primary key,
  owner_id uuid not null,
  provider text not null,
  modality text not null check (modality in ('image','video','image_to_video','audio')),
  status text not null check (status in ('PASS','CAPACITY','FAILED')),
  detail jsonb not null default '{}'::jsonb,
  tested_at timestamptz not null default now()
);

create index if not exists creator_media_probe_log_provider_idx
  on public.creator_media_probe_log(owner_id, provider, modality, tested_at desc);

alter table public.creator_media_probe_log enable row level security;

drop policy if exists creator_media_probe_owner_select on public.creator_media_probe_log;
create policy creator_media_probe_owner_select
  on public.creator_media_probe_log
  for select
  using (owner_id = auth.uid());
