/* Prometeo Classes Engine v1.1 — pure pedagogy/state engine. */
((global)=>{'use strict';if(global.PrometeoClasses)return;const clone=v=>structuredClone(v),now=()=>new Date().toISOString();
function normalizeConfig(c){if(!c?.id)throw new Error('Class id required');const topicIds=new Set(),exerciseIds=new Set();const topics=(c.topics||[]).map((t,ti)=>{const id=t.id||`topic-${ti+1}`;if(topicIds.has(id))throw new Error(`Duplicate topic ${id}`);topicIds.add(id);const exercises=(t.exercises||[]).map((e,ei)=>{const eid=e.id||`${id}-ex-${ei+1}`;if(exerciseIds.has(eid))throw new Error(`Duplicate exercise ${eid}`);exerciseIds.add(eid);return{...e,id:eid,required:e.required!==false,maxHints:e.maxHints??3,hints:Array.isArray(e.hints)?clone(e.hints):e.hints||[]};});return{...t,id,title:t.title||`Tema ${ti+1}`,theory:Array.isArray(t.theory)?clone(t.theory):t.theory||[],exercises};});const{topics:_ignored,...rest}=c;return Object.freeze({...rest,topics});}
function flat(config){return config.topics.flatMap(t=>t.exercises);}
function initialState(config,seed={}){const defaults={};flat(config).forEach((e,i)=>{defaults[e.id]={status:i===0?'AVAILABLE':'LOCKED',attempts:0,hintsUsed:0,lastAnswer:null,correct:false,postponed:false,updatedAt:null};});const incoming=seed.exercises||{},exercises={};for(const id of Object.keys(defaults))exercises[id]={...defaults[id],...clone(incoming[id]||{})};const state={schema:'prometeo.class-state/v1',classId:config.id,studentId:seed.studentId||config.studentId||null,startedAt:seed.startedAt||null,updatedAt:seed.updatedAt||null,currentExerciseId:defaults[seed.currentExerciseId]?seed.currentExerciseId:(Object.keys(exercises)[0]||null),exercises,events:Array.isArray(seed.events)?clone(seed.events):[]};unlock(config,state);return state;}
function unlock(config,state){const list=flat(config);for(let i=0;i<list.length;i++){const e=list[i],s=state.exercises[e.id];if(!s)continue;if(i===0){if(s.status==='LOCKED')s.status='AVAILABLE';continue;}const prev=state.exercises[list[i-1].id];if((prev?.correct||prev?.postponed)&&s.status==='LOCKED')s.status='AVAILABLE';}}
function record(state,type,payload={}){state.updatedAt=now();state.events.push({seq:state.events.length+1,type,at:state.updatedAt,...clone(payload)});}
const norm=v=>String(v??'').trim().toLowerCase().replace(/\s+/g,' ');
function answerMatches(e,answer){if(typeof e.check==='function')return!!e.check(answer);if(Array.isArray(e.correctAnswer)){const setMode=e.multiple===true||e.inputType==='multi'||e.answerMode==='set';if(setMode){if(!Array.isArray(answer))return false;const a=[...new Set(answer.map(norm))].sort(),b=[...new Set(e.correctAnswer.map(norm))].sort();return a.length===b.length&&a.every((v,i)=>v===b[i]);}return e.correctAnswer.map(norm).includes(norm(answer));}return norm(answer)===norm(e.correctAnswer);}
function reduce(config,state,action){const next=clone(state);const e=flat(config).find(x=>x.id===(action.exerciseId||next.currentExerciseId));if(!e&&action.type!=='START')throw new Error('Exercise not found');const s=e?next.exercises[e.id]:null;switch(action.type){case'START':next.startedAt=next.startedAt||now();record(next,'CLASS_STARTED');break;case'FOCUS':if(s.status==='LOCKED')throw new Error('Exercise locked');next.currentExerciseId=e.id;record(next,'EXERCISE_FOCUSED',{exerciseId:e.id});break;case'ANSWER':if(s.status==='LOCKED')throw new Error('Exercise locked');s.attempts++;s.lastAnswer=clone(action.answer);s.correct=answerMatches(e,action.answer);s.status=s.correct?'DONE':'AVAILABLE';s.updatedAt=now();record(next,s.correct?'ANSWER_CORRECT':'ANSWER_INCORRECT',{exerciseId:e.id,attempt:s.attempts});if(s.correct){const list=flat(config),idx=list.findIndex(x=>x.id===e.id),n=list[idx+1];if(n){next.exercises[n.id].status='AVAILABLE';next.currentExerciseId=n.id;}}break;case'HINT':if(s.status==='LOCKED')throw new Error('Exercise locked');if(s.hintsUsed>=e.maxHints){record(next,'HINT_EXHAUSTED',{exerciseId:e.id,level:s.hintsUsed});break;}s.hintsUsed++;record(next,'HINT_USED',{exerciseId:e.id,level:s.hintsUsed});break;case'POSTPONE':if(s.status==='LOCKED')throw new Error('Exercise locked');s.postponed=true;record(next,'EXERCISE_POSTPONED',{exerciseId:e.id});{const list=flat(config),idx=list.findIndex(x=>x.id===e.id),n=list[idx+1];if(n){next.exercises[n.id].status='AVAILABLE';next.currentExerciseId=n.id;}}break;case'RESET_EXERCISE':{const wasLocked=s.status==='LOCKED';next.exercises[e.id]={status:wasLocked?'LOCKED':'AVAILABLE',attempts:0,hintsUsed:0,lastAnswer:null,correct:false,postponed:false,updatedAt:now()};record(next,'EXERCISE_RESET',{exerciseId:e.id});break;}default:throw new Error(`Unknown class action ${action.type}`);}unlock(config,next);return next;}
function progress(config,state){const list=flat(config).filter(e=>e.required!==false),done=list.filter(e=>state.exercises[e.id]?.correct).length;return{done,total:list.length,ratio:list.length?done/list.length:1};}
function create(configInput,seed={}){const config=normalizeConfig(configInput);let state=initialState(config,seed);const listeners=new Set();return Object.freeze({config,getState:()=>clone(state),dispatch:a=>{state=reduce(config,state,a);listeners.forEach(fn=>fn(clone(state),a));return clone(state);},progress:()=>progress(config,state),subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn);}});}
global.PrometeoClasses=Object.freeze({version:'1.1.0-candidate',create,normalizeConfig,initialState,reduce,progress,answerMatches});})(typeof globalThis!=='undefined'?globalThis:window);
