'use strict';
const API='https://catnohyouxqjjtseaueb.supabase.co/functions/v1/pinterest-image-search-v1';
const KEY='pql-v1-7f2b9e31';
const STORE='prometeo.reference-curator.v1';
const useCases=['General','Spaces · tunnel','Spaces · floor texture','Spaces · wall pattern','Player · IDLE','Player · GRAB','Player · POINT','Player · ATTACK','Player · OFFER','Avatar · face','Avatar · body/limb','Trail · silhouette','Brutalist scale','Collage material','Reference only'];
const reasonTags=['production-useful','reference-only','too clean','too dark','too generic','strong silhouette','good material','good scale','good pose','creepy','brutalist','collage'];
const handStates=['IDLE','GRAB','POINT','ATTACK','OFFER'];
const stop=new Set('a an the of for and or to in on with from de la el los las un una para por con y o en del al is are image photo photography reference visual'.split(' '));
const baseState={version:1,reactions:{},ab:[],history:[],collections:{Favorites:[],Rejected:[],IDLE:[],GRAB:[],POINT:[],ATTACK:[],OFFER:[]}};
let state=load(),results=[],current=-1,view='search',comparePair=[null,null],selectedReasonTags=new Set();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function load(){try{return {...structuredClone(baseState),...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return structuredClone(baseState)}}
function persist(){localStorage.setItem(STORE,JSON.stringify(state));renderSide()}
function clean(s){return String(s||'').trim().replace(/s+/g,' ')}
function tokens(s){return clean(s).toLowerCase().replace(/[^a-z0-9áéíóúñü-]+/gi,' ').split(/s+/).filter(x=>x.length>2&&!stop.has(x))}
function reactionWeight(r){if(!r)return 0;let w=0;if(r.reaction==='like')w+=2;if(r.reaction==='save')w+=3;if(r.reaction==='dislike')w-=3;return w}
function profile(){const scores={};for(const r of Object.values(state.reactions)){const w=reactionWeight(r);for(const t of new Set(tokens((r.variantQuery||'')+' '+(r.reason||'')+' '+(r.tags||[]).join(' '))))scores[t]=(scores[t]||0)+w}for(const x of state.ab){for(const t of new Set(tokens(x.winnerQuery||'')))scores[t]=(scores[t]||0)+2;for(const t of new Set(tokens(x.loserQuery||'')))scores[t]=(scores[t]||0)-1}return scores}
function learnedTerms(base,limit=4){const p=profile(),bt=new Set(tokens(base));return Object.entries(p).filter(([t,s])=>s>0&&!bt.has(t)).sort((a,b)=>b[1]-a[1]).slice(0,limit).map(x=>x[0])}
function rejectedTerms(base,limit=3){const p=profile(),bt=new Set(tokens(base));return Object.entries(p).filter(([t,s])=>s<0&&!bt.has(t)).sort((a,b)=>a[1]-b[1]).slice(0,limit).map(x=>x[0])}
function makeVariants(base){const learned=learnedTerms(base),bad=rejectedTerms(base),ctx=$('#useCase').value;const ctxTerms=tokens(ctx.replace('·',' ')).filter(t=>!['general'].includes(t));const positive=[...new Set([...learned,...ctxTerms])].slice(0,5);return [
 {id:'original',label:'A · original',query:base,why:'Consulta original sin aprendizaje.'},
 {id:'learned',label:'B · memoria',query:clean(base+' '+positive.join(' ')),why:positive.length?'Añade términos favorecidos por tu historial/contexto: '+positive.join(', ')+'.':'Todavía no hay suficientes preferencias; queda cerca del original.'},
 {id:'counter',label:'C · contraprueba',query:clean(base+' '+ctxTerms.slice(0,2).join(' ')),why:bad.length?'Evita reforzar términos castigados repetidamente: '+bad.join(', ')+'.':'Variante contextual para comparar sin fingir aprendizaje inexistente.'}
]}
function renderVariants(vs){$('#variants').replaceChildren(...vs.map(v=>{const d=document.createElement('div');d.className='variant';d.dataset.id=v.id;d.innerHTML='<div class="varianthead"><b></b><span></span></div><input><div class="why"></div>';d.querySelector('b').textContent=v.label;d.querySelector('span').textContent=v.id;d.querySelector('input').value=v.query;d.querySelector('.why').textContent=v.why;return d}))}
async function fetchVariant(v,base){const url=new URL(API);url.searchParams.set('q',v.query);url.searchParams.set('limit','10');url.searchParams.set('k',KEY);const res=await fetch(url,{headers:{'x-prometeo-lab':'reference-curator-v1'}});const data=await res.json().catch(()=>({ok:false,error:'INVALID_RESPONSE'}));if(!res.ok||!data.ok)throw new Error(data.error||('HTTP_'+res.status));return (data.results||[]).map(x=>({...x,baseQuery:base,variantId:v.id,variantQuery:v.query,variantWhy:v.why,mediaType:'image',searchedAt:new Date().toISOString()}))}
async function runSearch(base,preserve=false){base=clean(base);if(!base)return;let vs;if(preserve&&$('#variants').children.length){vs=[...$('#variants').querySelectorAll('.variant')].map(el=>({id:el.dataset.id,label:el.querySelector('b').textContent,query:clean(el.querySelector('input').value),why:el.querySelector('.why').textContent}))}else{vs=makeVariants(base);renderVariants(vs);}$('#gallery').classList.add('loading');$('#heading').textContent='Buscando · '+base;$('#empty').style.display='none';try{const edited=[...$('#variants').querySelectorAll('.variant')].map((el,i)=>({...vs[i],query:clean(el.querySelector('input').value)}));const batches=await Promise.allSettled(edited.map(v=>fetchVariant(v,base)));const all=[];const seen=new Set();for(const b of batches)if(b.status==='fulfilled')for(const item of b.value){const key=item.id||item.image;if(!seen.has(key)){seen.add(key);all.push(item)}}results=all;state.history.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),base,useCase:$('#useCase').value,variants:edited.map(v=>({id:v.id,query:v.query,why:v.why})),resultCount:all.length});state.history=state.history.slice(0,80);persist();view='search';syncNav();renderGallery();$('#heading').textContent=base+' · '+all.length+' referencias';if(!all.length){$('#empty').style.display='block';$('#empty').textContent='La búsqueda volvió sin resultados.'}}catch(e){$('#empty').style.display='block';$('#empty').textContent='No se pudo completar la búsqueda: '+e.message;$('#heading').textContent='Error de búsqueda'}finally{$('#gallery').classList.remove('loading')}}
