function keyOf(x){return x?.id||x?.image||''}
function renderGallery(items=results){const g=$('#gallery');g.innerHTML='';for(const [i,item] of items.entries()){const k=keyOf(item),r=state.reactions[k];const c=document.createElement('article');c.className='card';c.innerHTML='<img><div class="cardmeta"><b></b><small></small></div>';const img=c.querySelector('img');img.src=item.image;img.alt=item.title||'Referencia';img.loading=i<8?'eager':'lazy';img.referrerPolicy='no-referrer';c.querySelector('b').textContent=item.title||'Sin título';c.querySelector('small').textContent=(item.variantId||'historial')+' · '+(r?.reaction||'sin decidir');if(r){const m=document.createElement('span');m.className='mark';m.textContent=r.reaction.toUpperCase();c.append(m)}c.addEventListener('click',()=>openMuseumByItem(item));g.append(c)}$('#empty').style.display=items.length?'none':'block'}
function allKnown(){const m=new Map();for(const x of results)m.set(keyOf(x),x);for(const r of Object.values(state.reactions))if(r.item)m.set(keyOf(r.item),r.item);return [...m.values()]}
function setView(v){view=v;syncNav();let items=[];if(v==='search')items=results;if(v==='saved')items=allKnown().filter(x=>state.reactions[keyOf(x)]?.reaction==='save');if(v==='rejected')items=allKnown().filter(x=>state.reactions[keyOf(x)]?.reaction==='dislike');if(v==='history'){renderHistoryPage();return}renderGallery(items);$('#heading').textContent=v==='search'?'Resultados actuales':v==='saved'?'Guardadas':v==='rejected'?'Rechazadas':v}
function renderHistoryPage(){const g=$('#gallery');g.innerHTML='';g.style.columns='1';for(const h of state.history){const d=document.createElement('div');d.className='variant';d.innerHTML='<div class="varianthead"><b></b><span></span></div><div class="why"></div>';d.querySelector('b').textContent=h.base;d.querySelector('span').textContent=new Date(h.at).toLocaleString();d.querySelector('.why').textContent=(h.useCase||'General')+' · '+h.resultCount+' resultados · '+h.variants.map(x=>x.query).join(' / ');g.append(d)}$('#heading').textContent='Historial de búsqueda';$('#empty').style.display=state.history.length?'none':'block'}
function syncNav(){$$('.navbtn').forEach(b=>b.classList.toggle('on',b.dataset.view===view));$('#gallery').style.columns=view==='history'?'1':''}
function openMuseumByItem(item){const arr=view==='search'?results:allKnown();current=Math.max(0,arr.findIndex(x=>keyOf(x)===keyOf(item)));results=view==='search'?results:arr;openMuseum()}
function openMuseum(){const item=results[current];if(!item)return;$('#hero').src=item.image;$('#heroTitle').textContent=item.title||'Sin título';$('#heroProv').textContent='query: '+(item.variantQuery||item.baseQuery||'desconocida')+' · '+(item.variantWhy||'sin explicación registrada');$('#source').href=item.source_url||item.image;$('#mediaNote').textContent='Media detectada por metadata disponible: '+(item.mediaType||'image')+'. GIF/video no confirmado por el backend actual.';const r=state.reactions[keyOf(item)]||{};$('#reason').value=r.reason||'';selectedReasonTags=new Set(r.tags||[]);renderReasonTags();renderHandTags(r.handState||'');$('#overlay').classList.add('open')}
function step(n){if(!results.length)return;current=(current+n+results.length)%results.length;openMuseum()}
function renderReasonTags(){const host=$('#quickReasons');host.innerHTML='';for(const t of reasonTags){const b=document.createElement('button');b.textContent=t;b.classList.toggle('on',selectedReasonTags.has(t));b.onclick=()=>{selectedReasonTags.has(t)?selectedReasonTags.delete(t):selectedReasonTags.add(t);renderReasonTags()};host.append(b)}}
function renderHandTags(active){const host=$('#handTags');host.innerHTML='';for(const t of handStates){const b=document.createElement('button');b.textContent='Player '+t;b.classList.toggle('on',active===t);b.onclick=()=>saveContext(null,t);host.append(b)}}
function react(kind){saveContext(kind,null)}
function saveContext(kind,handState){const item=results[current];if(!item)return;const k=keyOf(item),old=state.reactions[k]||{};const reaction=kind||old.reaction||'like';const next={...old,item,reaction,useCase:$('#useCase').value,tags:[...selectedReasonTags],reason:clean($('#reason').value),handState:handState||old.handState||'',variantId:item.variantId,variantQuery:item.variantQuery,baseQuery:item.baseQuery,mediaType:item.mediaType||'image',sourceUrl:item.source_url||'',at:new Date().toISOString()};state.reactions[k]=next;for(const name of Object.keys(state.collections))state.collections[name]=state.collections[name].filter(x=>x!==k);if(reaction==='save')state.collections.Favorites.push(k);if(reaction==='dislike')state.collections.Rejected.push(k);if(next.handState&&state.collections[next.handState])state.collections[next.handState].push(k);persist();renderGallery();toast((kind||'contexto')+' guardado');if(handState)renderHandTags(handState)}
function renderSide(){const rs=Object.values(state.reactions);$('#decisionCount').textContent=rs.length;$('#abCount').textContent=state.ab.length;$('#searchCount').textContent=state.history.length;const p=profile(),terms=Object.entries(p).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).slice(0,12);const prof=$('#profile');prof.innerHTML='';if(!terms.length)prof.innerHTML='<div class="notice">Todavía sin señal suficiente.</div>';for(const [t,s] of terms){const d=document.createElement('div');d.className='profileTerm '+(s>=0?'pos':'neg');d.innerHTML='<b></b><div class="bar"><i></i></div><span></span>';d.querySelector('b').textContent=t;d.querySelector('i').style.width=Math.min(100,15+Math.abs(s)*12)+'%';d.querySelector('span').textContent=(s>0?'+':'')+s;prof.append(d)}const h=state.history[0];$('#historyMini').innerHTML=h?'<div class="historyItem"><b>'+escapeHtml(h.base)+'</b><small>'+escapeHtml(h.useCase||'General')+' · '+h.resultCount+' resultados<br>'+h.variants.map(x=>escapeHtml(x.query)).join('<br>')+'</small></div>':'<div class="notice">Sin búsquedas todavía.</div>';const col=$('#collections');col.innerHTML='';for(const [name,ids] of Object.entries(state.collections)){const b=document.createElement('button');b.className='navbtn';b.textContent=name+' · '+ids.length;b.onclick=()=>showCollection(name);col.append(b)}}
function showCollection(name){const ids=new Set(state.collections[name]||[]),items=allKnown().filter(x=>ids.has(keyOf(x)));view='collection';syncNav();renderGallery(items);$('#heading').textContent=name+' · '+items.length}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function randomPair(){const pool=results.filter(x=>x?.image);if(pool.length<2){toast('Necesitás al menos 2 resultados');return false}const a=Math.floor(Math.random()*pool.length);let b=a;while(b===a)b=Math.floor(Math.random()*pool.length);comparePair=[pool[a],pool[b]];$('#imgA').src=comparePair[0].image;$('#imgB').src=comparePair[1].image;$('#compareTitle').textContent='¿Cuál es mejor para '+$('#useCase').value+'?';return true}
function openCompare(){if(randomPair())$('#compare').classList.add('open')}
function win(side){const winner=side==='a'?comparePair[0]:comparePair[1],loser=side==='a'?comparePair[1]:comparePair[0];state.ab.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),useCase:$('#useCase').value,winner:keyOf(winner),loser:keyOf(loser),winnerQuery:winner.variantQuery||winner.baseQuery||'',loserQuery:loser.variantQuery||loser.baseQuery||''});state.ab=state.ab.slice(0,120);persist();toast('Preferencia A/B guardada');randomPair()}
function refine(){const q=clean($('#query').value||state.history[0]?.base||'');if(!q)return toast('Primero escribí una búsqueda');const terms=learnedTerms(q,5),bad=rejectedTerms(q,5);const next=clean(q+' '+terms.join(' '));$('#query').value=next;toast(terms.length?'Refinado con: '+terms.join(', '):'Todavía no hay señal positiva suficiente');renderVariants(makeVariants(next));if(bad.length)$('#variants .variant:nth-child(2) .why').textContent+=' Se penalizan: '+bad.join(', ')+'.'}
function exportMemory(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='prometeo-reference-curator-memory-v1.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)}
for(const u of useCases){const o=document.createElement('option');o.value=o.textContent=u;$('#useCase').append(o)}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();runSearch($('#query').value)});$$('.navbtn[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#close').onclick=()=>$('#overlay').classList.remove('open');$('#prev').onclick=()=>step(-1);$('#next').onclick=()=>step(1);$$('[data-react]').forEach(b=>b.onclick=()=>react(b.dataset.react));$('#saveNote').onclick=()=>saveContext(null,null);$('#rerunBtn').onclick=()=>runSearch(clean($('#query').value||state.history[0]?.base||''),true);$('#compareBtn').onclick=openCompare;$('#closeCompare').onclick=()=>$('#compare').classList.remove('open');$('#skipPair').onclick=randomPair;$$('[data-win]').forEach(b=>b.onclick=()=>win(b.dataset.win));$('#refineBtn').onclick=refine;$('#exportBtn').onclick=exportMemory;document.addEventListener('keydown',e=>{if(!$('#overlay').classList.contains('open'))return;if(e.key==='ArrowLeft')step(-1);if(e.key==='ArrowRight')step(1);if(e.key==='Escape')$('#overlay').classList.remove('open')});
renderVariants(makeVariants(''));renderGallery();renderSide();
